#!/usr/bin/env python3
"""PreToolUse hook: enforce the AI-text marking rules of AI_USAGE_POLICY.md.

Text an agent posts to GitHub is AI-generated by definition, so:

1. `gh pr comment`, `gh issue comment`, `gh pr review`, and `gh api` calls
   with a `body` field (comments, review replies) must start with 🤖.
2. `gh pr create` / `gh pr edit` bodies must contain the 🤖 marker and an
   AI Influence Level tag `AIL0`-`AIL4` (`AIL5` is not accepted).
"""
import json
import re
import shlex
import sys
from pathlib import Path

MARKER = "🤖"
AIL_RE = re.compile(r"\bAIL[0-9]\b")
HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)


def read_file(path):
    p = Path(path)
    return p.read_text(encoding="utf-8", errors="replace") if p.is_file() else None


def extract_body(tokens):
    """Body from --body/-b/--body-file/-F and from `gh api` -f/-F/--field/--raw-field body=."""
    for i, t in enumerate(tokens):
        nxt = tokens[i + 1] if i + 1 < len(tokens) else None
        if t in ("--body", "-b") and nxt is not None:
            return nxt
        if t.startswith("--body="):
            return t.split("=", 1)[1]
        if t in ("--body-file",) and nxt is not None:
            return read_file(nxt)
        if t.startswith("--body-file="):
            return read_file(t.split("=", 1)[1])
        if t in ("-F", "-f", "--field", "--raw-field") and nxt is not None and nxt.startswith("body="):
            value = nxt.split("=", 1)[1]
            return read_file(value[1:]) if t in ("-F", "--field") and value.startswith("@") else value
        if t == "-F" and nxt is not None and not nxt.startswith("body="):
            # `gh pr create -F <file>`: -F is --body-file there
            return read_file(nxt)
    return None


def deny(reason):
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))
    sys.exit(0)


def main():
    try:
        data = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)
    if data.get("tool_name") != "Bash":
        sys.exit(0)
    cmd = data.get("tool_input", {}).get("command", "")

    is_pr_body = re.search(r"\bgh\s+pr\s+(create|edit)\b", cmd)
    is_comment = re.search(r"\bgh\s+(pr\s+(comment|review)|issue\s+comment)\b", cmd) or (
        re.search(r"\bgh\s+api\b", cmd) and re.search(r"(^|\s)(-f|-F|--field|--raw-field)\s+body=", cmd)
    )
    if not (is_pr_body or is_comment):
        sys.exit(0)

    try:
        tokens = shlex.split(cmd, posix=True)
    except ValueError:
        sys.exit(0)
    body = extract_body(tokens)
    if body is None:
        sys.exit(0)  # no readable body (heredoc/stdin/editor) - other guards or the human handle it

    if is_pr_body:
        body = HTML_COMMENT_RE.sub("", body)  # template comments mention AIL tags as examples
        problems = []
        if MARKER not in body:
            problems.append(f"the {MARKER} marker at the top of the Summary section")
        ail = AIL_RE.search(body)
        if not ail:
            problems.append("an AI Influence Level tag AIL0-AIL4 in the \"AI usage\" section")
        elif ail.group() not in ("AIL0", "AIL1", "AIL2", "AIL3", "AIL4"):
            problems.append(f"{ail.group()} is not accepted - fully AI-generated PRs are closed (AI_USAGE_POLICY.md)")
        if problems:
            deny("PR body violates AI_USAGE_POLICY.md; missing:\n" + "\n".join(f"  - {p}" for p in problems))
    elif not body.lstrip().startswith(MARKER):
        deny(
            f"AI-generated text posted to GitHub must start with {MARKER} "
            f"(e.g. '{MARKER} Generated with <tool>'), see AI_USAGE_POLICY.md. "
            "Unmarked AI-generated text leads to the PR being closed."
        )
    sys.exit(0)


if __name__ == "__main__":
    main()
