version=${version}
year=${year}
maintainers=${maintainers}
azureInstrumentationKey=${azureInstrumentationKey}

astrophysicsDataSystemAPIKey=${astrophysicsDataSystemAPIKey}
biodiversityHeritageApiKey=${biodiversityHeritageApiKey}
crossRefEmail=${crossRefEmail}
ieeeAPIKey=${ieeeAPIKey}
medlineApiKey=${medlineApiKey}
openAlexApiKey=${openAlexApiKey}
scholarApiKey=${scholarApiKey}
semanticScholarApiKey=${semanticScholarApiKey}
springerNatureAPIKey=${springerNatureAPIKey}
wileyTdmApiKey=${wileyTdmApiKey}
