# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # https://portal.cloud.hashicorp.com/vagrant/discover/aaronvonawesome/linux-mint-21-cinnamon
  config.vm.box = "aaronvonawesome/linux-mint-21-cinnamon"
  # config.vm.box = "archman/linuxmint" # v22

  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true

  config.vm.provider "virtualbox" do |v|
    v.name = "jabref-linux-mint-cinnamon"
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y upgrade
    sudo apt-get install -y git
  SHELL

  # Install JDK, clone JabRef's source code, and do an initial build
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install java 21.0.4-tem < /dev/null
    git clone --recurse-submodules https://github.com/JabRef/jabref.git
    cd jabref
    sdk use java 21.0.4-tem
    ./gradlew jar
  SHELL

  config.ssh.forward_x11 = true
end
