# Documentation: https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
      name: "linux"
    mac:
      imageName: "macOS-latest"
      name: "mac"
    windows:
      imageName: "windows-latest"
      name: "windows"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      tasks: 'jlinkZip'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/build/image.zip'
      artifactName: 'JabRef-$(name).zip'