coverage:
  ignore:
  - src/gen/.*
  status:
    patch: false
  project:
    default:
      threshold: 0.01
comment:
  branches:
    - "do-not-add-comment-to-any-branch-please"
  require_changes: true
