FROM gradle:jdk24-noble AS build

WORKDIR /app

COPY . .

RUN gradle --no-daemon :jabsrv-cli:shadowJar

RUN mv jabsrv-cli/build/libs/jabsrv*-all.jar jabsrv.jar

FROM eclipse-temurin:24-jre AS runtime

WORKDIR /app

COPY --from=build /app/jabsrv.jar .

EXPOSE 6050

# Run server
ENTRYPOINT ["java", "-jar", "jabsrv.jar"]
