# based on https://github.com/snapcore/snapcraft/blob/master/demos/gradle/snap/snapcraft.yaml

name: jabref

# the version string 4.2-dev is replaced by scripts/run-snapcraft.sh with the current version provided in build.gradle
version: '4.2-dev'

summary: Bibliography manager
icon: buildres/snapcraft/JabRef-icon-256.png
description: JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.

# only with the following set to stable + strict, we can do a full release

# see https://snapcraft.io/docs/reference/channels
# stable | devel
grade: devel

# see https://snapcraft.io/docs/reference/confinement
# strict | devmode
confinement: strict

apps:
   jabref:
     command: desktop-launch java -jar $SNAP/jar/JabRef-4.2-dev.jar
     plugs: [desktop, desktop-legacy, wayland, unity7, home, network-bind]
     desktop: ../buildres/snapcraft/jabref.desktop

parts:
  jabref:
    plugin: gradle
    source: .
    stage-packages: [default-jre, openjfx, x11-utils]
    gradle-options: [snapJar]
    gradle-output-dir: 'build/releases'
    after: [desktop-gtk3]
