package org.jabref.logic.journals;

import java.util.ArrayList;
import java.util.List;

class BuiltInJournalsList {

    private static final List<Abbreviation> builtInList = new ArrayList<>(942);

    static {
        builtInList.add(new Abbreviation("Health Care Financing Review. Annual Supplement", "Health Care Financ. Rev. Annu. Suppl."));
        builtInList.add(new Abbreviation("Journal of Neurocytology", "J. Neurocytol."));
        builtInList.add(new Abbreviation("Structure and Bonding", "Struct. Bond."));
        builtInList.add(new Abbreviation("Death Studies", "Death Stud."));
        builtInList.add(new Abbreviation("Experientia. Supplementum", "Experientia. Suppl."));
        builtInList.add(new Abbreviation("Food Microbiology", "Food Microbiol."));
        builtInList.add(new Abbreviation("Breastfeeding Review", "Breastfeed. Rev."));
        builtInList.add(new Abbreviation("Landarzt", "Landarzt"));
        builtInList.add(new Abbreviation("McGraw-Hill's Washington Report on Medicine and Health", "McGraw Hills Wash. Rep. Med. Health"));
        builtInList.add(new Abbreviation("Bulletin of the New York State Society of Dentistry for Children", "Bull. N. Y. State Soc. Dent. Child."));
        builtInList.add(new Abbreviation("Diabetic Medicine", "Diabet. Med."));
        builtInList.add(new Abbreviation("Plant Cell", "Plant Cell"));
        builtInList.add(new Abbreviation("Journal of Computed Tomography", "J. Comput. Tomogr."));
        builtInList.add(new Abbreviation("Accident Analysis and Prevention", "Accid. Anal. Prev."));
        builtInList.add(new Abbreviation("Advances in Ophthalmic, Plastic, and Reconstructive Surgery", "Adv. Ophthalmic. Plast. Reconstr. Surg."));
        builtInList.add(new Abbreviation("Annales Academiae Scientiarum Fennicae. Series A V, Medica", "Ann. Acad. Sci. Fenn. A"));
        builtInList.add(new Abbreviation("Midwives", "Midwives"));
        builtInList.add(new Abbreviation("Acta Biochimica et Biophysica Sinica", "Acta Biochim. Biophys. Sin."));
        builtInList.add(new Abbreviation("Evidence-Based Nursing", "Evid. Based Nurs."));
        builtInList.add(new Abbreviation("Geothermal Energy Science", "Geotherm. Energy Sci."));
        builtInList.add(new Abbreviation("Kumamoto Igakkai Zasshi (Journal of the Kumamoto Medical Society)", "Kumamoto Igakkai Zasshi"));
        builtInList.add(new Abbreviation("Frontiers in Pediatrics", "Front. Pediatr."));
        builtInList.add(new Abbreviation("Science in China, Series B: Chemistry", "Sci. China, Ser. B: Chem."));
        builtInList.add(new Abbreviation("Gastroenterologisches Journal", "Gastroenterol. J."));
        builtInList.add(new Abbreviation("Acta Crystallographica. Section A, Foundations of Crystallography", "Acta Crystallogr. A"));
        builtInList.add(new Abbreviation("Annales de Limnologie", "Ann. Limnol."));
        builtInList.add(new Abbreviation("ACS Infectious Diseases", "ACS Infect. Dis."));
        builtInList.add(new Abbreviation("FAO Food and Nutrition Series", "FAO Food Nutr. Ser."));
        builtInList.add(new Abbreviation("Revue Francaise d'Endocrinologie Clinique, Nutrition et Metabolisme", "Rev. Fr. Endocrinol. Clin."));
        builtInList.add(new Abbreviation("Medical Group Management Journal", "Med. Group Manage. J."));
        builtInList.add(new Abbreviation("Current Opinion in Structural Biology", "Curr. Opin. Struct. Biol."));
        builtInList.add(new Abbreviation("Computer Integrated Manufacturing Systems", "Comput. Integr. Manuf. Syst."));
        builtInList.add(new Abbreviation("Progress in Photovoltaics: Research and Applications", "Prog. Photovoltaics Res. Appl."));
        builtInList.add(new Abbreviation("Journal of Cellular Plastics", "J. Cell. Plast."));
        builtInList.add(new Abbreviation("International Journal of Security and Networks", "Int. J. Secur. Netw."));
        builtInList.add(new Abbreviation("Igaku to Seibutsugaku (Medicine and Biology)", "Igaku To Seibutsugaku"));
        builtInList.add(new Abbreviation("Biochemical Society Symposium", "Biochem. Soc. Symp."));
        builtInList.add(new Abbreviation("Management Review", "Manage. Rev."));
        builtInList.add(new Abbreviation("Journal of Gerontological Nursing", "J. Gerontol. Nurs."));
        builtInList.add(new Abbreviation("Pharmacopsychiatry", "Pharmacopsychiatry"));
        builtInList.add(new Abbreviation("Cooperador Dental", "Coop. Dent. (B. Aires)"));
        builtInList.add(new Abbreviation("Journal of Invasive Cardiology", "J. Invasive Cardiol."));
        builtInList.add(new Abbreviation("Mitteilungsblatt - Chemische Gesellschaft der Deutschen Demokratischen Republik", "Mitteilungsbl. - Chem. Ges. D. D. R."));
        builtInList.add(new Abbreviation("Experientia", "Experientia"));
        builtInList.add(new Abbreviation("Lattante", "Lattante"));
        builtInList.add(new Abbreviation("Polish Medical Sciences and History Bulletin", "Pol. Med. Sci. Hist. Bull."));
        builtInList.add(new Abbreviation("Current Opinion in Chemical Biology", "Curr. Opin. Chem. Biol."));
        builtInList.add(new Abbreviation("International Journal of Biometeorology", "Int. J. Biometeorol."));
        builtInList.add(new Abbreviation("Industrial Health", "Ind. Health"));
        builtInList.add(new Abbreviation("Physiological Chemistry and Physics", "Physiol. Chem. Phys."));
        builtInList.add(new Abbreviation("Gastroenterologia", "Gastroenterologia"));
        builtInList.add(new Abbreviation("Hospital Law Newsletter", "Hosp. Law Newsl."));
        builtInList.add(new Abbreviation("Beijing Da Xue Xue Bao. Yi Xue Ban (Journal of Peking University. Health Sciences)", "Beijing Da Xue Xue Bao"));
        builtInList.add(new Abbreviation("Journal of Surgical Oncology. Supplement", "J. Surg. Oncol. Suppl."));
        builtInList.add(new Abbreviation("Nippon Ishikai Zasshi (Journal of the Japan Medical Association)", "Nippon Ishikai Zasshi"));
        builtInList.add(new Abbreviation("Bruns' Beitrage fur Klinische Chirurgie", "Bruns Beitr. Klin. Chir."));
        builtInList.add(new Abbreviation("Pakistan Journal of Scientific Research", "Pak. J. Sci. Res."));
        builtInList.add(new Abbreviation("Journal of Contemporary Dental Practice", "J. Contemp. Dent. Pract."));
        builtInList.add(new Abbreviation("News Bulletin, Indian Dental Association", "News Bull. Indian Dent. Assoc."));
        builtInList.add(new Abbreviation("Yi Chuan Xue Bao (Acta Genetica Sinica)", "Yi Chuan Xue Bao"));
        builtInList.add(new Abbreviation("Food Chemistry", "Food Chem."));
        builtInList.add(new Abbreviation("Trends in Plant Science", "Trends Plant Sci."));
        builtInList.add(new Abbreviation("Development (Cambridge, United Kingdom)", "Development (Cambridge, U. K.)"));
        builtInList.add(new Abbreviation("Extractive Industries and Society", "Extr. Ind. Soc."));
        builtInList.add(new Abbreviation("Environmental Research", "Environ. Res."));
        builtInList.add(new Abbreviation("Pediatric Neurology", "Pediatr. Neurol."));
        builtInList.add(new Abbreviation("Endodoncia", "Endodoncia (Mex.)"));
        builtInList.add(new Abbreviation("International Journal of Applied Science and Technology", "Int. J. Appl. Sci. Technol."));
        builtInList.add(new Abbreviation("Rivista di Storia della Medicina", "Riv. Stor. Med."));
        builtInList.add(new Abbreviation("Journal of Drug Targeting", "J. Drug Targeting"));
        builtInList.add(new Abbreviation("Bildgebung", "Bildgebung"));
        builtInList.add(new Abbreviation("Biomedical Imaging and Intervention Journal", "Biomed. Imaging Intervention J."));
        builtInList.add(new Abbreviation("Investor-Owned Hospital Review", "Investor. Owned Hosp. Rev."));
        builtInList.add(new Abbreviation("Archives d'Ophtalmologie", "Arch. Ophtalmol. (Paris)"));
        builtInList.add(new Abbreviation("Alumni Bulletin, School of Dentistry, Indiana University", "Alumni Bull. Sch. Dent. Indiana Univ."));
        builtInList.add(new Abbreviation("Chemie Anlagen und Verfahren", "Chem. Anlagen Verfahren"));
        builtInList.add(new Abbreviation("Journal of Arid Environments", "J. Arid. Environ."));
        builtInList.add(new Abbreviation("Clinic", "Clinic (Paris)"));
        builtInList.add(new Abbreviation("Indian Journal of Industrial and Applied Mathematics", "Indian J. Ind. Appl. Math."));
        builtInList.add(new Abbreviation("Food Additives and Contaminants", "Food Addit. Contam."));
        builtInList.add(new Abbreviation("Changgeng Yi Xue Za Zhi (Chang Gung Medical Journal)", "Changgeng Yi Xue Za Zhi"));
        builtInList.add(new Abbreviation("Journal of Food Lipids", "J. Food Lipids"));
        builtInList.add(new Abbreviation("Journal of the Peripheral Nervous System", "J. Peripher. Nerv. Syst."));
        builtInList.add(new Abbreviation("Lymphatic Research and Biology", "Lymphat. Res. Biol."));
        builtInList.add(new Abbreviation("Journal of Clinical Densitometry", "J. Clin. Densitom."));
        builtInList.add(new Abbreviation("Scalpel", "Scalpel (Brux.)"));
        builtInList.add(new Abbreviation("British Journal of Psychology", "Br. J. Psychol."));
        builtInList.add(new Abbreviation("Critical Reviews in Toxicology", "Crit. Rev. Toxicol."));
        builtInList.add(new Abbreviation("Columbus Dental Society Bulletin", "Columbus Dent. Soc. Bull."));
        builtInList.add(new Abbreviation("Turk Hijiyen ve Tecrubi Biyoloji Dergisi", "Turk Hij. Tecr. Biyol. Derg."));
        builtInList.add(new Abbreviation("Journal of Polymer Science. Part B, Polymer Letters", "J. Polym. Sci. [B]"));
        builtInList.add(new Abbreviation("Italian General Review of Dermatology", "Ital. Gen. Rev. Dermatol."));
        builtInList.add(new Abbreviation("Neurophysiologie Clinique", "Neurophysiol. Clin."));
        builtInList.add(new Abbreviation("Acta Medica Nagasakiensia", "Acta Med. Nagasaki."));
        builtInList.add(new Abbreviation("Arquivos Brasileiros de Oftalmologia", "Arq. Bras. Oftalmol."));
        builtInList.add(new Abbreviation("Canadian Journal of Biochemistry", "Can. J. Biochem."));
        builtInList.add(new Abbreviation("South Dakota Medicine", "S. D. Med."));
        builtInList.add(new Abbreviation("Journal of the West Australian Nurses", "J. West Aust. Nurses"));
        builtInList.add(new Abbreviation("Journal of Immunology", "J. Immunol."));
        builtInList.add(new Abbreviation("Journal of Applied Mechanics", "J. Appl. Mech."));
        builtInList.add(new Abbreviation("Gerontology and Geriatrics Education", "Gerontol. Geriatr. Educ."));
        builtInList.add(new Abbreviation("Journal of Risk and Insurance", "J. Risk Insur."));
        builtInList.add(new Abbreviation("Contemporary Issues in Clinical Biochemistry", "Contemp. Issues Clin. Biochem."));
        builtInList.add(new Abbreviation("Operative Dentistry. Supplement", "Oper. Dent. Suppl."));
        builtInList.add(new Abbreviation("Proceedings, Annual Meeting of the Medical Section of the American Life Convention", "Proc. Annu. Meet. Med. Sect. Am. Life Conv."));
        builtInList.add(new Abbreviation("Journal of Applied Glycoscience", "J. Appl. Glycosci."));
        builtInList.add(new Abbreviation("Journal of Biomechanical Engineering", "J. Biomech. Eng."));
        builtInList.add(new Abbreviation("Journal de Biologie Buccale", "J. Biol. Buccale"));
        builtInList.add(new Abbreviation("Zeitschrift fur Naturforschung B: Journal of Chemical Sciences", "Z. Naturforsch., B: Chem. Sci."));
        builtInList.add(new Abbreviation("Clinics in Rheumatic Diseases", "Clin. Rheum. Dis."));
        builtInList.add(new Abbreviation("Microporous and Mesoporous Materials", "Microporous Mesoporous Mater."));
        builtInList.add(new Abbreviation("Journal of the Brazilian Chemical Society", "J. Braz. Chem. Soc."));
        builtInList.add(new Abbreviation("Report, Navy Medical Neuropsychiatric Research Unit", "Rep. Nav. Med. Neuropsychiatr. Res. Unit"));
        builtInList.add(new Abbreviation("Journal of Environmental Science and Health. Part C, Environmental Health Sciences", "J. Environ. Sci. Health [C]"));
        builtInList.add(new Abbreviation("Special Education", "Spec. Educ."));
        builtInList.add(new Abbreviation("Journal of Radioanalytical and Nuclear Chemistry", "J. Radioanal. Nucl. Chem."));
        builtInList.add(new Abbreviation("Journal of Quaternary Science", "J. Quat. Sci."));
        builtInList.add(new Abbreviation("Journal of the Association for Academic Minority Physicians", "J. Assoc. Acad. Minor. Phys."));
        builtInList.add(new Abbreviation("Pediatric Emergency Care", "Pediatr. Emerg. Care"));
        builtInList.add(new Abbreviation("International Review of Poultry Science", "Int. Rev. Poult. Sci."));
        builtInList.add(new Abbreviation("Radiologia Clinica", "Radiol. Clin. (Basel)"));
        builtInList.add(new Abbreviation("Appetite", "Appetite"));
        builtInList.add(new Abbreviation("Bulletin on the Rheumatic Diseases", "Bull. Rheum. Dis."));
        builtInList.add(new Abbreviation("Journal of Petrology", "J. Petrol."));
        builtInList.add(new Abbreviation("Archives of Psychiatric Nursing", "Arch. Psychiatr. Nurs."));
        builtInList.add(new Abbreviation("Currents in Modern Biology", "Curr. Mod. Biol."));
        builtInList.add(new Abbreviation("Journal of Microwave Power and Electromagnetic Energy", "J. Microwave Power Electromagn. Energy"));
        builtInList.add(new Abbreviation("Current Pharmaceutical Biotechnology", "Current Pharm. Biotechnol."));
        builtInList.add(new Abbreviation("Immunodeficiency Reviews", "Immunodefic. Rev."));
        builtInList.add(new Abbreviation("Polar Geography", "Polar Geogr."));
        builtInList.add(new Abbreviation("New York Journal of Dentistry", "N. Y. J. Dent."));
        builtInList.add(new Abbreviation("Plasmid", "Plasmid"));
        builtInList.add(new Abbreviation("Chemistry - An Asian Journal", "Chem. Asian J."));
        builtInList.add(new Abbreviation("Functional Orthodontist", "Funct. Orthod."));
        builtInList.add(new Abbreviation("WIT Transactions on Engineering Sciences", "WIT Trans. Eng. Sci."));
        builtInList.add(new Abbreviation("Annali della Sanita Pubblica", "Ann. Sanita Pubblica"));
        builtInList.add(new Abbreviation("Actas Espanolas de Psiquiatria", "Actas Esp. Psiquiatr."));
        builtInList.add(new Abbreviation("Journal of the Acoustical Society of America", "J. Acoust. Soc. Am."));
        builtInList.add(new Abbreviation("Academic Nurse", "Acad. Nurse"));
        builtInList.add(new Abbreviation("Ambulatory Pediatrics", "Ambul. Pediatr."));
        builtInList.add(new Abbreviation("Radiography Today", "Radiogr. Today"));
        builtInList.add(new Abbreviation("Journal of Electronics (China)", "J. Electron."));
        builtInList.add(new Abbreviation("International Journal of Neural Systems", "Int. J. Neural Syst."));
        builtInList.add(new Abbreviation("Memoires de l'Academie de Chirurgie", "Mem. Acad. Chir. (Paris)"));
        builtInList.add(new Abbreviation("Psychiatrie, Neurologie und Medizinische Psychologie", "Psychiatr. Neurol. Med. Psychol. (Leipz.)"));
        builtInList.add(new Abbreviation("Surface and Coatings Technology", "Surf. Coat. Technol."));
        builtInList.add(new Abbreviation("Caementum", "Caementum"));
        builtInList.add(new Abbreviation("Contemporary Pharmacy Practice", "Contemp. Pharm. Pract."));
        builtInList.add(new Abbreviation("Acta Biotheoretica", "Acta Biotheor."));
        builtInList.add(new Abbreviation("Lubrication Engineering", "Lubr. Eng."));
        builtInList.add(new Abbreviation("Journal of Visual Communication and Image Representation", "J. Visual Commun. Image Represent."));
        builtInList.add(new Abbreviation("Journal of Cystic Fibrosis", "J. Cyst. Fibros."));
        builtInList.add(new Abbreviation("Stanford Law Review", "Stanford Law Rev."));
        builtInList.add(new Abbreviation("IMA Journal of Mathematical Control and Information", "IMA J. Math. Control Inf."));
        builtInList.add(new Abbreviation("Berichte der Deutschen Pharmazeutischen Gesellschaft", "Ber. Dtsch. Pharm. Ges."));
        builtInList.add(new Abbreviation("Advances in Colloid and Interface Science", "Adv. Colloid Interface Sci."));
        builtInList.add(new Abbreviation("Boletim do Sanatorio Sao Lucas", "Bol. Sanat. Sao Lucas"));
        builtInList.add(new Abbreviation("Journal of Prosthetic Dentistry", "J. Prosthet. Dent."));
        builtInList.add(new Abbreviation("Journal of High Energy Physics", "J. High Energy Phys."));
        builtInList.add(new Abbreviation("Marine Ecology", "Mar. Ecol."));
        builtInList.add(new Abbreviation("Energy Efficiency", "Energy Effic."));
        builtInList.add(new Abbreviation("Acta Veterinaria Scandinavica", "Acta Vet. Scand."));
        builtInList.add(new Abbreviation("Contemporary Anesthesia Practice", "Contemp. Anesth. Pract."));
        builtInList.add(new Abbreviation("Eye, Ear, Nose and Throat Monthly", "Eye. Ear. Nose Throat Mon."));
        builtInList.add(new Abbreviation("Issledovaniia po Genetike", "Issled. Genet."));
        builtInList.add(new Abbreviation("Sozial- und Praventivmedizin", "Soz. Praventivmed."));
        builtInList.add(new Abbreviation("Chemical Vapor Deposition", "Chem. Vap. Deposition"));
        builtInList.add(new Abbreviation("Archiv fur Kinderheilkunde", "Arch. Kinderheilkd."));
        builtInList.add(new Abbreviation("Metals and Materials International", "Met. Mater. Int."));
        builtInList.add(new Abbreviation("Tidsskriftet Sykepleien", "Tidsskr. Sykepl."));
        builtInList.add(new Abbreviation("Journal of Integrated Design and Process Science", "J. Integr. Des. Process Sci."));
        builtInList.add(new Abbreviation("Mathematical Modelling: Theory and Applications", "Math. Modell. Theory Appl."));
        builtInList.add(new Abbreviation("Annales de Microbiologie", "Ann. Microbiol. (Paris)"));
        builtInList.add(new Abbreviation("Clinical Intensive Care", "Clin. Intensive Care"));
        builtInList.add(new Abbreviation("Fen Zi Xi Bao Sheng Wu Xue Bao (Journal of Molecular Cell Biology)", "Fen Zi Xi Bao Sheng Wu Xue Bao"));
        builtInList.add(new Abbreviation("Annalen der Physik", "Ann. Phys."));
        builtInList.add(new Abbreviation("Placenta. Supplement", "Placenta. Suppl."));
        builtInList.add(new Abbreviation("Revista de la Sociedad Peruana de Endocrinologia", "Rev. Soc. Peru. Endocrinol."));
        builtInList.add(new Abbreviation("Journal of Thoracic and Cardiovascular Surgery", "J. Thorac. Cardiovasc. Surg."));
        builtInList.add(new Abbreviation("Integrative and Comparative Biology", "Integr. Comp. Biol."));
        builtInList.add(new Abbreviation("Inflammatory Bowel Diseases", "Inflamm. Bowel Dis."));
        builtInList.add(new Abbreviation("Journal of State Government", "J. State Gov."));
        builtInList.add(new Abbreviation("ASTRA Proceedings", "ASTRA Proc."));
        builtInList.add(new Abbreviation("Footwear Science", "Footwear Sci."));
        builtInList.add(new Abbreviation("Godisen Zbornik na Medicinskiot Fakultet vo Skopje", "God. Zb. Med. Fak. Skopje"));
        builtInList.add(new Abbreviation("Environmental and Experimental Botany", "Environ. Exp. Bot."));
        builtInList.add(new Abbreviation("Revue Roumaine d'Inframicrobiologie", "Rev. Roum. Inframicrobiol."));
        builtInList.add(new Abbreviation("Journal of Leukocyte Biology. Supplement", "J. Leukoc. Biol. Suppl."));
        builtInList.add(new Abbreviation("Dental Dialogue", "Dent. Dialogue"));
        builtInList.add(new Abbreviation("Monthly Notices of the Royal Astronomical Society Letters", "Mon. Not. R. Astron. Soc. Lett."));
        builtInList.add(new Abbreviation("Swedish Dental Journal", "Swed. Dent. J."));
        builtInList.add(new Abbreviation("Lyon Chirurgical", "Lyon Chir."));
        builtInList.add(new Abbreviation("Journal of the Electrochemical Society of India", "J. Electrochem. Soc. India"));
        builtInList.add(new Abbreviation("Wiadomosci Lekarskie", "Wiad. Lek."));
        builtInList.add(new Abbreviation("Regional Immunology", "Reg. Immunol."));
        builtInList.add(new Abbreviation("Fetal and Pediatric Pathology", "Fetal Pediatr. Pathol."));
        builtInList.add(new Abbreviation("Maejo International Journal of Science and Technology", "Maejo Int. J. Sci. Technol."));
        builtInList.add(new Abbreviation("Systematic Zoology", "Syst. Zool."));
        builtInList.add(new Abbreviation("Infection Control", "Infect. Control"));
        builtInList.add(new Abbreviation("International Journal of Humanoid Robotics", "Int. J. Humanoid Rob."));
        builtInList.add(new Abbreviation("Kokuritsu Iyakuhin Shokuhin Eisei Kenkyusho Hokoku (Bulletin of National Institute of Health Sciences)", "Kokuritsu Iyakuhin Shokuhin Eisei Kenkyusho Hokoku"));
        builtInList.add(new Abbreviation("Geomagnetism and Aeronomy", "Geomag. Aeron."));
        builtInList.add(new Abbreviation("Comparative Biochemistry and Physiology. Toxicology and Pharmacology", "Comp. Biochem. Physiol. C Toxicol. Pharmacol."));
        builtInList.add(new Abbreviation("Expert Opinion on Drug Metabolism & Toxicology", "Expert Opin. Drug Metab. Toxicol."));
        builtInList.add(new Abbreviation("Journal of Geophysics", "J. Geophys."));
        builtInList.add(new Abbreviation("Computational Intelligence", "Comput. Intell."));
        builtInList.add(new Abbreviation("International Journal of Sport Nutrition", "Int. J. Sport Nutr."));
        builtInList.add(new Abbreviation("European Journal of Echocardiography", "Eur. J. Echocardiogr."));
        builtInList.add(new Abbreviation("Russian Physics Journal", "Russ. Phys. J."));
        builtInList.add(new Abbreviation("Harefuah", "Harefuah"));
        builtInList.add(new Abbreviation("Monographs in Developmental Biology", "Monogr. Dev. Biol."));
        builtInList.add(new Abbreviation("Archivio Italiano di Urologia, Nefrologia, Andrologia", "Arch. Ital. Urol. Nefrol. Androl."));
        builtInList.add(new Abbreviation("Biologie Medicale", "Biol. Med. (Paris)"));
        builtInList.add(new Abbreviation("Freie Zahnarzt", "Freie Zahnarzt"));
        builtInList.add(new Abbreviation("MSDA Journal", "MSDA J."));
        builtInList.add(new Abbreviation("Transactions, American Society for Artificial Internal Organs", "Trans. Am. Soc. Artif. Intern. Organs"));
        builtInList.add(new Abbreviation("Rational Drug Therapy", "Ration. Drug Ther."));
        builtInList.add(new Abbreviation("Revue de Medecine Psychosomatique et de Psychologie Medicale", "Rev. Med. Psychosom. Psychol. Med."));
        builtInList.add(new Abbreviation("Pacific Medicine and Surgery", "Pac. Med. Surg."));
        builtInList.add(new Abbreviation("ZFA; Zeitschrift fur Alternsforschung", "ZFA"));
        builtInList.add(new Abbreviation("Nebraska Nurse", "Nebr. Nurse"));
        builtInList.add(new Abbreviation("Journal of Biomimetics Biomaterials and Tissue Engineering", "J. Biomimetics Biomater. Tissue Eng."));
        builtInList.add(new Abbreviation("International Journal of Chemistry", "Int. J. Chem."));
        builtInList.add(new Abbreviation("Columbia Law Review", "Columbia Law Rev."));
        builtInList.add(new Abbreviation("Advances in Physics", "Adv. Phys."));
        builtInList.add(new Abbreviation("Journal of Biomedial Materials ResearchPart A", "J. Biomed. Mater. Res. Part A"));
        builtInList.add(new Abbreviation("Peptides (New York, NY, United States)", "Peptides (N. Y., NY, U. S.)"));
        builtInList.add(new Abbreviation("Annals of Nutrition and Metabolism", "Ann. Nutr. Metab."));
        builtInList.add(new Abbreviation("Health Service Journal", "Health Serv. J."));
        builtInList.add(new Abbreviation("Human Antibodies and Hybridomas", "Hum. Antibodies Hybridomas"));
        builtInList.add(new Abbreviation("Nursingconnections", "Nursingconnections"));
        builtInList.add(new Abbreviation("New York Times", "N.Y. Times"));
        builtInList.add(new Abbreviation("Voprosy Pitaniia", "Vopr. Pitan."));
        builtInList.add(new Abbreviation("Training and Development Journal", "Train. Dev. J."));
        builtInList.add(new Abbreviation("Statistics in Medicine", "Stat. Med."));
        builtInList.add(new Abbreviation("Journal of Food Science and Technology", "J. Food Sci. Technol."));
        builtInList.add(new Abbreviation("Mendeleev Communications", "Mendeleev Commun."));
        builtInList.add(new Abbreviation("Bulletin of Engineering Geology and the Environment", "Bull. Eng. Geol. Environ."));
        builtInList.add(new Abbreviation("Biochimica et Biophysica Acta, Reviews on Biomembranes", "Biochim. Biophys. Acta, Rev. Biomembr."));
        builtInList.add(new Abbreviation("International Journal for Numerical and Analytical Methods in Geomechanics", "Int. J. Numer. Anal. Methods Geomech."));
        builtInList.add(new Abbreviation("Journal of Periodontal Research", "J. Periodontal Res."));
        builtInList.add(new Abbreviation("Circulation Journal", "Circ. J."));
        builtInList.add(new Abbreviation("Endocrine Research", "Endocr. Res."));
        builtInList.add(new Abbreviation("HMO Practice", "HMO Pract."));
        builtInList.add(new Abbreviation("Journal of Rural Health", "J. Rural Health"));
        builtInList.add(new Abbreviation("Diffusion and Defect Data--Solid State Data, Pt. A: Defect and Diffusion Forum", "Diffus. Defect Data, Pt. A"));
        builtInList.add(new Abbreviation("Zeitschrift fur Angewandte Photographie in Wissenschaft und Technik", "Z. Angew. Photogr. Wiss. Tech."));
        builtInList.add(new Abbreviation("Physics of Fluids A", "Phys. Fluids A"));
        builtInList.add(new Abbreviation("Physics of Fluids B", "Phys. Fluids B"));
        builtInList.add(new Abbreviation("Rivista dei Combustibili e dell'Industia Chimica", "Riv. Combust. Ind. Chim."));
        builtInList.add(new Abbreviation("Environmental Quality Management", "Environ. Qual. Manage."));
        builtInList.add(new Abbreviation("Schweizerische Zeitschrift fur Sportmedizin", "Schweiz. Z. Sportmed."));
        builtInList.add(new Abbreviation("Forum on Medicine", "Forum Med."));
        builtInList.add(new Abbreviation("Odonto-Stomatologie Tropicale", "Odontostomatol. Trop."));
        builtInList.add(new Abbreviation("Journal of the American Academy of Gold Foil Operators", "J. Am. Acad. Gold Foil Oper."));
        builtInList.add(new Abbreviation("Nature Reviews Neuroscience", "Nat. Rev. Neurosci."));
        builtInList.add(new Abbreviation("Zhongguo Xiu Fu Chong Jian Wai Ke Za Zhi (Chinese Journal of Reparative and Reconstructive Surgery)", "Zhongguo Xiu Fu Chong Jian Wai Ke Za Zhi"));
        builtInList.add(new Abbreviation("Foundations of Chemistry", "Found. Chem."));
        builtInList.add(new Abbreviation("Texas Hospitals", "Tex. Hosp."));
        builtInList.add(new Abbreviation("Microbial and Comparative Genomics", "Microb. Comp. Genomics"));
        builtInList.add(new Abbreviation("Biofuels, Bioproducts and Biorefining", "Biofuels, Bioprod. Biorefin."));
        builtInList.add(new Abbreviation("Medycyna Wieku Rozwojowego", "Med. Wieku Rozwoj."));
        builtInList.add(new Abbreviation("Terrestrial Magnetism", "Terr. Magn."));
        builtInList.add(new Abbreviation("Journal of the Indian Dental Association", "J. Indian Dent. Assoc."));
        builtInList.add(new Abbreviation("GMDA Bulletin", "GMDA Bull."));
        builtInList.add(new Abbreviation("Journal of Climatology", "J. Climatol."));
        builtInList.add(new Abbreviation("Science of the Total Environment", "Sci. Total Environ."));
        builtInList.add(new Abbreviation("Zhurnal Vysshei Nervnoi Deiatelnosti Imeni I. P. Pavlova", "Zh. Vyssh. Nerv. Deiat. Im. I. P. Pavlova"));
        builtInList.add(new Abbreviation("Annals of Thoracic and Cardiovascular Surgery", "Ann. Thorac. Cardiovasc. Surg."));
        builtInList.add(new Abbreviation("Annual Review of Nuclear Science", "Annu. Rev. Nucl. Sci."));
        builtInList.add(new Abbreviation("Journal of the American Academy of Psychiatry and the Law", "J. Am. Acad. Psychiatry Law"));
        builtInList.add(new Abbreviation("Molecular Immunology", "Mol. Immunol."));
        builtInList.add(new Abbreviation("Journal of the Rhode Island State Dental Society", "J. R. I. State Dent. Soc."));
        builtInList.add(new Abbreviation("Journal of Bone and Mineral Metabolism", "J. Bone Miner. Metab."));
        builtInList.add(new Abbreviation("Clinical Psychology Review", "Clin. Psychol. Rev."));
        builtInList.add(new Abbreviation("Journal of Dental Medicine", "J. Dent. Med."));
        builtInList.add(new Abbreviation("Massachusetts Nurse", "Mass. Nurse"));
        builtInList.add(new Abbreviation("Revista Brasileira de Enfermagem", "Rev. Bras. Enferm."));
        builtInList.add(new Abbreviation("Odontiatriki", "Odontiatriki"));
        builtInList.add(new Abbreviation("Biological Control", "Biol. Control"));
        builtInList.add(new Abbreviation("Chemical Research in Toxicology", "Chem. Res. Toxicol."));
        builtInList.add(new Abbreviation("Alpine Botany", "Alp. Bot."));
        builtInList.add(new Abbreviation("Nature Reviews. Immunology", "Nat. Rev. Immunol."));
        builtInList.add(new Abbreviation("Acta Ginecologica", "Acta Ginecol. (Madr.)"));
        builtInList.add(new Abbreviation("Journal of Asia-Pacific Entomology", "J. Asia-Pac. Entomol."));
        builtInList.add(new Abbreviation("Biomedicine & Pharmacotherapy", "Biomed. Pharmacother."));
        builtInList.add(new Abbreviation("Archiv für Meteorologie, Geophysik und Bioklimatologie", "Arch. Meteor. Geophys. Bioklimatol."));
        builtInList.add(new Abbreviation("Archivio Italiano di Scienze Mediche Tropicali e di Parassitologia", "Arch. Ital. Sci. Med. Trop. Parassitol."));
        builtInList.add(new Abbreviation("American Journal of Hospital Pharmacy", "Am. J. Hosp. Pharm."));
        builtInList.add(new Abbreviation("Cambridge Quarterly of Healthcare Ethics", "Camb. Q. Healthc. Ethics"));
        builtInList.add(new Abbreviation("Zeitschrift fur Analytische Chemie", "Z. Anal. Chem."));
        builtInList.add(new Abbreviation("Psychological Medicine", "Psychol. Med."));
        builtInList.add(new Abbreviation("Seminars in Musculoskeletal Radiology", "Semin. Musculoskelet. Radiol."));
        builtInList.add(new Abbreviation("Clinica Terapeutica", "Clin. Ter."));
        builtInList.add(new Abbreviation("Journal of Geomagnetism and Geoelectricity", "J. Geomagn. Geoelec."));
        builtInList.add(new Abbreviation("Central African Journal of Medicine", "Cent. Afr. J. Med."));
        builtInList.add(new Abbreviation("American Journal of Proctology", "Am. J. Proctol."));
        builtInList.add(new Abbreviation("Curationis", "Curationis"));
        builtInList.add(new Abbreviation("Applied Mathematics and Computation", "Appl. Math. Comput."));
        builtInList.add(new Abbreviation("Zeitschrift fur Wasser- und Abwasserforschung", "Z. Wasser Abwasser-Forsch."));
        builtInList.add(new Abbreviation("NAHAM Management Journal", "NAHAM Manage. J."));
        builtInList.add(new Abbreviation("Berliner Beitraege zur Archaeometrie", "Berl. Beitr. Archaeom."));
        builtInList.add(new Abbreviation("Archiv fur die Gesamte Psychologie", "Arch. Gesamte Psychol."));
        builtInList.add(new Abbreviation("Ark-Light Newsletter", "Ark. Light Newsl."));
        builtInList.add(new Abbreviation("Journal of Radiation Research and Applied Sciences", "J. Radiat. Res. Appl. Sci."));
        builtInList.add(new Abbreviation("Bulletin, American Association of Hospital Dentists", "Bull. Am. Assoc. Hosp. Dent."));
        builtInList.add(new Abbreviation("Journal of the Linnean Society of London, Zoology", "J. Linn. Soc. London, Zool."));
        builtInList.add(new Abbreviation("Progress in Experimental Personality and Psychopathology Research", "Prog. Exp. Pers. Psychopathol. Res."));
        builtInList.add(new Abbreviation("Chemosensory Perception", "Chemosens. Percept."));
        builtInList.add(new Abbreviation("Sheng Li Xue Bao (Acta Physiologica Sinica)", "Sheng Li Xue Bao"));
        builtInList.add(new Abbreviation("Zdravookhranenie Rossiiskoi Federatsii", "Zdravookhr. Ross. Fed."));
        builtInList.add(new Abbreviation("Chinese Medical Sciences Journal", "Chin. Med. Sci. J."));
        builtInList.add(new Abbreviation("Fortschritte der Mineralogie", "Fortschr. Mineral."));
        builtInList.add(new Abbreviation("Cancer Cell", "Cancer Cell"));
        builtInList.add(new Abbreviation("Physics of Fluids", "Phys. Fluids"));
        builtInList.add(new Abbreviation("Biomacromolecules", "Biomacromolecules"));
        builtInList.add(new Abbreviation("JPO: Journal of Practical Orthodontics", "JPO J. Pract. Orthod."));
        builtInList.add(new Abbreviation("Acta Clinica Odontologica", "Acta Clin. Odontol."));
        builtInList.add(new Abbreviation("Schriften des Vereines zur Verbreitung Naturwissenschaftlicher Kenntnisse in Wien", "Schr. Naturwissen. Verbr. Naturwissen. Kennt. Wien"));
        builtInList.add(new Abbreviation("International Journal of Automation and Computing", "Int. J. Autom. Comput."));
        builtInList.add(new Abbreviation("Acta Physiologica Academiae Scientiarum Hungaricae", "Acta Physiol. Acad. Sci. Hung."));
        builtInList.add(new Abbreviation("Respiration", "Respiration"));
        builtInList.add(new Abbreviation("Journal of Refractive Surgery", "J. Refract. Surg."));
        builtInList.add(new Abbreviation("Materials Science & Engineering, C: Biomimetic and Supramolecular Systems", "Mater. Sci. Eng., C"));
        builtInList.add(new Abbreviation("Sudhoffs Archiv; Zeitschrift fur Wissenschaftsgeschichte. Beihefte", "Sudhoffs Arch. Z. Wissenschaftsgesch. Beih."));
        builtInList.add(new Abbreviation("Ligament", "Ligament"));
        builtInList.add(new Abbreviation("Pathology, Research and Practice", "Pathol. Res. Pract."));
        builtInList.add(new Abbreviation("Bulletin of the Medical Library Association", "Bull. Med. Libr. Assoc."));
        builtInList.add(new Abbreviation("Mechanics of Solids", "Mech. Solids"));
        builtInList.add(new Abbreviation("Annual Review of Pharmacology", "Annu. Rev. Pharmacol."));
        builtInList.add(new Abbreviation("Journal of the European Academy of Dermatology and Venereology", "J. Eur. Acad. Dermatol. Venereol."));
        builtInList.add(new Abbreviation("Physical Review Letters", "Phys. Rev. Lett."));
        builtInList.add(new Abbreviation("Norsk Geologisk Tidsskrift", "Nor. Geol. Tidsskr."));
        builtInList.add(new Abbreviation("Monographs in Allergy", "Monogr. Allergy"));
        builtInList.add(new Abbreviation("International Archives of Occupational and Environmental Health", "Int. Arch. Occup. Environ. Health"));
        builtInList.add(new Abbreviation("Protein Expression and Purification", "Protein Expression Purif."));
        builtInList.add(new Abbreviation("Journal of Structural and Functional Genomics", "J. Struct. Funct. Genomics"));
        builtInList.add(new Abbreviation("Gems & Gemology", "Gems Gemol."));
        builtInList.add(new Abbreviation("Revista del Ateneo Argentino de Odontologia", "Rev. Ateneo Argent. Odontol."));
        builtInList.add(new Abbreviation("Guangpuxue Yu Guangpu Fenxi", "Guangpuxue Yu Guangpu Fenxi"));
        builtInList.add(new Abbreviation("Deutsches Zentralblatt fur Krankenpflege", "Dtsch. Zentralbl. Krankenpfl."));
        builtInList.add(new Abbreviation("Your Oklahoma Dental Association Journal", "Your Okla. Dent. Assoc. J."));
        builtInList.add(new Abbreviation("Gifu Shika Gakkai Zasshi (Journal of Gifu Dental Society)", "Gifu Shika Gakkai Zasshi"));
        builtInList.add(new Abbreviation("Kango Kyoshitsu (Japanese Journal of the Nursing Class)", "Kango Kyoshitsu"));
        builtInList.add(new Abbreviation("Studies in Applied Mathematics", "Stud. Appl. Math."));
        builtInList.add(new Abbreviation("Journal of Nursing Research", "J. Nurs. Res."));
        builtInList.add(new Abbreviation("Acta Allergologica", "Acta Allergol."));
        builtInList.add(new Abbreviation("Dental Press", "Dent. Press"));
        builtInList.add(new Abbreviation("Aquatic Botany", "Aquat. Bot."));
        builtInList.add(new Abbreviation("Hematologic Pathology", "Hematol. Pathol."));
        builtInList.add(new Abbreviation("Legal Medicine Annual", "Leg. Med. Annu."));
        builtInList.add(new Abbreviation("Journal of Health Care Benefits", "J. Health Care Benefits"));
        builtInList.add(new Abbreviation("Burns", "Burns"));
        builtInList.add(new Abbreviation("Journal of Pedodontics", "J. Pedod."));
        builtInList.add(new Abbreviation("Soins. Pathologie Tropicale", "Soins. Pathol. Trop."));
        builtInList.add(new Abbreviation("Journal of Pharmacobio-Dynamics", "J. Pharmacobiodyn."));
        builtInList.add(new Abbreviation("Blood Cells", "Blood Cells"));
        builtInList.add(new Abbreviation("Proceedings of the Institution of Electronic and Radio Engineers", "Proc. Inst. Electron. Radio Eng."));
        builtInList.add(new Abbreviation("Journal of Stone Disease", "J. Stone Dis."));
        builtInList.add(new Abbreviation("Current Drug Delivery", "Curr. Drug Deliv."));
        builtInList.add(new Abbreviation("Journal of Chemical Sciences (Bangalore, India)", "J. Chem. Sci. (Bangalore, India)"));
        builtInList.add(new Abbreviation("Journal, Southern California Dental Association", "J. South. Calif. Dent. Assoc."));
        builtInList.add(new Abbreviation("Archives of Pharmacal Research", "Arch. Pharmacal Res."));
        builtInList.add(new Abbreviation("Zhonghua Jie He He Hu Xi Xi Ji Bing Za Zhi (Chinese Journal of Tuberculosis and Respiratory Diseases)", "Zhonghua Jie He He Hu Xi Xi Ji Bing Za Zhi"));
        builtInList.add(new Abbreviation("Journal of Fluids and Structures", "J. Fluids Struct."));
        builtInList.add(new Abbreviation("Medical Record News", "Med. Rec. News"));
        builtInList.add(new Abbreviation("Modern Midwife", "Mod. Midwife"));
        builtInList.add(new Abbreviation("Deutsche Zeitschrift fur Sportmedizin", "Dtsch. Z. Sportmed."));
        builtInList.add(new Abbreviation("International Journal of Manufacturing Technology and Management", "Int. J. Manuf. Technol. Manage."));
        builtInList.add(new Abbreviation("Canadian Journal of Microbiology", "Can. J. Microbiol."));
        builtInList.add(new Abbreviation("Archives Italiennes de Biologie", "Arch. Ital. Biol."));
        builtInList.add(new Abbreviation("Cell Biochemistry and Function", "Cell Biochem. Funct."));
        builtInList.add(new Abbreviation("Journal of Neurosurgery", "J. Neurosurg."));
        builtInList.add(new Abbreviation("Trudy Glavnoi Geofizicheskoi Observatorii", "Tr. Gl. Geofiz. Obs."));
        builtInList.add(new Abbreviation("Chemical Engineering Research and Design", "Chem. Eng. Res. Des."));
        builtInList.add(new Abbreviation("Modelling and Simulation in Materials Science and Engineering", "Modell. Simul. Mater. Sci. Eng."));
        builtInList.add(new Abbreviation("Acta Cytologica", "Acta Cytol."));
        builtInList.add(new Abbreviation("Annals of Clinical and Laboratory Science", "Ann. Clin. Lab. Sci."));
        builtInList.add(new Abbreviation("CRC Critical Reviews in Clinical Laboratory Sciences", "CRC Crit. Rev. Clin. Lab. Sci."));
        builtInList.add(new Abbreviation("Biomaterials, Artificial Cells, and Immobilization Biotechnology", "Biomater. Artif. Cells. Immobilization Biotechnol."));
        builtInList.add(new Abbreviation("American Journal of Economics and Sociology", "Am. J. Econ. Sociol."));
        builtInList.add(new Abbreviation("Journal of Nursing Care Quality", "J. Nurs. Care Qual."));
        builtInList.add(new Abbreviation("Environmental Science & Technology", "Environ. Sci. Technol."));
        builtInList.add(new Abbreviation("Revue de Micropaleontologie", "Rev. Micropaleontol."));
        builtInList.add(new Abbreviation("Aktuelle Gerontologie", "Aktuelle Gerontol."));
        builtInList.add(new Abbreviation("Genesis", "Genesis"));
        builtInList.add(new Abbreviation("Letters in Applied Microbiology", "Lett. Appl. Microbiol."));
        builtInList.add(new Abbreviation("Transactions of the American Institute of Metals", "Trans. Am. Inst. Met."));
        builtInList.add(new Abbreviation("Anatomical Record. Part B, New Anatomist", "Anat. Rec. B. New Anat."));
        builtInList.add(new Abbreviation("Zeitschrift fur Naturforschung C: Journal of Biosciences", "Z. Naturforsch., C: Biosci."));
        builtInList.add(new Abbreviation("Journal of Engineering Thermophysics", "J. Eng. Thermophys."));
        builtInList.add(new Abbreviation("Refractive and Corneal Surgery", "Refract. Corneal Surg."));
        builtInList.add(new Abbreviation("Seminars in Thrombosis and Hemostasis", "Semin. Thromb. Hemost."));
        builtInList.add(new Abbreviation("Journal of Solution Chemistry", "J. Solution Chem."));
        builtInList.add(new Abbreviation("Distributed Systems Engineering", "Distrib. Sys. Eng."));
        builtInList.add(new Abbreviation("Preventing Chronic Disease", "Prev. Chronic. Dis."));
        builtInList.add(new Abbreviation("APMIS", "APMIS"));
        builtInList.add(new Abbreviation("Monaldi Archives for Chest Disease", "Monaldi Arch. Chest Dis."));
        builtInList.add(new Abbreviation("National Underwriter", "Natl. Underwrit. [Life Health]"));
        builtInList.add(new Abbreviation("Voprosy Virusologii", "Vopr. Virusol."));
        builtInList.add(new Abbreviation("Palaeogeography, Palaeoclimatology, Palaeoecology", "Palaeogeogr. Palaeoclimatol. Palaeoecol."));
        builtInList.add(new Abbreviation("Industrial Biotechnology", "Ind. Biotechnol."));
        builtInList.add(new Abbreviation("Proceedings of the Indian National Science Academy", "Proc. Indian Natl. Sci. Acad."));
        builtInList.add(new Abbreviation("ANZ Journal of Surgery", "ANZ J. Surg."));
        builtInList.add(new Abbreviation("Huaxue Tongbao", "Huaxue Tongbao"));
        builtInList.add(new Abbreviation("Nanoscale Research Letters", "Nanoscale Res. Lett."));
        builtInList.add(new Abbreviation("Australian Meteorological Magazine", "Aust. Meteorol. Mag."));
        builtInList.add(new Abbreviation("Bioconjugate Chemistry", "Bioconjugate Chem."));
        builtInList.add(new Abbreviation("Finite Fields and Their Applications", "Finite Fields Appl."));
        builtInList.add(new Abbreviation("International Journal of Structural Stability and Dynamics", "Int. J. Struct. Stab. Dyn."));
        builtInList.add(new Abbreviation("Journal of Food Protection", "J. Food Prot."));
        builtInList.add(new Abbreviation("Journal of Liquid Chromatography & Related Technologies", "J. Liq. Chromatogr. Relat. Technol."));
        builtInList.add(new Abbreviation("International Psychiatry Clinics", "Int. Psychiatry Clin."));
        builtInList.add(new Abbreviation("Hospital Topics", "Hosp. Top."));
        builtInList.add(new Abbreviation("Kobe Daigaku Igakubu Kiyo (Medical Journal of Kobe University)", "Kobe Daigaku Igakubu Kiyo"));
        builtInList.add(new Abbreviation("Physics and Chemistry of Minerals", "Phys. Chem. Miner."));
        builtInList.add(new Abbreviation("Weed Science", "Weed Sci."));
        builtInList.add(new Abbreviation("Sveriges Tandlakarforbund Tidning", "Sver. Tandlakarforb. Tidn."));
        builtInList.add(new Abbreviation("Journal of Legal Medicine", "J. Leg. Med."));
        builtInList.add(new Abbreviation("Annals of Vascular Surgery", "Ann. Vasc. Surg."));
        builtInList.add(new Abbreviation("Perspectives on Addictions Nursing", "Perspect. Addict. Nurs."));
        builtInList.add(new Abbreviation("International Journal of Biomedical Sciences", "Int. J. Biomed. Sci."));
        builtInList.add(new Abbreviation("Adolescence", "Adolescence"));
        builtInList.add(new Abbreviation("Folding and Design", "Fold. Des."));
        builtInList.add(new Abbreviation("RAPRA Review Reports", "Rapra Rev. Rep."));
        builtInList.add(new Abbreviation("Radiologia Diagnostica", "Radiol. Diagn. (Berl.)"));
        builtInList.add(new Abbreviation("Journal of the Egyptian Medical Association", "J. Egypt. Med. Assoc."));
        builtInList.add(new Abbreviation("Biomed Research International", "Biomed Res. Int."));
        builtInList.add(new Abbreviation("Ceskoslovenska Neurologie", "Cesk. Neurol."));
        builtInList.add(new Abbreviation("Electromyography", "Electromyography"));
        builtInList.add(new Abbreviation("Gaofenzi Cailiao Kexue Yu Gongcheng", "Gaofenzi Cailiao Kexue Yu Gongcheng"));
        builtInList.add(new Abbreviation("International Geology Review", "Int. Geol. Rev."));
        builtInList.add(new Abbreviation("Journal of Petroleum Science and Technology", "J. Pet. Sci. Technol."));
        builtInList.add(new Abbreviation("American Journal of Art Therapy", "Am. J. Art Ther."));
        builtInList.add(new Abbreviation("Journal of Non-Equilibrium Thermodynamics", "J. Non-Equilib. Thermodyn."));
        builtInList.add(new Abbreviation("Journal of Endocrinology", "J. Endocrinol."));
        builtInList.add(new Abbreviation("Energy Harvesting Systems", "Energy Harvesting Syst."));
        builtInList.add(new Abbreviation("Prostaglandins, Leukotrienes and Medicine", "Prostaglandins. Leukot. Med."));
        builtInList.add(new Abbreviation("Orthopaedic Review", "Orthop. Rev."));
        builtInList.add(new Abbreviation("Alzheimer Disease and Associated Disorders", "Alzheimer Dis. Assoc. Disord."));
        builtInList.add(new Abbreviation("Pediatric Nursing", "Pediatr. Nurs."));
        builtInList.add(new Abbreviation("British Journal of Medical Hypnotism", "Br. J. Med. Hypn."));
        builtInList.add(new Abbreviation("Current Opinion in Immunology", "Curr. Opin. Immunol."));
        builtInList.add(new Abbreviation("Institutions/Volume Feeding", "Inst. Vol. Feed."));
        builtInList.add(new Abbreviation("Molecular Human Reproduction", "Mol. Hum. Reprod."));
        builtInList.add(new Abbreviation("Nippon Hinyokika Gakkai Zasshi (Japanese Journal of Urology)", "Nippon Hinyokika Gakkai Zasshi"));
        builtInList.add(new Abbreviation("Translational Research", "Transl. Res."));
        builtInList.add(new Abbreviation("Optometry and Vision Science", "Optom. Vis. Sci."));
        builtInList.add(new Abbreviation("Transactions of the International Conference on Oral Surgery", "Trans. Int. Conf. Oral Surg."));
        builtInList.add(new Abbreviation("Essays in Fundamental Immunology", "Essays Fundam. Immunol."));
        builtInList.add(new Abbreviation("Journal of Supramolecular Structure and Cellular Biochemistry. Supplement", "J. Supramol. Struct. Cell. Biochem. Suppl."));
        builtInList.add(new Abbreviation("Izvestiya Vysshikh Uchebnykh Zavedenii, Tsvetnaya Metallurgiya", "Izv. Vyssh. Uchebn. Zaved., Tsvetn. Metall."));
        builtInList.add(new Abbreviation("Environmental and Molecular Mutagenesis", "Environ. Mol. Mutagen."));
        builtInList.add(new Abbreviation("Journal of the Society for Gynecologic Investigation", "J. Soc. Gynecol. Investig."));
        builtInList.add(new Abbreviation("Praktische Metallographie", "Prakt. Metallogr."));
        builtInList.add(new Abbreviation("Anales del Programa Academico de Medicina", "An. Programa Acad. Med. (Lima)"));
        builtInList.add(new Abbreviation("Journal of Applied Meteorology", "J. Appl. Meteorol."));
        builtInList.add(new Abbreviation("ADM", "ADM"));
        builtInList.add(new Abbreviation("Journal of Microwave Power", "J. Microwave Power"));
        builtInList.add(new Abbreviation("Zeitschrift fur Erzbergbau und Metallhuttenwesen", "Z. Erzbergbau MetallhuttenWes."));
        builtInList.add(new Abbreviation("Journal of Medical Laboratory Technology", "J. Med. Lab. Technol."));
        builtInList.add(new Abbreviation("Diagnostic Microbiology and Infectious Disease", "Diagn. Microbiol. Infect. Dis."));
        builtInList.add(new Abbreviation("Immunity", "Immunity"));
        builtInList.add(new Abbreviation("Public Relations Journal", "Public Relat. J."));
        builtInList.add(new Abbreviation("European Journal of Surgical Oncology", "Eur. J. Surg. Oncol."));
        builtInList.add(new Abbreviation("Revue d'Elevage et de Medecine Veterinaire des Pays Tropicaux", "Rev. Elev. Med. Vet. Pays Trop."));
        builtInList.add(new Abbreviation("Journal of Rheumatology", "J. Rheumatol."));
        builtInList.add(new Abbreviation("Information Management", "Inf. Manage."));
        builtInList.add(new Abbreviation("Journal of Photochemistry and Photobiology C: Photochemistry Reviews", "J. Photochem. Photobiol., C"));
        builtInList.add(new Abbreviation("Advances in Tuberculosis Research", "Adv. Tuberc. Res."));
        builtInList.add(new Abbreviation("Yao Xue Xue Bao (Acta Pharmaceutica Sinica)", "Yao Xue Xue Bao"));
        builtInList.add(new Abbreviation("Protein Reviews on the Web", "Protein Rev. Web"));
        builtInList.add(new Abbreviation("Journal of Plant Interactions", "J. Plant Interact."));
        builtInList.add(new Abbreviation("Journal of Solar Energy Engineering", "J. Sol. Energy Eng."));
        builtInList.add(new Abbreviation("American Journal of Clinical Dermatology", "Am. J. Clin. Dermatol."));
        builtInList.add(new Abbreviation("Annales de l Institut Pasteur. Microbiologie", "Ann. Inst. Pasteur. Microbiol."));
        builtInList.add(new Abbreviation("Population Reports. Series A, Oral Contraceptives", "Popul. Rep. A"));
        builtInList.add(new Abbreviation("Acta Endocrinologica", "Acta Endocrinol. (Copenh.)"));
        builtInList.add(new Abbreviation("Journal of the Irish Dental Association", "J. Ir. Dent. Assoc."));
        builtInList.add(new Abbreviation("Actualites Hepato-Gastro-Enterologiques", "Actual. Hepatogastroenterol. (Paris)"));
        builtInList.add(new Abbreviation("Journal of Mammalogy", "J. Mammal."));
        builtInList.add(new Abbreviation("Journal of Biomedical Materials Research. Part A", "J. Biomed. Mater. Res. A"));
        builtInList.add(new Abbreviation("Cardiovascular Engineering", "Cardiovasc. Eng."));
        builtInList.add(new Abbreviation("Journal of Craniomandibular Disorders", "J. Craniomandib. Disord."));
        builtInList.add(new Abbreviation("Cytometry. Part B, Clinical Cytometry", "Cytometry B Clin. Cytom."));
        builtInList.add(new Abbreviation("Disease Markers", "Dis. Markers"));
        builtInList.add(new Abbreviation("In Practice", "In Pract."));
        builtInList.add(new Abbreviation("Personnel Administrator", "Pers. Adm."));
        builtInList.add(new Abbreviation("Schweizerische Laboratoriums Zeitschrift", "Schweiz. Lab. Z."));
        builtInList.add(new Abbreviation("International Journal of Molecular Medicine", "Int. J. Mol. Med."));
        builtInList.add(new Abbreviation("Investigative Ophthalmology and Visual Science", "Invest. Ophthalmol. Vis. Sci."));
        builtInList.add(new Abbreviation("International Journal of Mining, Reclamation and Environment", "Int. J. Min. Reclam. Environ."));
        builtInList.add(new Abbreviation("World Meteorological Organization Bulletin", "WMO Bull."));
        builtInList.add(new Abbreviation("Annales Paediatrici (International Review of Pediatrics)", "Ann. Paediatr. Int. Rev. Pediatr."));
        builtInList.add(new Abbreviation("Experimental Medicine and Surgery", "Exp. Med. Surg."));
        builtInList.add(new Abbreviation("International Journal of Developmental Biology", "Int. J. Dev. Biol."));
        builtInList.add(new Abbreviation("Ecological Chemistry and Engineering A", "Ecol. Chem. Eng. A"));
        builtInList.add(new Abbreviation("Revista de Pediatrie, Obstetrica si Ginecologie. Obstetrica si Ginecologie", "Rev. Pediatr. Obstet. Ginecol. Obstet. Ginecol."));
        builtInList.add(new Abbreviation("Journal of Energy Resources Technology", "J. Energy Res. Technol."));
        builtInList.add(new Abbreviation("Executive Housekeeper", "Exec. Housekeeper"));
        builtInList.add(new Abbreviation("Acta Crystallographica Section F: Structural Biology and Crystallization Communications", "Acta Crystallogr., Sect. F: Struct. Biol. Cryst. Commun."));
        builtInList.add(new Abbreviation("Proceedings of the Institution of Civil Engineers: Construction Materials", "Proc. Inst. Civ. Eng. Constr. Mater"));
        builtInList.add(new Abbreviation("Biochimica et Biophysica Acta, Proteins and Proteomics", "Biochim. Biophys. Acta, Proteins Proteomics"));
        builtInList.add(new Abbreviation("Ecological Chemistry and Engineering S", "Ecol. Chem. Eng. S"));
        builtInList.add(new Abbreviation("Water Quality, Exposure and Health", "Water Qual. Exposure Health"));
        builtInList.add(new Abbreviation("Macromolecular Materials and Engineering", "Macromol. Mater. Eng."));
        builtInList.add(new Abbreviation("Springer Series in Materials Science", "Springer Ser. Mater. Sci."));
        builtInList.add(new Abbreviation("International Journal of Gastrointestinal Cancer", "Int. J. Gastrointest. Cancer"));
        builtInList.add(new Abbreviation("Treatments in Respiratory Medicine", "Treat. Respir. Med."));
        builtInList.add(new Abbreviation("Learning and Motivation", "Learn. Motiv."));
        builtInList.add(new Abbreviation("Atmospheric and Oceanic Optics", "Atmos. Oceanic Opt."));
        builtInList.add(new Abbreviation("American Medical News", "Am. Med. News"));
        builtInList.add(new Abbreviation("Nutrition", "Nutrition"));
        builtInList.add(new Abbreviation("British Corrosion Journal", "Br. Corros. J."));
        builtInList.add(new Abbreviation("Contributions to Primatology", "Contrib. Primatol."));
        builtInList.add(new Abbreviation("Diamond", "Diamond"));
        builtInList.add(new Abbreviation("Journal of the Indian Institute of Science", "J. Indian Inst. Sci."));
        builtInList.add(new Abbreviation("Research Report, Health Effects Institute", "Res. Rep. Health Eff. Inst."));
        builtInList.add(new Abbreviation("Management World", "Manage. World"));
        builtInList.add(new Abbreviation("Human Nutrition. Applied Nutrition", "Hum. Nutr. Appl. Nutr."));
        builtInList.add(new Abbreviation("Giornale di Malattie Infettive e Parassitarie", "G. Mal. Infett. Parassit."));
        builtInList.add(new Abbreviation("Journal of Patient Account Management", "J. Patient Acc. Manage."));
        builtInList.add(new Abbreviation("Journal of Public Health", "J. Public Health"));
        builtInList.add(new Abbreviation("Bone and Mineral", "Bone Miner."));
        builtInList.add(new Abbreviation("Revue des Sciences de l'Eau", "Rev. Sci. Eau"));
        builtInList.add(new Abbreviation("Biomedizinische Technik", "Biomed. Tech."));
        builtInList.add(new Abbreviation("Reproduction. Abstract Series", "Reprod. Abstr. Ser."));
        builtInList.add(new Abbreviation("American Christmas Tree Journal", "Am. Christmas Tree J."));
        builtInList.add(new Abbreviation("Journal of Molecular Medicine", "J. Mol. Med."));
        builtInList.add(new Abbreviation("Journal of Voice", "J. Voice"));
        builtInList.add(new Abbreviation("KY Reports", "KY Rep."));
        builtInList.add(new Abbreviation("TMJ Update", "TMJ Update"));
        builtInList.add(new Abbreviation("International Journal of Modern Physics C: Computational Physics and Physical Computation", "Int. J. Mod. Phys. C"));
        builtInList.add(new Abbreviation("Scanning Microscopy", "Scanning Microsc."));
        builtInList.add(new Abbreviation("Journal of the Aeronautical Sciences", "J. Aeronaut. Sci."));
        builtInList.add(new Abbreviation("Forschende Komplementarmedizin und Klassische Naturheilkunde", "Forsch. Komplementarmed. Klass. Naturheilkd."));
        builtInList.add(new Abbreviation("Journal of Travel Medicine", "J. Travel Med."));
        builtInList.add(new Abbreviation("Annals of Telecommunications", "Ann. Telecommun."));
        builtInList.add(new Abbreviation("2D Materials", "2D Mater."));
        builtInList.add(new Abbreviation("Surgery", "Surgery"));
        builtInList.add(new Abbreviation("Human and Experimental Toxicology", "Hum. Exp. Toxicol."));
        builtInList.add(new Abbreviation("Biological Journal of the Linnean Society", "Biol. J. Linn. Soc."));
        builtInList.add(new Abbreviation("Journal of Soils and Sediments", "J. Soils Sediments"));
        builtInList.add(new Abbreviation("Journal of Geophysical Research, Solid Earth", "J. Geophys. Res. Solid Earth"));
        builtInList.add(new Abbreviation("Journal of MMIJ", "J. MMIJ"));
        builtInList.add(new Abbreviation("Lutte Contre le Cancer", "Lutte Cancer"));
        builtInList.add(new Abbreviation("Neurotoxins", "Neurotoxins"));
        builtInList.add(new Abbreviation("Minerals Engineering", "Miner. Eng."));
        builtInList.add(new Abbreviation("Macromolecules", "Macromolecules"));
        builtInList.add(new Abbreviation("Schweizerische Mineralogische und Petrographische Mitteilungen", "Schweiz. Mineral. Petrogr. Mitt."));
        builtInList.add(new Abbreviation("R.I. Medical Journal", "R. I. Med. J."));
        builtInList.add(new Abbreviation("Report, U.S. Navy Experimental Diving Unit", "Rep. US. Navy Exp. Diving Unit"));
        builtInList.add(new Abbreviation("Nature Reviews Endrocrinology", "Nat. Rev. Endocrinol."));
        builtInList.add(new Abbreviation("SA Nursing Journal", "SA Nurs. J."));
        builtInList.add(new Abbreviation("Journal of Plant Physiology", "J. Plant Physiol."));
        builtInList.add(new Abbreviation("Healthcare Facilities Management Series", "Healthc. Facil. Manag. Ser."));
        builtInList.add(new Abbreviation("Preparative Biochemistry", "Prep. Biochem."));
        builtInList.add(new Abbreviation("Integrated Healthcare Report", "Integr. Healthc. Rep."));
        builtInList.add(new Abbreviation("Journal of Arthroplasty", "J. Arthroplasty"));
        builtInList.add(new Abbreviation("Journal of Rehabilitation Research and Development", "J. Rehabil. Res. Dev."));
        builtInList.add(new Abbreviation("Population Reports. Series M, Special Topics", "Popul. Rep. M"));
        builtInList.add(new Abbreviation("Urologiia i Nefrologiia", "Urol. Nefrol. (Mosk.)"));
        builtInList.add(new Abbreviation("Hippocampus", "Hippocampus"));
        builtInList.add(new Abbreviation("Omvardaren", "Omvardaren"));
        builtInList.add(new Abbreviation("Revista de la Facultad de Odontologia, Universidad de Antioquia", "Rev. Fac. Odontol. Univ. Antioq."));
        builtInList.add(new Abbreviation("Medicina del Lavoro", "Med. Lav."));
        builtInList.add(new Abbreviation("JSME International Journal Series A: Mechanics and Material Engineering", "JSME Int J., Ser. A"));
        builtInList.add(new Abbreviation("International Journal of Environmental Studies", "Int. J. Environ. Stud."));
        builtInList.add(new Abbreviation("Additives for Polymers", "Addit. Polym."));
        builtInList.add(new Abbreviation("Thrombosis et Diathesis Haemorrhagica. Supplementum", "Thromb. Diath. Haemorrh. Suppl."));
        builtInList.add(new Abbreviation("Best Practice & Research, Clinical Haematology", "Best Pract. Res. Clin. Haematol."));
        builtInList.add(new Abbreviation("Forschung im Ingenieurwesen", "Forsch. Ingenieurwes."));
        builtInList.add(new Abbreviation("Ultrasonics Sonochemistry", "Ultrason. Sonochem."));
        builtInList.add(new Abbreviation("Acta Rheumatologica Scandinavica", "Acta Rheumatol. Scand."));
        builtInList.add(new Abbreviation("Transactions of the SAEST", "Trans. SAEST"));
        builtInList.add(new Abbreviation("Zbornik Vojnomedicinske Akademije", "Zb. Vojnomed. Akad."));
        builtInList.add(new Abbreviation("Environmental Practice", "Environ. Pract."));
        builtInList.add(new Abbreviation("Enantiomer", "Enantiomer"));
        builtInList.add(new Abbreviation("Radiation Biology", "Radiat. Biol."));
        builtInList.add(new Abbreviation("Oncology Research", "Oncol. Res."));
        builtInList.add(new Abbreviation("Nippon Koku Geka Gakkai Zasshi", "Nippon Koku Geka Gakkai Zasshi"));
        builtInList.add(new Abbreviation("British Journal of Obstetrics and Gynaecology", "Br. J. Obstet. Gynaecol."));
        builtInList.add(new Abbreviation("Minerva Urologica e Nefrologica", "Minerva Urol. Nefrol."));
        builtInList.add(new Abbreviation("Rozprawy Wydzialu Nauk Medycznych", "Rozpr. Wydz. Nauk Med."));
        builtInList.add(new Abbreviation("Biomedical and Environmental Mass Spectrometry", "Biomed. Environ. Mass Spectrom."));
        builtInList.add(new Abbreviation("Journal of Compliance in Health Care", "J. Compliance Health Care"));
        builtInList.add(new Abbreviation("Global Change Biology", "Global Change Biol."));
        builtInList.add(new Abbreviation("Journals of Gerontology. Series B, Psychological Sciences and Social Sciences", "J. Gerontol. B. Psychol. Sci. Soc. Sci."));
        builtInList.add(new Abbreviation("Current Separations and Drug Development", "Curr. Sep Drug Dev."));
        builtInList.add(new Abbreviation("Journal of Nursing Management", "J. Nurs. Manag."));
        builtInList.add(new Abbreviation("Opticheskii Zhurnal", "Opt. Zh."));
        builtInList.add(new Abbreviation("Archives of Interamerican Rheumatology", "Arch. Interam. Rheumatol."));
        builtInList.add(new Abbreviation("Chemisches Zentralblatt", "Chem. Zentralbl."));
        builtInList.add(new Abbreviation("Building Operating Management", "Build. Oper. Manage."));
        builtInList.add(new Abbreviation("Frontiers of Materials Science in China", "Front. Mater. Sci. China"));
        builtInList.add(new Abbreviation("BMC Medical Research Methodology", "BMC Med. Res. Methodol."));
        builtInList.add(new Abbreviation("Reactive Polymers", "React. Polym."));
        builtInList.add(new Abbreviation("Journal of Cellular and Molecular Medicine", "J. Cell. Mol. Med."));
        builtInList.add(new Abbreviation("Journal of Food and Drug Analysis", "J. Food Drug Anal."));
        builtInList.add(new Abbreviation("American Journal of Hospice and Palliative Care", "Am. J. Hosp. Palliat. Care"));
        builtInList.add(new Abbreviation("Statistical Methods in Medical Research", "Stat. Methods Med. Res."));
        builtInList.add(new Abbreviation("Acta Hydrochimica et Hydrobiologica", "Acta Hydrochim. Hydrobiol."));
        builtInList.add(new Abbreviation("Advanced Powder Technology", "Adv. Powder Technol."));
        builtInList.add(new Abbreviation("Cell", "Cell"));
        builtInList.add(new Abbreviation("Israel Journal of Chemistry", "Isr. J. Chem."));
        builtInList.add(new Abbreviation("Occupational Health", "Occup. Health (Lond.)"));
        builtInList.add(new Abbreviation("Journal of Materials Science: Materials in Medicine", "J. Mater. Sci.: Mater. Med."));
        builtInList.add(new Abbreviation("Structure (Cambridge, MA, United States)", "Structure (Cambridge, MA, U. S.)"));
        builtInList.add(new Abbreviation("Science in China, Series D: Earth Sciences", "Sci. China, Ser. D Earth Sci."));
        builtInList.add(new Abbreviation("Surgeon", "Surgeon"));
        builtInList.add(new Abbreviation("IT Professional", "IT Prof."));
        builtInList.add(new Abbreviation("Magnesium and Trace Elements", "Magnes. Trace Elem."));
        builtInList.add(new Abbreviation("Oil and Chemical Pollution", "Oil Chem. Pollut."));
        builtInList.add(new Abbreviation("Plankton and Benthos Research", "Plankton Benthos Res."));
        builtInList.add(new Abbreviation("Clinical Colorectal Cancer", "Clin. Colorectal Cancer"));
        builtInList.add(new Abbreviation("Waves in Random and Complex Media", "Waves Random Complex Medium"));
        builtInList.add(new Abbreviation("Quimica no Brasil", "Quim. Bras."));
        builtInList.add(new Abbreviation("Tijdschrift voor Diergeneeskunde", "Tijdschr. Diergeneeskd."));
        builtInList.add(new Abbreviation("Pharmacogenomics Journal", "Pharmacogenomics J."));
        builtInList.add(new Abbreviation("Journal of Automated Methods & Management in Chemistry", "J. Autom. Methods Manage. Chem."));
        builtInList.add(new Abbreviation("Journal of the American Statistical Association", "J. Am. Stat. Assoc."));
        builtInList.add(new Abbreviation("Phonetica", "Phonetica"));
        builtInList.add(new Abbreviation("Revue Internationale du Trachome et de Pathologie Oculaire Tropicale et Subtropicale", "Rev. Int. Trach. Pathol. Ocul. Trop. Subtrop."));
        builtInList.add(new Abbreviation("SIAM Journal on Discrete Mathematics", "SIAM J. Discrete Math."));
        builtInList.add(new Abbreviation("Spectroscopic Properties of Inorganic and Organometallic Compounds", "Spectrosc. Prop. Inorg. Organomet. Compd."));
        builtInList.add(new Abbreviation("German Medicine", "Ger. Med."));
        builtInList.add(new Abbreviation("Nursing Times", "Nurs. Times"));
        builtInList.add(new Abbreviation("American Heart Hospital Journal", "Am. Heart Hosp. J."));
        builtInList.add(new Abbreviation("American Imago", "Am. Imago"));
        builtInList.add(new Abbreviation("European Journal of Nutrition", "Eur. J. Nutr."));
        builtInList.add(new Abbreviation("International Journal of Mobile Network Design and Innovation", "Int. J. Mobile Network Des. Innov."));
        builtInList.add(new Abbreviation("Surface Topography: Metrology and Properties", "Surf. Topogr. Metrol. Prop."));
        builtInList.add(new Abbreviation("Trends in Ecology & Evolution", "Trends Ecol. Evol."));
        builtInList.add(new Abbreviation("Doklady Biochemistry and Biophysics", "Dokl. Biochem. Biophys."));
        builtInList.add(new Abbreviation("Zahnarztliche Welt, Zahnarztliche Rundschau, ZWR, Vereinigt mit Zahnarztliche Reform", "Zahnarztl. Welt. Zahnarztl. Rundsch. ZWR. Zahnarztl. Reform"));
        builtInList.add(new Abbreviation("Mainlines", "Mainlines"));
        builtInList.add(new Abbreviation("Management and Compliance Series", "Manag. Compliance Ser."));
        builtInList.add(new Abbreviation("Hospital Infection Control", "Hosp. Infect. Control"));
        builtInList.add(new Abbreviation("Family Medicine", "Fam. Med."));
        builtInList.add(new Abbreviation("Gerodontology", "Gerodontology"));
        builtInList.add(new Abbreviation("Comparative Medicine", "Comp. Med."));
        builtInList.add(new Abbreviation("Pituitary", "Pituitary"));
        builtInList.add(new Abbreviation("Hellenis Adelphe", "Hell. Adelphe"));
        builtInList.add(new Abbreviation("Proceedings of the Cambridge Philosophical Society", "Proc. Cambridge Philos. Soc."));
        builtInList.add(new Abbreviation("Lotta Contro la Tubercolosi", "Lotta Contro Tuberc."));
        builtInList.add(new Abbreviation("Molecular and Cellular Biology", "Mol. Cell. Biol."));
        builtInList.add(new Abbreviation("Journal of the American College of Dentists", "J. Am. Coll. Dent."));
        builtInList.add(new Abbreviation("Scandinavian Journal of Plastic and Reconstructive Surgery and Hand Surgery. Supplementum", "Scand. J. Plast. Reconstr. Surg. Hand Surg. Suppl."));
        builtInList.add(new Abbreviation("Journal of Quality Assurance", "J. Qual. Assur."));
        builtInList.add(new Abbreviation("Molecular and Cellular Therapies", "Mol. Cell. Ther."));
        builtInList.add(new Abbreviation("Fresenius Environment bulletin", "Fresenius Environ. Bull."));
        builtInList.add(new Abbreviation("Enfermedades Infecciosas y Microbiologia Clinica", "Enferm. Infecc. Microbiol. Clin."));
        builtInList.add(new Abbreviation("Energy Economics", "Energy Econ."));
        builtInList.add(new Abbreviation("Multibody System Dynamics", "Multibody Sys.Dyn."));
        builtInList.add(new Abbreviation("Capitation Rates and Data", "Capitation Rates Data"));
        builtInList.add(new Abbreviation("CBE Life Sciences Education", "CBE Life Sci. Educ."));
        builtInList.add(new Abbreviation("U.S. Geological Survey Professional Paper", "U.S. Geol. Surv. Prof. Pap."));
        builtInList.add(new Abbreviation("Pharmacology and Therapeutics. Part B, General and Systematic Pharmacology", "Pharmacol. Ther. [B]"));
        builtInList.add(new Abbreviation("Digitale Bilddiagnostik", "Digitale Bilddiagn."));
        builtInList.add(new Abbreviation("International Journal of Polymer Analysis and Characterization", "Int. J. Polym. Anal. Charact."));
        builtInList.add(new Abbreviation("Biotechnology Letters", "Biotechnol. Lett."));
        builtInList.add(new Abbreviation("Applications in Plant Sciences", "Appl. Plant Sci."));
        builtInList.add(new Abbreviation("Dental Student", "Dent. Stud."));
        builtInList.add(new Abbreviation("Journal of Bone and Joint Surgery. American Volume", "J. Bone Joint Surg. Am."));
        builtInList.add(new Abbreviation("MRS Internet Journal of Nitride Semiconductor Research", "MRS Internet J. Nitride Semicond. Res."));
        builtInList.add(new Abbreviation("Community Health Studies", "Community Health Stud."));
        builtInList.add(new Abbreviation("Okajimas Folia Anatomica Japonica", "Okajimas Folia Anat. Jpn."));
        builtInList.add(new Abbreviation("Journal, Canadian Dental Association", "J. Can. Dent. Assoc."));
        builtInList.add(new Abbreviation("Beitrage zur Infusionstherapie", "Beitr. Infusionsther."));
        builtInList.add(new Abbreviation("Biochemistry and Molecular Biology International", "Biochem. Mol. Biol. Int."));
        builtInList.add(new Abbreviation("Developmental Immunology", "Dev. Immunol."));
        builtInList.add(new Abbreviation("Archiv fur Lebensmittelhygiene", "Arch. Lebensmittelhyg."));
        builtInList.add(new Abbreviation("Journal of Parenteral Science and Technology", "J. Parenter. Sci. Technol."));
        builtInList.add(new Abbreviation("Osterreichische Hebammenzeitung", "Osterr. Hebammenztg."));
        builtInList.add(new Abbreviation("Josanpu Zasshi (Japanese Journal for Midwives)", "Josanpu Zasshi"));
        builtInList.add(new Abbreviation("Advances in Chronic Kidney Disease", "Adv. Chronic Kidney Dis."));
        builtInList.add(new Abbreviation("Journal of Hematotherapy and Stem Cell Research", "J. Hematother. Stem Cell Res."));
        builtInList.add(new Abbreviation("Promotion et Education", "Promot. Educ."));
        builtInList.add(new Abbreviation("Chemico-Biological Interactions", "Chem. Biol. Interact."));
        builtInList.add(new Abbreviation("California Medicine", "Calif. Med."));
        builtInList.add(new Abbreviation("Gynecologie Pratique", "Gynecol. Prat."));
        builtInList.add(new Abbreviation("Family and Community Health", "Fam. Community Health"));
        builtInList.add(new Abbreviation("Journal of the Oslo City Hospitals", "J. Oslo City Hosp."));
        builtInList.add(new Abbreviation("High Temperature Material Processes", "High Temp. Mater. Processes (New York)"));
        builtInList.add(new Abbreviation("Journal of Experimental Social Psychology", "J. Exp. Soc. Psychol."));
        builtInList.add(new Abbreviation("Photo-Dermatology", "Photodermatol."));
        builtInList.add(new Abbreviation("Journal of Clinical Pathology", "J. Clin. Pathol."));
        builtInList.add(new Abbreviation("Protein Journal", "Protein J."));
        builtInList.add(new Abbreviation("Folia Morphologica (Poland)", "Folia Morphol. (Warsz.)"));
        builtInList.add(new Abbreviation("Soft Matter", "Soft Matter"));
        builtInList.add(new Abbreviation("Journal of Computing Science and Engineering", "J. Comput. Sci. Eng."));
        builtInList.add(new Abbreviation("Journal of Sound and Vibration", "J. Sound Vib."));
        builtInList.add(new Abbreviation("Japanese Journal of Dermatology: Series B", "Jpn. J. Dermatol. B"));
        builtInList.add(new Abbreviation("Ergebnisse der Physiologie, Biologischen Chemie und Experimentellen Pharmakologie", "Ergeb. Physiol."));
        builtInList.add(new Abbreviation("Military Medicine", "Mil. Med."));
        builtInList.add(new Abbreviation("Ciba Foundation Symposium", "Ciba Found. Symp."));
        builtInList.add(new Abbreviation("International Journal of Language and Communication Disorders", "Int. J. Lang. Commun. Disord."));
        builtInList.add(new Abbreviation("Wiley Interdisciplinary Reviews: Nanomedicine and Nanobiotechnology", "Wiley Interdiscip. Rev. Nanomed. Nanobiotechnol."));
        builtInList.add(new Abbreviation("International Journal of Psycho-Analysis", "Int. J. Psychoanal."));
        builtInList.add(new Abbreviation("National Institutes of Health Consensus Development Conference Consensus Statement", "Natl. Inst. Health Consens. Dev. Conf. Consens. Statement"));
        builtInList.add(new Abbreviation("Disability and Rehabilitation", "Disabil. Rehabil."));
        builtInList.add(new Abbreviation("Dentisuto (Dentist)", "Dentisuto."));
        builtInList.add(new Abbreviation("Geochemical Transactions", "Geochem. Trans."));
        builtInList.add(new Abbreviation("Review of Czechoslovak Medicine", "Rev. Czech. Med."));
        builtInList.add(new Abbreviation("Los Alamos National Laboratory, Preprint Archive, General Relativity and Quantum Cosmology", "Los Alamos Nat. Lab. Prepr. Arch. Gen. Relativ. Quantum Cosmol."));
        builtInList.add(new Abbreviation("Journal of Sedimentary Research", "J. Sediment. Res."));
        builtInList.add(new Abbreviation("Journal of Heart and Lung Transplantation", "J. Heart Lung Transplant."));
        builtInList.add(new Abbreviation("Osterreichische Zeitschrift fur Stomatologie", "Osterr. Z. Stomatol."));
        builtInList.add(new Abbreviation("Endodontic Report", "Endod. Rep."));
        builtInList.add(new Abbreviation("Journal of Biochemical Toxicology", "J. Biochem. Toxicol."));
        builtInList.add(new Abbreviation("Hellenic Journal of Cardiology", "Hellenic J. Cardiol."));
        builtInList.add(new Abbreviation("Progress in Biomaterials", "Prog. Biomater."));
        builtInList.add(new Abbreviation("Drying Technology", "Drying Technol."));
        builtInList.add(new Abbreviation("British Journal of Addiction to Alcohol and Other Drugs", "Br. J. Addict. Alcohol Other Drugs"));
        builtInList.add(new Abbreviation("Zeitschrift für Meteorologie", "Z. Meteor."));
        builtInList.add(new Abbreviation("Depression and Anxiety", "Depress. Anxiety"));
        builtInList.add(new Abbreviation("CRC Critical Reviews in Microbiology", "CRC Crit. Rev. Microbiol."));
        builtInList.add(new Abbreviation("Applied Soil Ecology", "Appl. Soil Ecol."));
        builtInList.add(new Abbreviation("Environmental Pollution (Amsterdam, Netherlands)", "Environ. Pollut. (Amsterdam, Neth.)"));
        builtInList.add(new Abbreviation("Turk Tip Dernegi Dergisi", "Turk Tip Dernegi Derg."));
        builtInList.add(new Abbreviation("Healthcare Information Management", "Healthc. Inf. Manage."));
        builtInList.add(new Abbreviation("Best Practice and Research. Clinical Anaesthesiology", "Best Pract. Res. Clin. Anaesthesiol."));
        builtInList.add(new Abbreviation("Molecular Neurobiology", "Mol. Neurobiol."));
        builtInList.add(new Abbreviation("Shiyo (Journal of the Tokyo Dental Association)", "Shiyo"));
        builtInList.add(new Abbreviation("Quarterly Journal of the Geological Society of London", "Q. J. Geol. Soc. London"));
        builtInList.add(new Abbreviation("Journal of Ultrasound in Medicine", "J. Ultrasound Med."));
        builtInList.add(new Abbreviation("Ukrains'kii Fizichnii Zhurnal", "Ukr. Fiz. Zh."));
        builtInList.add(new Abbreviation("Neues Jahrbuch fur Mineralogie, Geologie und Palaeontologie, Abhandlungen Abteiling B: Geologie, Palaeontologie", "Neues Jahrb. Mineral. Geol. Palaeontol. Abh. Abt. B"));
        builtInList.add(new Abbreviation("Plugger; Iowa Dental Assistants Journal", "Plugger."));
        builtInList.add(new Abbreviation("MLO; Medical Laboratory Observer", "MLO. Med. Lab. Obs."));
        builtInList.add(new Abbreviation("West African Journal of Pharmacology and Drug Research", "West Afr. J. Pharmacol. Drug Res."));
        builtInList.add(new Abbreviation("Giornale Italiano di Cardiologia", "G. Ital. Cardiol."));
        builtInList.add(new Abbreviation("Acta Orthopaedica Scandinavica. Supplementum", "Acta Orthop. Scand. Suppl."));
        builtInList.add(new Abbreviation("Water International", "Water Int."));
        builtInList.add(new Abbreviation("Hospital Technology Series", "Hosp. Technol. Ser."));
        builtInList.add(new Abbreviation("Heart Rhythm", "Heart Rhythm"));
        builtInList.add(new Abbreviation("Plant Signaling & Behavior", "Plant Signaling Behav."));
        builtInList.add(new Abbreviation("Journal American Water Works Association", "J. Am. Water Works Assn."));
        builtInList.add(new Abbreviation("Brain and Cognition", "Brain Cogn."));
        builtInList.add(new Abbreviation("Journal of Sustainable Forestry", "J. Sustainable For."));
        builtInList.add(new Abbreviation("Parasite", "Parasite"));
        builtInList.add(new Abbreviation("International Journal of Molecular Medicine and Advance Sciences", "Int. J. Mol. Med. Adv. Sci."));
        builtInList.add(new Abbreviation("International Journal of Bifurcation and Chaos in Applied Sciences and Engineering", "Int. J. Bifurcation Chaos Appl. Sci. Eng."));
        builtInList.add(new Abbreviation("Therapiewoche", "Therapiewoche"));
        builtInList.add(new Abbreviation("Advances in Biology of Skin", "Adv. Biol. Skin"));
        builtInList.add(new Abbreviation("Chief Information Officer Journal", "Chief Inf. Off. J."));
        builtInList.add(new Abbreviation("Online Journal of Current Clinical Trials", "Online J. Curr. Clin. Trials"));
        builtInList.add(new Abbreviation("Histochemistry", "Histochemistry"));
        builtInList.add(new Abbreviation("Biological Rhythm Research", "Biol. Rhythm Res."));
        builtInList.add(new Abbreviation("Malaysian Journal of Pathology", "Malays. J. Pathol."));
        builtInList.add(new Abbreviation("Acta Belgica. Medica Physica", "Acta Belg. Med. Phys."));
        builtInList.add(new Abbreviation("Archives Belges de Medecine Sociale, Hygiene, Medecine du Travail et Medecine Legale", "Arch. Belg. Med. Soc."));
        builtInList.add(new Abbreviation("Journal of Immunological Methods", "J. Immunol. Methods"));
        builtInList.add(new Abbreviation("Nurse Anesthesia", "Nurse Anesth."));
        builtInList.add(new Abbreviation("Oil, Gas (Hamburg, Germany)", "Oil, Gas (Hamburg, Ger.)"));
        builtInList.add(new Abbreviation("Journal of General Microbiology", "J. Gen. Microbiol."));
        builtInList.add(new Abbreviation("Advances in Polymer Technology", "Adv. Polym. Technol."));
        builtInList.add(new Abbreviation("Bulletin de la Societe de Pathologie Exotique", "Bull. Soc. Pathol. Exot."));
        builtInList.add(new Abbreviation("Public Health Papers", "Public Health Pap."));
        builtInList.add(new Abbreviation("Comments on Astrophysics", "Comments Astrophys."));
        builtInList.add(new Abbreviation("Gigiena i Sanitariia", "Gig. Sanit."));
        builtInList.add(new Abbreviation("Research in Health Economics", "Res. Health Econ."));
        builtInList.add(new Abbreviation("Public Administration Review", "Public Adm. Rev."));
        builtInList.add(new Abbreviation("EMBO Reports", "EMBO Rep."));
        builtInList.add(new Abbreviation("Endeavour", "Endeavour"));
        builtInList.add(new Abbreviation("ACS Macro Letters", "ACS Macro Lett."));
        builtInList.add(new Abbreviation("Critical Reviews in Eukaryotic Gene Expression", "Crit. Rev. Eukaryot. Gene Expr."));
        builtInList.add(new Abbreviation("Journal of Drugs in Dermatology", "J. Drugs Dermatol."));
        builtInList.add(new Abbreviation("Hospital Capital Finance", "Hosp. Cap. Finance"));
        builtInList.add(new Abbreviation("Critical Reviews in Clinical Laboratory Sciences", "Crit. Rev. Clin. Lab. Sci."));
        builtInList.add(new Abbreviation("Journal of Industrial Ecology", "J. Ind. Ecol."));
        builtInList.add(new Abbreviation("Aquatic Conservation: Marine and Freshwater Ecosystems", "Aquat. Conserv. Mar. Freshwater Ecosyst."));
        builtInList.add(new Abbreviation("Asepsis", "Asepsis"));
        builtInList.add(new Abbreviation("Canadian Journal of Pharmaceutical Sciences", "Can. J. Pharm. Sci."));
        builtInList.add(new Abbreviation("International Journal of Oral and Maxillofacial Surgery", "Int. J. Oral Maxillofac. Surg."));
        builtInList.add(new Abbreviation("Developmental Biology", "Dev. Biol."));
        builtInList.add(new Abbreviation("Oncogene Research", "Oncogene Res."));
        builtInList.add(new Abbreviation("Hansenologia Internationalis", "Hansenol. Int."));
        builtInList.add(new Abbreviation("Odontologia", "Odontologia"));
        builtInList.add(new Abbreviation("Acta Zoologica et Pathologica Antverpiensia", "Acta Zool. Pathol. Antverp."));
        builtInList.add(new Abbreviation("Seminars in Adolescent Medicine", "Semin. Adolesc. Med."));
        builtInList.add(new Abbreviation("Journal of Pharmacological Sciences", "J. Pharmacol. Sci."));
        builtInList.add(new Abbreviation("Electroencephalography and Clinical Neurophysiology. Supplement", "Electroencephalogr. Clin. Neurophysiol. Suppl."));
        builtInList.add(new Abbreviation("Journal of Laryngology and Otology. Supplement", "J. Laryngol. Otol. Suppl."));
        builtInList.add(new Abbreviation("Kathmandu University Medical Journal", "Kathmandu Univ. Med. J."));
        builtInList.add(new Abbreviation("Nihon Rinsho Shishubyo Danwakai Kaishi (Journal of the Japanese Society of Periodontists)", "Nihon Rinsho Shishubyo Danwakai Kaishi"));
        builtInList.add(new Abbreviation("Journal of Comparative Effectiveness Research", "J. Comp. Eff. Res."));
        builtInList.add(new Abbreviation("Journal of Nursing Quality Assurance", "J. Nurs. Qual. Assur."));
        builtInList.add(new Abbreviation("Spectrum", "Spectrum"));
        builtInList.add(new Abbreviation("Inorganic Reaction Mechanisms (Philadelphia, PA, United States)", "Inorg. React. Mech. (Philadelphia, PA, U. S.)"));
        builtInList.add(new Abbreviation("Clinical Preventive Dentistry", "Clin. Prev. Dent."));
        builtInList.add(new Abbreviation("American Journal of Neuroprotection and Neuroregeneration", "Am. J. Neuroprot. Neuroregener."));
        builtInList.add(new Abbreviation("Christian Nurse", "Christ. Nurse (Mysore)"));
        builtInList.add(new Abbreviation("Sairaanhoitaja", "Sairaanhoitaja"));
        builtInList.add(new Abbreviation("Journal of Urban Health", "J. Urban Health"));
        builtInList.add(new Abbreviation("Journal of the Medical Association of the State of Alabama", "J. Med. Assoc. State Ala."));
        builtInList.add(new Abbreviation("Applied Surface Science", "Appl. Surf. Sci."));
        builtInList.add(new Abbreviation("Bulletin of the Chemical Society of Japan", "Bull. Chem. Soc. Jpn."));
        builtInList.add(new Abbreviation("Nanomedicine", "Nanomedicine"));
        builtInList.add(new Abbreviation("Journal of Hydrology", "J. Hydrol."));
        builtInList.add(new Abbreviation("International Journal of Clinical and Laboratory Research", "Int. J. Clin. Lab. Res."));
        builtInList.add(new Abbreviation("Noseleutike", "Noseleutike"));
        builtInList.add(new Abbreviation("Pro Re Nata", "Pro Re Nata"));
        builtInList.add(new Abbreviation("Astrobiology", "Astrobiology"));
        builtInList.add(new Abbreviation("International Journal of Hyperthermia", "Int. J. Hyperthermia"));
        builtInList.add(new Abbreviation("Disease-a-Month", "Dis. Mon."));
        builtInList.add(new Abbreviation("Medicinal Chemistry Research", "Med. Chem. Res."));
        builtInList.add(new Abbreviation("Microbiologica", "Microbiologica"));
        builtInList.add(new Abbreviation("Concrete Engineering International", "Concr. Eng. Int."));
        builtInList.add(new Abbreviation("Deutsche Schwesternzeitung", "Dtsch. Schwesternztg."));
        builtInList.add(new Abbreviation("Journal of Traditional Chinese Medicine", "J. Tradit. Chin. Med."));
        builtInList.add(new Abbreviation("Molecular Ecology Resources", "Mol. Ecol. Resour."));
        builtInList.add(new Abbreviation("Policlinico. Sezione Pratica", "Policlinico. [Prat.]"));
        builtInList.add(new Abbreviation("Romanian Journal of Chemistry", "Rom. J. Chem."));
        builtInList.add(new Abbreviation("Minerva Oftalmologica", "Minerva Oftalmol."));
        builtInList.add(new Abbreviation("Aquatic Geochemistry", "Aquat. Geochem."));
        builtInList.add(new Abbreviation("Acta Farmaceutica Bonaerense", "Acta Farm. Bonaerense"));
        builtInList.add(new Abbreviation("Physik Journal", "Phys. J."));
        builtInList.add(new Abbreviation("Animal Reproduction Science", "Anim. Reprod. Sci."));
        builtInList.add(new Abbreviation("Climate Risk Management", "Clim. Risk Manage."));
        builtInList.add(new Abbreviation("Powder Metallurgy and Metal Ceramics", "Powder Metall. Met. Ceram."));
        builtInList.add(new Abbreviation("Journal of the National Association of Seventh-Day Adventist Dentists", "J. Natl. Assoc. Seventh. Day Advent. Dent."));
        builtInList.add(new Abbreviation("UNA Nursing Journal", "UNA Nurs. J."));
        builtInList.add(new Abbreviation("Journal of Tropical Ecology", "J. Trop. Ecology"));
        builtInList.add(new Abbreviation("International Journal of Modern Physics E: Nuclear Physics", "Int. J. Mod. Phys. E"));
        builtInList.add(new Abbreviation("Nutrition in Clinical Care", "Nutr. Clin. Care"));
        builtInList.add(new Abbreviation("Schweizerische Rundschau fur Medizin Praxis", "Schweiz. Rundsch. Med. Prax."));
        builtInList.add(new Abbreviation("Journal of the American Society of Nephrology", "J. Am. Soc. Nephrol."));
        builtInList.add(new Abbreviation("New England Journal of Medicine", "N. Engl. J. Med."));
        builtInList.add(new Abbreviation("BMC Chemical Biology", "BMC Chem. Biol"));
        builtInList.add(new Abbreviation("Genes and Function", "Genes Funct."));
        builtInList.add(new Abbreviation("Journal of the American Water Resources Association", "J. Am. Water Resour. Assoc."));
        builtInList.add(new Abbreviation("Toxicological Sciences", "Toxicol. Sci."));
        builtInList.add(new Abbreviation("Brain Topography", "Brain Topogr."));
        builtInList.add(new Abbreviation("Canadian Pharmaceutical Journal", "Can. Pharm. J."));
        builtInList.add(new Abbreviation("International Journal of Pancreatology", "Int. J. Pancreatol."));
        builtInList.add(new Abbreviation("American Journal of Transplantation", "Am. J. Transplant."));
        builtInList.add(new Abbreviation("Asian Pacific Journal of Cancer Prevention", "Asian Pac. J. Cancer Prev."));
        builtInList.add(new Abbreviation("Quarterly Journal of the Chemical Society", "Q. J. Chem. Soc."));
        builtInList.add(new Abbreviation("Pharmaceutisch Weekblad. Scientific Edition", "Pharm. Weekbl. Sci."));
        builtInList.add(new Abbreviation("Computational Geometry: Theory and Applications", "Comput. Geom. Theory Appl."));
        builtInList.add(new Abbreviation("American Biotechnology Laboratory", "Am. Biotechnol. Lab."));
        builtInList.add(new Abbreviation("Methods", "Methods"));
        builtInList.add(new Abbreviation("Nuclear and Chemical Waste Management", "Nucl. Chem. Waste Manage."));
        builtInList.add(new Abbreviation("Resources, Conservation and Recycling", "Resour. Conserv. Recycl."));
        builtInList.add(new Abbreviation("Revue de Paleobiologie", "Rev. Paleobiol."));
        builtInList.add(new Abbreviation("National Institute of Animal Health Quarterly", "Natl. Inst. Anim. Health Q. (Tokyo)"));
        builtInList.add(new Abbreviation("Giornale Italiano della Tubercolosi e delle Malattie del Torace", "G. Ital. Tuberc. Mal. Torace"));
        builtInList.add(new Abbreviation("Cahiers du Nursing", "Cah. Nurs."));
        builtInList.add(new Abbreviation("Zeitschrift fur Erkrankungen der Atmungsorgane", "Z. Erkr. Atmungsorgane"));
        builtInList.add(new Abbreviation("Revista de Neurologia", "Rev. Neurol."));
        builtInList.add(new Abbreviation("Advanced Cement Based Materials", "Adv. Cem. Based Mater."));
        builtInList.add(new Abbreviation("Protein & Peptide Letters", "Protein Pept. Lett."));
        builtInList.add(new Abbreviation("International Journal of Technology and Human Interaction", "Int. J. Technol. Hum. Interact."));
        builtInList.add(new Abbreviation("Lecture Notes in Physics Monographs", "Lect. Notes Phys. Monogr."));
        builtInList.add(new Abbreviation("European Journal of Pharmacology: Molecular Pharmacology", "Eur. J. Pharmacol. Mol. Pharmacol."));
        builtInList.add(new Abbreviation("International Journal of Medical Robotics and Computer Assisted Surgery", "Int. J. Med. Rob. Comput. Assisted Surg."));
        builtInList.add(new Abbreviation("Journal of Statistical Physics", "J. Stat. Phys."));
        builtInList.add(new Abbreviation("Acta Crystallographica. Section D, Biological Crystallography", "Acta Crystallogr. D Biol. Crystallogr."));
        builtInList.add(new Abbreviation("International Journal of Radiation Applications and Instrumentation. Part E. Nuclear Geophysics", "Int. J. Radiat. Appl. Instrum. Part E"));
        builtInList.add(new Abbreviation("Mitteilungen der Deutschen Pharmazeutischen Gesellschaft und der Pharmazeutischen Gesellschaft der DDR", "Mitt. Dtsch. Pharm. Ges. Pharm. Ges. DDR"));
        builtInList.add(new Abbreviation("Documenta Ophthalmologica", "Doc. Ophthalmol."));
        builtInList.add(new Abbreviation("IARC Monographs on the Evaluation of the Carcinogenic Risk of Chemicals to Humans. Supplement", "IARC Monogr. Eval. Carcinog. Risk Chem. Hum. Suppl."));
        builtInList.add(new Abbreviation("Social Biology", "Soc. Biol."));
        builtInList.add(new Abbreviation("Indian Journal of Pure and Applied Physics", "Indian J. Pure Appl. Phys."));
        builtInList.add(new Abbreviation("Publications of the Astronomical Society of Japan", "Publ. Astron. Soc. Jpn."));
        builtInList.add(new Abbreviation("Solar System Research", "Sol. Syst. Res."));
        builtInList.add(new Abbreviation("FEMS Yeast Research", "FEMS Yeast Res."));
        builtInList.add(new Abbreviation("Monographs of the American Association on Mental Deficiency", "Monogr. Am. Assoc. Ment. Defic."));
        builtInList.add(new Abbreviation("Nippon Kyobu Geka Gakkai Zasshi (Journal of the Japanese Association for Thoracic Surgery)", "Nippon Kyobu Geka Gakkai Zasshi"));
        builtInList.add(new Abbreviation("Progress in Biophysics and Molecular biology", "Prog. Biophys. Mol. Biol."));
    }

    public static List<Abbreviation> getAbbreviations() {
        return builtInList;
    }
}
