package org.jabref.logic.journals;

import java.util.ArrayList;
import java.util.List;

class BuiltInJournalsList {

    public static List<Abbreviation> getAbbreviations() {
        List<Abbreviation> result = new ArrayList<>(942);

        result.add(new Abbreviation("Health Care Financing Review. Annual Supplement","Health Care Financ. Rev. Annu. Suppl."));
        result.add(new Abbreviation("Journal of Neurocytology","J. Neurocytol."));
        result.add(new Abbreviation("Structure and Bonding","Struct. Bond."));
        result.add(new Abbreviation("Death Studies","Death Stud."));
        result.add(new Abbreviation("Experientia. Supplementum","Experientia. Suppl."));
        result.add(new Abbreviation("Food Microbiology","Food Microbiol."));
        result.add(new Abbreviation("Breastfeeding Review","Breastfeed. Rev."));
        result.add(new Abbreviation("Landarzt","Landarzt"));
        result.add(new Abbreviation("McGraw-Hill's Washington Report on Medicine and Health","McGraw Hills Wash. Rep. Med. Health"));
        result.add(new Abbreviation("Bulletin of the New York State Society of Dentistry for Children","Bull. N. Y. State Soc. Dent. Child."));
        result.add(new Abbreviation("Diabetic Medicine","Diabet. Med."));
        result.add(new Abbreviation("Plant Cell","Plant Cell"));
        result.add(new Abbreviation("Journal of Computed Tomography","J. Comput. Tomogr."));
        result.add(new Abbreviation("Accident Analysis and Prevention","Accid. Anal. Prev."));
        result.add(new Abbreviation("Advances in Ophthalmic, Plastic, and Reconstructive Surgery","Adv. Ophthalmic. Plast. Reconstr. Surg."));
        result.add(new Abbreviation("Annales Academiae Scientiarum Fennicae. Series A V, Medica","Ann. Acad. Sci. Fenn. A"));
        result.add(new Abbreviation("Midwives","Midwives"));
        result.add(new Abbreviation("Acta Biochimica et Biophysica Sinica","Acta Biochim. Biophys. Sin."));
        result.add(new Abbreviation("Evidence-Based Nursing","Evid. Based Nurs."));
        result.add(new Abbreviation("Geothermal Energy Science","Geotherm. Energy Sci."));
        result.add(new Abbreviation("Kumamoto Igakkai Zasshi (Journal of the Kumamoto Medical Society)","Kumamoto Igakkai Zasshi"));
        result.add(new Abbreviation("Frontiers in Pediatrics","Front. Pediatr."));
        result.add(new Abbreviation("Science in China, Series B: Chemistry","Sci. China, Ser. B: Chem."));
        result.add(new Abbreviation("Gastroenterologisches Journal","Gastroenterol. J."));
        result.add(new Abbreviation("Acta Crystallographica. Section A, Foundations of Crystallography","Acta Crystallogr. A"));
        result.add(new Abbreviation("Annales de Limnologie","Ann. Limnol."));
        result.add(new Abbreviation("ACS Infectious Diseases","ACS Infect. Dis."));
        result.add(new Abbreviation("FAO Food and Nutrition Series","FAO Food Nutr. Ser."));
        result.add(new Abbreviation("Revue Francaise d'Endocrinologie Clinique, Nutrition et Metabolisme","Rev. Fr. Endocrinol. Clin."));
        result.add(new Abbreviation("Medical Group Management Journal","Med. Group Manage. J."));
        result.add(new Abbreviation("Current Opinion in Structural Biology","Curr. Opin. Struct. Biol."));
        result.add(new Abbreviation("Computer Integrated Manufacturing Systems","Comput. Integr. Manuf. Syst."));
        result.add(new Abbreviation("Progress in Photovoltaics: Research and Applications","Prog. Photovoltaics Res. Appl."));
        result.add(new Abbreviation("Journal of Cellular Plastics","J. Cell. Plast."));
        result.add(new Abbreviation("International Journal of Security and Networks","Int. J. Secur. Netw."));
        result.add(new Abbreviation("Igaku to Seibutsugaku (Medicine and Biology)","Igaku To Seibutsugaku"));
        result.add(new Abbreviation("Biochemical Society Symposium","Biochem. Soc. Symp."));
        result.add(new Abbreviation("Management Review","Manage. Rev."));
        result.add(new Abbreviation("Journal of Gerontological Nursing","J. Gerontol. Nurs."));
        result.add(new Abbreviation("Pharmacopsychiatry","Pharmacopsychiatry"));
        result.add(new Abbreviation("Cooperador Dental","Coop. Dent. (B. Aires)"));
        result.add(new Abbreviation("Journal of Invasive Cardiology","J. Invasive Cardiol."));
        result.add(new Abbreviation("Mitteilungsblatt - Chemische Gesellschaft der Deutschen Demokratischen Republik","Mitteilungsbl. - Chem. Ges. D. D. R."));
        result.add(new Abbreviation("Experientia","Experientia"));
        result.add(new Abbreviation("Lattante","Lattante"));
        result.add(new Abbreviation("Polish Medical Sciences and History Bulletin","Pol. Med. Sci. Hist. Bull."));
        result.add(new Abbreviation("Current Opinion in Chemical Biology","Curr. Opin. Chem. Biol."));
        result.add(new Abbreviation("International Journal of Biometeorology","Int. J. Biometeorol."));
        result.add(new Abbreviation("Industrial Health","Ind. Health"));
        result.add(new Abbreviation("Physiological Chemistry and Physics","Physiol. Chem. Phys."));
        result.add(new Abbreviation("Gastroenterologia","Gastroenterologia"));
        result.add(new Abbreviation("Hospital Law Newsletter","Hosp. Law Newsl."));
        result.add(new Abbreviation("Beijing Da Xue Xue Bao. Yi Xue Ban (Journal of Peking University. Health Sciences)","Beijing Da Xue Xue Bao"));
        result.add(new Abbreviation("Journal of Surgical Oncology. Supplement","J. Surg. Oncol. Suppl."));
        result.add(new Abbreviation("Nippon Ishikai Zasshi (Journal of the Japan Medical Association)","Nippon Ishikai Zasshi"));
        result.add(new Abbreviation("Bruns' Beitrage fur Klinische Chirurgie","Bruns Beitr. Klin. Chir."));
        result.add(new Abbreviation("Pakistan Journal of Scientific Research","Pak. J. Sci. Res."));
        result.add(new Abbreviation("Journal of Contemporary Dental Practice","J. Contemp. Dent. Pract."));
        result.add(new Abbreviation("News Bulletin, Indian Dental Association","News Bull. Indian Dent. Assoc."));
        result.add(new Abbreviation("Yi Chuan Xue Bao (Acta Genetica Sinica)","Yi Chuan Xue Bao"));
        result.add(new Abbreviation("Food Chemistry","Food Chem."));
        result.add(new Abbreviation("Trends in Plant Science","Trends Plant Sci."));
        result.add(new Abbreviation("Development (Cambridge, United Kingdom)","Development (Cambridge, U. K.)"));
        result.add(new Abbreviation("Extractive Industries and Society","Extr. Ind. Soc."));
        result.add(new Abbreviation("Environmental Research","Environ. Res."));
        result.add(new Abbreviation("Pediatric Neurology","Pediatr. Neurol."));
        result.add(new Abbreviation("Endodoncia","Endodoncia (Mex.)"));
        result.add(new Abbreviation("International Journal of Applied Science and Technology","Int. J. Appl. Sci. Technol."));
        result.add(new Abbreviation("Rivista di Storia della Medicina","Riv. Stor. Med."));
        result.add(new Abbreviation("Journal of Drug Targeting","J. Drug Targeting"));
        result.add(new Abbreviation("Bildgebung","Bildgebung"));
        result.add(new Abbreviation("Biomedical Imaging and Intervention Journal","Biomed. Imaging Intervention J."));
        result.add(new Abbreviation("Investor-Owned Hospital Review","Investor. Owned Hosp. Rev."));
        result.add(new Abbreviation("Archives d'Ophtalmologie","Arch. Ophtalmol. (Paris)"));
        result.add(new Abbreviation("Alumni Bulletin, School of Dentistry, Indiana University","Alumni Bull. Sch. Dent. Indiana Univ."));
        result.add(new Abbreviation("Chemie Anlagen und Verfahren","Chem. Anlagen Verfahren"));
        result.add(new Abbreviation("Journal of Arid Environments","J. Arid. Environ."));
        result.add(new Abbreviation("Clinic","Clinic (Paris)"));
        result.add(new Abbreviation("Indian Journal of Industrial and Applied Mathematics","Indian J. Ind. Appl. Math."));
        result.add(new Abbreviation("Food Additives and Contaminants","Food Addit. Contam."));
        result.add(new Abbreviation("Changgeng Yi Xue Za Zhi (Chang Gung Medical Journal)","Changgeng Yi Xue Za Zhi"));
        result.add(new Abbreviation("Journal of Food Lipids","J. Food Lipids"));
        result.add(new Abbreviation("Journal of the Peripheral Nervous System","J. Peripher. Nerv. Syst."));
        result.add(new Abbreviation("Lymphatic Research and Biology","Lymphat. Res. Biol."));
        result.add(new Abbreviation("Journal of Clinical Densitometry","J. Clin. Densitom."));
        result.add(new Abbreviation("Scalpel","Scalpel (Brux.)"));
        result.add(new Abbreviation("British Journal of Psychology","Br. J. Psychol."));
        result.add(new Abbreviation("Critical Reviews in Toxicology","Crit. Rev. Toxicol."));
        result.add(new Abbreviation("Columbus Dental Society Bulletin","Columbus Dent. Soc. Bull."));
        result.add(new Abbreviation("Turk Hijiyen ve Tecrubi Biyoloji Dergisi","Turk Hij. Tecr. Biyol. Derg."));
        result.add(new Abbreviation("Journal of Polymer Science. Part B, Polymer Letters","J. Polym. Sci. [B]"));
        result.add(new Abbreviation("Italian General Review of Dermatology","Ital. Gen. Rev. Dermatol."));
        result.add(new Abbreviation("Neurophysiologie Clinique","Neurophysiol. Clin."));
        result.add(new Abbreviation("Acta Medica Nagasakiensia","Acta Med. Nagasaki."));
        result.add(new Abbreviation("Arquivos Brasileiros de Oftalmologia","Arq. Bras. Oftalmol."));
        result.add(new Abbreviation("Canadian Journal of Biochemistry","Can. J. Biochem."));
        result.add(new Abbreviation("South Dakota Medicine","S. D. Med."));
        result.add(new Abbreviation("Journal of the West Australian Nurses","J. West Aust. Nurses"));
        result.add(new Abbreviation("Journal of Immunology","J. Immunol."));
        result.add(new Abbreviation("Journal of Applied Mechanics","J. Appl. Mech."));
        result.add(new Abbreviation("Gerontology and Geriatrics Education","Gerontol. Geriatr. Educ."));
        result.add(new Abbreviation("Journal of Risk and Insurance","J. Risk Insur."));
        result.add(new Abbreviation("Contemporary Issues in Clinical Biochemistry","Contemp. Issues Clin. Biochem."));
        result.add(new Abbreviation("Operative Dentistry. Supplement","Oper. Dent. Suppl."));
        result.add(new Abbreviation("Proceedings, Annual Meeting of the Medical Section of the American Life Convention","Proc. Annu. Meet. Med. Sect. Am. Life Conv."));
        result.add(new Abbreviation("Journal of Applied Glycoscience","J. Appl. Glycosci."));
        result.add(new Abbreviation("Journal of Biomechanical Engineering","J. Biomech. Eng."));
        result.add(new Abbreviation("Journal de Biologie Buccale","J. Biol. Buccale"));
        result.add(new Abbreviation("Zeitschrift fur Naturforschung B: Journal of Chemical Sciences","Z. Naturforsch., B: Chem. Sci."));
        result.add(new Abbreviation("Clinics in Rheumatic Diseases","Clin. Rheum. Dis."));
        result.add(new Abbreviation("Microporous and Mesoporous Materials","Microporous Mesoporous Mater."));
        result.add(new Abbreviation("Journal of the Brazilian Chemical Society","J. Braz. Chem. Soc."));
        result.add(new Abbreviation("Report, Navy Medical Neuropsychiatric Research Unit","Rep. Nav. Med. Neuropsychiatr. Res. Unit"));
        result.add(new Abbreviation("Journal of Environmental Science and Health. Part C, Environmental Health Sciences","J. Environ. Sci. Health [C]"));
        result.add(new Abbreviation("Special Education","Spec. Educ."));
        result.add(new Abbreviation("Journal of Radioanalytical and Nuclear Chemistry","J. Radioanal. Nucl. Chem."));
        result.add(new Abbreviation("Journal of Quaternary Science","J. Quat. Sci."));
        result.add(new Abbreviation("Journal of the Association for Academic Minority Physicians","J. Assoc. Acad. Minor. Phys."));
        result.add(new Abbreviation("Pediatric Emergency Care","Pediatr. Emerg. Care"));
        result.add(new Abbreviation("International Review of Poultry Science","Int. Rev. Poult. Sci."));
        result.add(new Abbreviation("Radiologia Clinica","Radiol. Clin. (Basel)"));
        result.add(new Abbreviation("Appetite","Appetite"));
        result.add(new Abbreviation("Bulletin on the Rheumatic Diseases","Bull. Rheum. Dis."));
        result.add(new Abbreviation("Journal of Petrology","J. Petrol."));
        result.add(new Abbreviation("Archives of Psychiatric Nursing","Arch. Psychiatr. Nurs."));
        result.add(new Abbreviation("Currents in Modern Biology","Curr. Mod. Biol."));
        result.add(new Abbreviation("Journal of Microwave Power and Electromagnetic Energy","J. Microwave Power Electromagn. Energy"));
        result.add(new Abbreviation("Current Pharmaceutical Biotechnology","Current Pharm. Biotechnol."));
        result.add(new Abbreviation("Immunodeficiency Reviews","Immunodefic. Rev."));
        result.add(new Abbreviation("Polar Geography","Polar Geogr."));
        result.add(new Abbreviation("New York Journal of Dentistry","N. Y. J. Dent."));
        result.add(new Abbreviation("Plasmid","Plasmid"));
        result.add(new Abbreviation("Chemistry - An Asian Journal","Chem. Asian J."));
        result.add(new Abbreviation("Functional Orthodontist","Funct. Orthod."));
        result.add(new Abbreviation("WIT Transactions on Engineering Sciences","WIT Trans. Eng. Sci."));
        result.add(new Abbreviation("Annali della Sanita Pubblica","Ann. Sanita Pubblica"));
        result.add(new Abbreviation("Actas Espanolas de Psiquiatria","Actas Esp. Psiquiatr."));
        result.add(new Abbreviation("Journal of the Acoustical Society of America","J. Acoust. Soc. Am."));
        result.add(new Abbreviation("Academic Nurse","Acad. Nurse"));
        result.add(new Abbreviation("Ambulatory Pediatrics","Ambul. Pediatr."));
        result.add(new Abbreviation("Radiography Today","Radiogr. Today"));
        result.add(new Abbreviation("Journal of Electronics (China)","J. Electron."));
        result.add(new Abbreviation("International Journal of Neural Systems","Int. J. Neural Syst."));
        result.add(new Abbreviation("Memoires de l'Academie de Chirurgie","Mem. Acad. Chir. (Paris)"));
        result.add(new Abbreviation("Psychiatrie, Neurologie und Medizinische Psychologie","Psychiatr. Neurol. Med. Psychol. (Leipz.)"));
        result.add(new Abbreviation("Surface and Coatings Technology","Surf. Coat. Technol."));
        result.add(new Abbreviation("Caementum","Caementum"));
        result.add(new Abbreviation("Contemporary Pharmacy Practice","Contemp. Pharm. Pract."));
        result.add(new Abbreviation("Acta Biotheoretica","Acta Biotheor."));
        result.add(new Abbreviation("Lubrication Engineering","Lubr. Eng."));
        result.add(new Abbreviation("Journal of Visual Communication and Image Representation","J. Visual Commun. Image Represent."));
        result.add(new Abbreviation("Journal of Cystic Fibrosis","J. Cyst. Fibros."));
        result.add(new Abbreviation("Stanford Law Review","Stanford Law Rev."));
        result.add(new Abbreviation("IMA Journal of Mathematical Control and Information","IMA J. Math. Control Inf."));
        result.add(new Abbreviation("Berichte der Deutschen Pharmazeutischen Gesellschaft","Ber. Dtsch. Pharm. Ges."));
        result.add(new Abbreviation("Advances in Colloid and Interface Science","Adv. Colloid Interface Sci."));
        result.add(new Abbreviation("Boletim do Sanatorio Sao Lucas","Bol. Sanat. Sao Lucas"));
        result.add(new Abbreviation("Journal of Prosthetic Dentistry","J. Prosthet. Dent."));
        result.add(new Abbreviation("Journal of High Energy Physics","J. High Energy Phys."));
        result.add(new Abbreviation("Marine Ecology","Mar. Ecol."));
        result.add(new Abbreviation("Energy Efficiency","Energy Effic."));
        result.add(new Abbreviation("Acta Veterinaria Scandinavica","Acta Vet. Scand."));
        result.add(new Abbreviation("Contemporary Anesthesia Practice","Contemp. Anesth. Pract."));
        result.add(new Abbreviation("Eye, Ear, Nose and Throat Monthly","Eye. Ear. Nose Throat Mon."));
        result.add(new Abbreviation("Issledovaniia po Genetike","Issled. Genet."));
        result.add(new Abbreviation("Sozial- und Praventivmedizin","Soz. Praventivmed."));
        result.add(new Abbreviation("Chemical Vapor Deposition","Chem. Vap. Deposition"));
        result.add(new Abbreviation("Archiv fur Kinderheilkunde","Arch. Kinderheilkd."));
        result.add(new Abbreviation("Metals and Materials International","Met. Mater. Int."));
        result.add(new Abbreviation("Tidsskriftet Sykepleien","Tidsskr. Sykepl."));
        result.add(new Abbreviation("Journal of Integrated Design and Process Science","J. Integr. Des. Process Sci."));
        result.add(new Abbreviation("Mathematical Modelling: Theory and Applications","Math. Modell. Theory Appl."));
        result.add(new Abbreviation("Annales de Microbiologie","Ann. Microbiol. (Paris)"));
        result.add(new Abbreviation("Clinical Intensive Care","Clin. Intensive Care"));
        result.add(new Abbreviation("Fen Zi Xi Bao Sheng Wu Xue Bao (Journal of Molecular Cell Biology)","Fen Zi Xi Bao Sheng Wu Xue Bao"));
        result.add(new Abbreviation("Annalen der Physik","Ann. Phys."));
        result.add(new Abbreviation("Placenta. Supplement","Placenta. Suppl."));
        result.add(new Abbreviation("Revista de la Sociedad Peruana de Endocrinologia","Rev. Soc. Peru. Endocrinol."));
        result.add(new Abbreviation("Journal of Thoracic and Cardiovascular Surgery","J. Thorac. Cardiovasc. Surg."));
        result.add(new Abbreviation("Integrative and Comparative Biology","Integr. Comp. Biol."));
        result.add(new Abbreviation("Inflammatory Bowel Diseases","Inflamm. Bowel Dis."));
        result.add(new Abbreviation("Journal of State Government","J. State Gov."));
        result.add(new Abbreviation("ASTRA Proceedings","ASTRA Proc."));
        result.add(new Abbreviation("Footwear Science","Footwear Sci."));
        result.add(new Abbreviation("Godisen Zbornik na Medicinskiot Fakultet vo Skopje","God. Zb. Med. Fak. Skopje"));
        result.add(new Abbreviation("Environmental and Experimental Botany","Environ. Exp. Bot."));
        result.add(new Abbreviation("Revue Roumaine d'Inframicrobiologie","Rev. Roum. Inframicrobiol."));
        result.add(new Abbreviation("Journal of Leukocyte Biology. Supplement","J. Leukoc. Biol. Suppl."));
        result.add(new Abbreviation("Dental Dialogue","Dent. Dialogue"));
        result.add(new Abbreviation("Monthly Notices of the Royal Astronomical Society Letters","Mon. Not. R. Astron. Soc. Lett."));
        result.add(new Abbreviation("Swedish Dental Journal","Swed. Dent. J."));
        result.add(new Abbreviation("Lyon Chirurgical","Lyon Chir."));
        result.add(new Abbreviation("Journal of the Electrochemical Society of India","J. Electrochem. Soc. India"));
        result.add(new Abbreviation("Wiadomosci Lekarskie","Wiad. Lek."));
        result.add(new Abbreviation("Regional Immunology","Reg. Immunol."));
        result.add(new Abbreviation("Fetal and Pediatric Pathology","Fetal Pediatr. Pathol."));
        result.add(new Abbreviation("Maejo International Journal of Science and Technology","Maejo Int. J. Sci. Technol."));
        result.add(new Abbreviation("Systematic Zoology","Syst. Zool."));
        result.add(new Abbreviation("Infection Control","Infect. Control"));
        result.add(new Abbreviation("International Journal of Humanoid Robotics","Int. J. Humanoid Rob."));
        result.add(new Abbreviation("Kokuritsu Iyakuhin Shokuhin Eisei Kenkyusho Hokoku (Bulletin of National Institute of Health Sciences)","Kokuritsu Iyakuhin Shokuhin Eisei Kenkyusho Hokoku"));
        result.add(new Abbreviation("Geomagnetism and Aeronomy","Geomag. Aeron."));
        result.add(new Abbreviation("Comparative Biochemistry and Physiology. Toxicology and Pharmacology","Comp. Biochem. Physiol. C Toxicol. Pharmacol."));
        result.add(new Abbreviation("Expert Opinion on Drug Metabolism & Toxicology","Expert Opin. Drug Metab. Toxicol."));
        result.add(new Abbreviation("Journal of Geophysics","J. Geophys."));
        result.add(new Abbreviation("Computational Intelligence","Comput. Intell."));
        result.add(new Abbreviation("International Journal of Sport Nutrition","Int. J. Sport Nutr."));
        result.add(new Abbreviation("European Journal of Echocardiography","Eur. J. Echocardiogr."));
        result.add(new Abbreviation("Russian Physics Journal","Russ. Phys. J."));
        result.add(new Abbreviation("Harefuah","Harefuah"));
        result.add(new Abbreviation("Monographs in Developmental Biology","Monogr. Dev. Biol."));
        result.add(new Abbreviation("Archivio Italiano di Urologia, Nefrologia, Andrologia","Arch. Ital. Urol. Nefrol. Androl."));
        result.add(new Abbreviation("Biologie Medicale","Biol. Med. (Paris)"));
        result.add(new Abbreviation("Freie Zahnarzt","Freie Zahnarzt"));
        result.add(new Abbreviation("MSDA Journal","MSDA J."));
        result.add(new Abbreviation("Transactions, American Society for Artificial Internal Organs","Trans. Am. Soc. Artif. Intern. Organs"));
        result.add(new Abbreviation("Rational Drug Therapy","Ration. Drug Ther."));
        result.add(new Abbreviation("Revue de Medecine Psychosomatique et de Psychologie Medicale","Rev. Med. Psychosom. Psychol. Med."));
        result.add(new Abbreviation("Pacific Medicine and Surgery","Pac. Med. Surg."));
        result.add(new Abbreviation("ZFA; Zeitschrift fur Alternsforschung","ZFA"));
        result.add(new Abbreviation("Nebraska Nurse","Nebr. Nurse"));
        result.add(new Abbreviation("Journal of Biomimetics Biomaterials and Tissue Engineering","J. Biomimetics Biomater. Tissue Eng."));
        result.add(new Abbreviation("International Journal of Chemistry","Int. J. Chem."));
        result.add(new Abbreviation("Columbia Law Review","Columbia Law Rev."));
        result.add(new Abbreviation("Advances in Physics","Adv. Phys."));
        result.add(new Abbreviation("Journal of Biomedial Materials ResearchPart A","J. Biomed. Mater. Res. Part A"));
        result.add(new Abbreviation("Peptides (New York, NY, United States)","Peptides (N. Y., NY, U. S.)"));
        result.add(new Abbreviation("Annals of Nutrition and Metabolism","Ann. Nutr. Metab."));
        result.add(new Abbreviation("Health Service Journal","Health Serv. J."));
        result.add(new Abbreviation("Human Antibodies and Hybridomas","Hum. Antibodies Hybridomas"));
        result.add(new Abbreviation("Nursingconnections","Nursingconnections"));
        result.add(new Abbreviation("New York Times","N.Y. Times"));
        result.add(new Abbreviation("Voprosy Pitaniia","Vopr. Pitan."));
        result.add(new Abbreviation("Training and Development Journal","Train. Dev. J."));
        result.add(new Abbreviation("Statistics in Medicine","Stat. Med."));
        result.add(new Abbreviation("Journal of Food Science and Technology","J. Food Sci. Technol."));
        result.add(new Abbreviation("Mendeleev Communications","Mendeleev Commun."));
        result.add(new Abbreviation("Bulletin of Engineering Geology and the Environment","Bull. Eng. Geol. Environ."));
        result.add(new Abbreviation("Biochimica et Biophysica Acta, Reviews on Biomembranes","Biochim. Biophys. Acta, Rev. Biomembr."));
        result.add(new Abbreviation("International Journal for Numerical and Analytical Methods in Geomechanics","Int. J. Numer. Anal. Methods Geomech."));
        result.add(new Abbreviation("Journal of Periodontal Research","J. Periodontal Res."));
        result.add(new Abbreviation("Circulation Journal","Circ. J."));
        result.add(new Abbreviation("Endocrine Research","Endocr. Res."));
        result.add(new Abbreviation("HMO Practice","HMO Pract."));
        result.add(new Abbreviation("Journal of Rural Health","J. Rural Health"));
        result.add(new Abbreviation("Diffusion and Defect Data--Solid State Data, Pt. A: Defect and Diffusion Forum","Diffus. Defect Data, Pt. A"));
        result.add(new Abbreviation("Zeitschrift fur Angewandte Photographie in Wissenschaft und Technik","Z. Angew. Photogr. Wiss. Tech."));
        result.add(new Abbreviation("Physics of Fluids A","Phys. Fluids A"));
        result.add(new Abbreviation("Physics of Fluids B","Phys. Fluids B"));
        result.add(new Abbreviation("Rivista dei Combustibili e dell'Industia Chimica","Riv. Combust. Ind. Chim."));
        result.add(new Abbreviation("Environmental Quality Management","Environ. Qual. Manage."));
        result.add(new Abbreviation("Schweizerische Zeitschrift fur Sportmedizin","Schweiz. Z. Sportmed."));
        result.add(new Abbreviation("Forum on Medicine","Forum Med."));
        result.add(new Abbreviation("Odonto-Stomatologie Tropicale","Odontostomatol. Trop."));
        result.add(new Abbreviation("Journal of the American Academy of Gold Foil Operators","J. Am. Acad. Gold Foil Oper."));
        result.add(new Abbreviation("Nature Reviews Neuroscience","Nat. Rev. Neurosci."));
        result.add(new Abbreviation("Zhongguo Xiu Fu Chong Jian Wai Ke Za Zhi (Chinese Journal of Reparative and Reconstructive Surgery)","Zhongguo Xiu Fu Chong Jian Wai Ke Za Zhi"));
        result.add(new Abbreviation("Foundations of Chemistry","Found. Chem."));
        result.add(new Abbreviation("Texas Hospitals","Tex. Hosp."));
        result.add(new Abbreviation("Microbial and Comparative Genomics","Microb. Comp. Genomics"));
        result.add(new Abbreviation("Biofuels, Bioproducts and Biorefining","Biofuels, Bioprod. Biorefin."));
        result.add(new Abbreviation("Medycyna Wieku Rozwojowego","Med. Wieku Rozwoj."));
        result.add(new Abbreviation("Terrestrial Magnetism","Terr. Magn."));
        result.add(new Abbreviation("Journal of the Indian Dental Association","J. Indian Dent. Assoc."));
        result.add(new Abbreviation("GMDA Bulletin","GMDA Bull."));
        result.add(new Abbreviation("Journal of Climatology","J. Climatol."));
        result.add(new Abbreviation("Science of the Total Environment","Sci. Total Environ."));
        result.add(new Abbreviation("Zhurnal Vysshei Nervnoi Deiatelnosti Imeni I. P. Pavlova","Zh. Vyssh. Nerv. Deiat. Im. I. P. Pavlova"));
        result.add(new Abbreviation("Annals of Thoracic and Cardiovascular Surgery","Ann. Thorac. Cardiovasc. Surg."));
        result.add(new Abbreviation("Annual Review of Nuclear Science","Annu. Rev. Nucl. Sci."));
        result.add(new Abbreviation("Journal of the American Academy of Psychiatry and the Law","J. Am. Acad. Psychiatry Law"));
        result.add(new Abbreviation("Molecular Immunology","Mol. Immunol."));
        result.add(new Abbreviation("Journal of the Rhode Island State Dental Society","J. R. I. State Dent. Soc."));
        result.add(new Abbreviation("Journal of Bone and Mineral Metabolism","J. Bone Miner. Metab."));
        result.add(new Abbreviation("Clinical Psychology Review","Clin. Psychol. Rev."));
        result.add(new Abbreviation("Journal of Dental Medicine","J. Dent. Med."));
        result.add(new Abbreviation("Massachusetts Nurse","Mass. Nurse"));
        result.add(new Abbreviation("Revista Brasileira de Enfermagem","Rev. Bras. Enferm."));
        result.add(new Abbreviation("Odontiatriki","Odontiatriki"));
        result.add(new Abbreviation("Biological Control","Biol. Control"));
        result.add(new Abbreviation("Chemical Research in Toxicology","Chem. Res. Toxicol."));
        result.add(new Abbreviation("Alpine Botany","Alp. Bot."));
        result.add(new Abbreviation("Nature Reviews. Immunology","Nat. Rev. Immunol."));
        result.add(new Abbreviation("Acta Ginecologica","Acta Ginecol. (Madr.)"));
        result.add(new Abbreviation("Journal of Asia-Pacific Entomology","J. Asia-Pac. Entomol."));
        result.add(new Abbreviation("Biomedicine & Pharmacotherapy","Biomed. Pharmacother."));
        result.add(new Abbreviation("Archiv für Meteorologie, Geophysik und Bioklimatologie","Arch. Meteor. Geophys. Bioklimatol."));
        result.add(new Abbreviation("Archivio Italiano di Scienze Mediche Tropicali e di Parassitologia","Arch. Ital. Sci. Med. Trop. Parassitol."));
        result.add(new Abbreviation("American Journal of Hospital Pharmacy","Am. J. Hosp. Pharm."));
        result.add(new Abbreviation("Cambridge Quarterly of Healthcare Ethics","Camb. Q. Healthc. Ethics"));
        result.add(new Abbreviation("Zeitschrift fur Analytische Chemie","Z. Anal. Chem."));
        result.add(new Abbreviation("Psychological Medicine","Psychol. Med."));
        result.add(new Abbreviation("Seminars in Musculoskeletal Radiology","Semin. Musculoskelet. Radiol."));
        result.add(new Abbreviation("Clinica Terapeutica","Clin. Ter."));
        result.add(new Abbreviation("Journal of Geomagnetism and Geoelectricity","J. Geomagn. Geoelec."));
        result.add(new Abbreviation("Central African Journal of Medicine","Cent. Afr. J. Med."));
        result.add(new Abbreviation("American Journal of Proctology","Am. J. Proctol."));
        result.add(new Abbreviation("Curationis","Curationis"));
        result.add(new Abbreviation("Applied Mathematics and Computation","Appl. Math. Comput."));
        result.add(new Abbreviation("Zeitschrift fur Wasser- und Abwasserforschung","Z. Wasser Abwasser-Forsch."));
        result.add(new Abbreviation("NAHAM Management Journal","NAHAM Manage. J."));
        result.add(new Abbreviation("Berliner Beitraege zur Archaeometrie","Berl. Beitr. Archaeom."));
        result.add(new Abbreviation("Archiv fur die Gesamte Psychologie","Arch. Gesamte Psychol."));
        result.add(new Abbreviation("Ark-Light Newsletter","Ark. Light Newsl."));
        result.add(new Abbreviation("Journal of Radiation Research and Applied Sciences","J. Radiat. Res. Appl. Sci."));
        result.add(new Abbreviation("Bulletin, American Association of Hospital Dentists","Bull. Am. Assoc. Hosp. Dent."));
        result.add(new Abbreviation("Journal of the Linnean Society of London, Zoology","J. Linn. Soc. London, Zool."));
        result.add(new Abbreviation("Progress in Experimental Personality and Psychopathology Research","Prog. Exp. Pers. Psychopathol. Res."));
        result.add(new Abbreviation("Chemosensory Perception","Chemosens. Percept."));
        result.add(new Abbreviation("Sheng Li Xue Bao (Acta Physiologica Sinica)","Sheng Li Xue Bao"));
        result.add(new Abbreviation("Zdravookhranenie Rossiiskoi Federatsii","Zdravookhr. Ross. Fed."));
        result.add(new Abbreviation("Chinese Medical Sciences Journal","Chin. Med. Sci. J."));
        result.add(new Abbreviation("Fortschritte der Mineralogie","Fortschr. Mineral."));
        result.add(new Abbreviation("Cancer Cell","Cancer Cell"));
        result.add(new Abbreviation("Physics of Fluids","Phys. Fluids"));
        result.add(new Abbreviation("Biomacromolecules","Biomacromolecules"));
        result.add(new Abbreviation("JPO: Journal of Practical Orthodontics","JPO J. Pract. Orthod."));
        result.add(new Abbreviation("Acta Clinica Odontologica","Acta Clin. Odontol."));
        result.add(new Abbreviation("Schriften des Vereines zur Verbreitung Naturwissenschaftlicher Kenntnisse in Wien","Schr. Naturwissen. Verbr. Naturwissen. Kennt. Wien"));
        result.add(new Abbreviation("International Journal of Automation and Computing","Int. J. Autom. Comput."));
        result.add(new Abbreviation("Acta Physiologica Academiae Scientiarum Hungaricae","Acta Physiol. Acad. Sci. Hung."));
        result.add(new Abbreviation("Respiration","Respiration"));
        result.add(new Abbreviation("Journal of Refractive Surgery","J. Refract. Surg."));
        result.add(new Abbreviation("Materials Science & Engineering, C: Biomimetic and Supramolecular Systems","Mater. Sci. Eng., C"));
        result.add(new Abbreviation("Sudhoffs Archiv; Zeitschrift fur Wissenschaftsgeschichte. Beihefte","Sudhoffs Arch. Z. Wissenschaftsgesch. Beih."));
        result.add(new Abbreviation("Ligament","Ligament"));
        result.add(new Abbreviation("Pathology, Research and Practice","Pathol. Res. Pract."));
        result.add(new Abbreviation("Bulletin of the Medical Library Association","Bull. Med. Libr. Assoc."));
        result.add(new Abbreviation("Mechanics of Solids","Mech. Solids"));
        result.add(new Abbreviation("Annual Review of Pharmacology","Annu. Rev. Pharmacol."));
        result.add(new Abbreviation("Journal of the European Academy of Dermatology and Venereology","J. Eur. Acad. Dermatol. Venereol."));
        result.add(new Abbreviation("Physical Review Letters","Phys. Rev. Lett."));
        result.add(new Abbreviation("Norsk Geologisk Tidsskrift","Nor. Geol. Tidsskr."));
        result.add(new Abbreviation("Monographs in Allergy","Monogr. Allergy"));
        result.add(new Abbreviation("International Archives of Occupational and Environmental Health","Int. Arch. Occup. Environ. Health"));
        result.add(new Abbreviation("Protein Expression and Purification","Protein Expression Purif."));
        result.add(new Abbreviation("Journal of Structural and Functional Genomics","J. Struct. Funct. Genomics"));
        result.add(new Abbreviation("Gems & Gemology","Gems Gemol."));
        result.add(new Abbreviation("Revista del Ateneo Argentino de Odontologia","Rev. Ateneo Argent. Odontol."));
        result.add(new Abbreviation("Guangpuxue Yu Guangpu Fenxi","Guangpuxue Yu Guangpu Fenxi"));
        result.add(new Abbreviation("Deutsches Zentralblatt fur Krankenpflege","Dtsch. Zentralbl. Krankenpfl."));
        result.add(new Abbreviation("Your Oklahoma Dental Association Journal","Your Okla. Dent. Assoc. J."));
        result.add(new Abbreviation("Gifu Shika Gakkai Zasshi (Journal of Gifu Dental Society)","Gifu Shika Gakkai Zasshi"));
        result.add(new Abbreviation("Kango Kyoshitsu (Japanese Journal of the Nursing Class)","Kango Kyoshitsu"));
        result.add(new Abbreviation("Studies in Applied Mathematics","Stud. Appl. Math."));
        result.add(new Abbreviation("Journal of Nursing Research","J. Nurs. Res."));
        result.add(new Abbreviation("Acta Allergologica","Acta Allergol."));
        result.add(new Abbreviation("Dental Press","Dent. Press"));
        result.add(new Abbreviation("Aquatic Botany","Aquat. Bot."));
        result.add(new Abbreviation("Hematologic Pathology","Hematol. Pathol."));
        result.add(new Abbreviation("Legal Medicine Annual","Leg. Med. Annu."));
        result.add(new Abbreviation("Journal of Health Care Benefits","J. Health Care Benefits"));
        result.add(new Abbreviation("Burns","Burns"));
        result.add(new Abbreviation("Journal of Pedodontics","J. Pedod."));
        result.add(new Abbreviation("Soins. Pathologie Tropicale","Soins. Pathol. Trop."));
        result.add(new Abbreviation("Journal of Pharmacobio-Dynamics","J. Pharmacobiodyn."));
        result.add(new Abbreviation("Blood Cells","Blood Cells"));
        result.add(new Abbreviation("Proceedings of the Institution of Electronic and Radio Engineers","Proc. Inst. Electron. Radio Eng."));
        result.add(new Abbreviation("Journal of Stone Disease","J. Stone Dis."));
        result.add(new Abbreviation("Current Drug Delivery","Curr. Drug Deliv."));
        result.add(new Abbreviation("Journal of Chemical Sciences (Bangalore, India)","J. Chem. Sci. (Bangalore, India)"));
        result.add(new Abbreviation("Journal, Southern California Dental Association","J. South. Calif. Dent. Assoc."));
        result.add(new Abbreviation("Archives of Pharmacal Research","Arch. Pharmacal Res."));
        result.add(new Abbreviation("Zhonghua Jie He He Hu Xi Xi Ji Bing Za Zhi (Chinese Journal of Tuberculosis and Respiratory Diseases)","Zhonghua Jie He He Hu Xi Xi Ji Bing Za Zhi"));
        result.add(new Abbreviation("Journal of Fluids and Structures","J. Fluids Struct."));
        result.add(new Abbreviation("Medical Record News","Med. Rec. News"));
        result.add(new Abbreviation("Modern Midwife","Mod. Midwife"));
        result.add(new Abbreviation("Deutsche Zeitschrift fur Sportmedizin","Dtsch. Z. Sportmed."));
        result.add(new Abbreviation("International Journal of Manufacturing Technology and Management","Int. J. Manuf. Technol. Manage."));
        result.add(new Abbreviation("Canadian Journal of Microbiology","Can. J. Microbiol."));
        result.add(new Abbreviation("Archives Italiennes de Biologie","Arch. Ital. Biol."));
        result.add(new Abbreviation("Cell Biochemistry and Function","Cell Biochem. Funct."));
        result.add(new Abbreviation("Journal of Neurosurgery","J. Neurosurg."));
        result.add(new Abbreviation("Trudy Glavnoi Geofizicheskoi Observatorii","Tr. Gl. Geofiz. Obs."));
        result.add(new Abbreviation("Chemical Engineering Research and Design","Chem. Eng. Res. Des."));
        result.add(new Abbreviation("Modelling and Simulation in Materials Science and Engineering","Modell. Simul. Mater. Sci. Eng."));
        result.add(new Abbreviation("Acta Cytologica","Acta Cytol."));
        result.add(new Abbreviation("Annals of Clinical and Laboratory Science","Ann. Clin. Lab. Sci."));
        result.add(new Abbreviation("CRC Critical Reviews in Clinical Laboratory Sciences","CRC Crit. Rev. Clin. Lab. Sci."));
        result.add(new Abbreviation("Biomaterials, Artificial Cells, and Immobilization Biotechnology","Biomater. Artif. Cells. Immobilization Biotechnol."));
        result.add(new Abbreviation("American Journal of Economics and Sociology","Am. J. Econ. Sociol."));
        result.add(new Abbreviation("Journal of Nursing Care Quality","J. Nurs. Care Qual."));
        result.add(new Abbreviation("Environmental Science & Technology","Environ. Sci. Technol."));
        result.add(new Abbreviation("Revue de Micropaleontologie","Rev. Micropaleontol."));
        result.add(new Abbreviation("Aktuelle Gerontologie","Aktuelle Gerontol."));
        result.add(new Abbreviation("Genesis","Genesis"));
        result.add(new Abbreviation("Letters in Applied Microbiology","Lett. Appl. Microbiol."));
        result.add(new Abbreviation("Transactions of the American Institute of Metals","Trans. Am. Inst. Met."));
        result.add(new Abbreviation("Anatomical Record. Part B, New Anatomist","Anat. Rec. B. New Anat."));
        result.add(new Abbreviation("Zeitschrift fur Naturforschung C: Journal of Biosciences","Z. Naturforsch., C: Biosci."));
        result.add(new Abbreviation("Journal of Engineering Thermophysics","J. Eng. Thermophys."));
        result.add(new Abbreviation("Refractive and Corneal Surgery","Refract. Corneal Surg."));
        result.add(new Abbreviation("Seminars in Thrombosis and Hemostasis","Semin. Thromb. Hemost."));
        result.add(new Abbreviation("Journal of Solution Chemistry","J. Solution Chem."));
        result.add(new Abbreviation("Distributed Systems Engineering","Distrib. Sys. Eng."));
        result.add(new Abbreviation("Preventing Chronic Disease","Prev. Chronic. Dis."));
        result.add(new Abbreviation("APMIS","APMIS"));
        result.add(new Abbreviation("Monaldi Archives for Chest Disease","Monaldi Arch. Chest Dis."));
        result.add(new Abbreviation("National Underwriter","Natl. Underwrit. [Life Health]"));
        result.add(new Abbreviation("Voprosy Virusologii","Vopr. Virusol."));
        result.add(new Abbreviation("Palaeogeography, Palaeoclimatology, Palaeoecology","Palaeogeogr. Palaeoclimatol. Palaeoecol."));
        result.add(new Abbreviation("Industrial Biotechnology","Ind. Biotechnol."));
        result.add(new Abbreviation("Proceedings of the Indian National Science Academy","Proc. Indian Natl. Sci. Acad."));
        result.add(new Abbreviation("ANZ Journal of Surgery","ANZ J. Surg."));
        result.add(new Abbreviation("Huaxue Tongbao","Huaxue Tongbao"));
        result.add(new Abbreviation("Nanoscale Research Letters","Nanoscale Res. Lett."));
        result.add(new Abbreviation("Australian Meteorological Magazine","Aust. Meteorol. Mag."));
        result.add(new Abbreviation("Bioconjugate Chemistry","Bioconjugate Chem."));
        result.add(new Abbreviation("Finite Fields and Their Applications","Finite Fields Appl."));
        result.add(new Abbreviation("International Journal of Structural Stability and Dynamics","Int. J. Struct. Stab. Dyn."));
        result.add(new Abbreviation("Journal of Food Protection","J. Food Prot."));
        result.add(new Abbreviation("Journal of Liquid Chromatography & Related Technologies","J. Liq. Chromatogr. Relat. Technol."));
        result.add(new Abbreviation("International Psychiatry Clinics","Int. Psychiatry Clin."));
        result.add(new Abbreviation("Hospital Topics","Hosp. Top."));
        result.add(new Abbreviation("Kobe Daigaku Igakubu Kiyo (Medical Journal of Kobe University)","Kobe Daigaku Igakubu Kiyo"));
        result.add(new Abbreviation("Physics and Chemistry of Minerals","Phys. Chem. Miner."));
        result.add(new Abbreviation("Weed Science","Weed Sci."));
        result.add(new Abbreviation("Sveriges Tandlakarforbund Tidning","Sver. Tandlakarforb. Tidn."));
        result.add(new Abbreviation("Journal of Legal Medicine","J. Leg. Med."));
        result.add(new Abbreviation("Annals of Vascular Surgery","Ann. Vasc. Surg."));
        result.add(new Abbreviation("Perspectives on Addictions Nursing","Perspect. Addict. Nurs."));
        result.add(new Abbreviation("International Journal of Biomedical Sciences","Int. J. Biomed. Sci."));
        result.add(new Abbreviation("Adolescence","Adolescence"));
        result.add(new Abbreviation("Folding and Design","Fold. Des."));
        result.add(new Abbreviation("RAPRA Review Reports","Rapra Rev. Rep."));
        result.add(new Abbreviation("Radiologia Diagnostica","Radiol. Diagn. (Berl.)"));
        result.add(new Abbreviation("Journal of the Egyptian Medical Association","J. Egypt. Med. Assoc."));
        result.add(new Abbreviation("Biomed Research International","Biomed Res. Int."));
        result.add(new Abbreviation("Ceskoslovenska Neurologie","Cesk. Neurol."));
        result.add(new Abbreviation("Electromyography","Electromyography"));
        result.add(new Abbreviation("Gaofenzi Cailiao Kexue Yu Gongcheng","Gaofenzi Cailiao Kexue Yu Gongcheng"));
        result.add(new Abbreviation("International Geology Review","Int. Geol. Rev."));
        result.add(new Abbreviation("Journal of Petroleum Science and Technology","J. Pet. Sci. Technol."));
        result.add(new Abbreviation("American Journal of Art Therapy","Am. J. Art Ther."));
        result.add(new Abbreviation("Journal of Non-Equilibrium Thermodynamics","J. Non-Equilib. Thermodyn."));
        result.add(new Abbreviation("Journal of Endocrinology","J. Endocrinol."));
        result.add(new Abbreviation("Energy Harvesting Systems","Energy Harvesting Syst."));
        result.add(new Abbreviation("Prostaglandins, Leukotrienes and Medicine","Prostaglandins. Leukot. Med."));
        result.add(new Abbreviation("Orthopaedic Review","Orthop. Rev."));
        result.add(new Abbreviation("Alzheimer Disease and Associated Disorders","Alzheimer Dis. Assoc. Disord."));
        result.add(new Abbreviation("Pediatric Nursing","Pediatr. Nurs."));
        result.add(new Abbreviation("British Journal of Medical Hypnotism","Br. J. Med. Hypn."));
        result.add(new Abbreviation("Current Opinion in Immunology","Curr. Opin. Immunol."));
        result.add(new Abbreviation("Institutions/Volume Feeding","Inst. Vol. Feed."));
        result.add(new Abbreviation("Molecular Human Reproduction","Mol. Hum. Reprod."));
        result.add(new Abbreviation("Nippon Hinyokika Gakkai Zasshi (Japanese Journal of Urology)","Nippon Hinyokika Gakkai Zasshi"));
        result.add(new Abbreviation("Translational Research","Transl. Res."));
        result.add(new Abbreviation("Optometry and Vision Science","Optom. Vis. Sci."));
        result.add(new Abbreviation("Transactions of the International Conference on Oral Surgery","Trans. Int. Conf. Oral Surg."));
        result.add(new Abbreviation("Essays in Fundamental Immunology","Essays Fundam. Immunol."));
        result.add(new Abbreviation("Journal of Supramolecular Structure and Cellular Biochemistry. Supplement","J. Supramol. Struct. Cell. Biochem. Suppl."));
        result.add(new Abbreviation("Izvestiya Vysshikh Uchebnykh Zavedenii, Tsvetnaya Metallurgiya","Izv. Vyssh. Uchebn. Zaved., Tsvetn. Metall."));
        result.add(new Abbreviation("Environmental and Molecular Mutagenesis","Environ. Mol. Mutagen."));
        result.add(new Abbreviation("Journal of the Society for Gynecologic Investigation","J. Soc. Gynecol. Investig."));
        result.add(new Abbreviation("Praktische Metallographie","Prakt. Metallogr."));
        result.add(new Abbreviation("Anales del Programa Academico de Medicina","An. Programa Acad. Med. (Lima)"));
        result.add(new Abbreviation("Journal of Applied Meteorology","J. Appl. Meteorol."));
        result.add(new Abbreviation("ADM","ADM"));
        result.add(new Abbreviation("Journal of Microwave Power","J. Microwave Power"));
        result.add(new Abbreviation("Zeitschrift fur Erzbergbau und Metallhuttenwesen","Z. Erzbergbau MetallhuttenWes."));
        result.add(new Abbreviation("Journal of Medical Laboratory Technology","J. Med. Lab. Technol."));
        result.add(new Abbreviation("Diagnostic Microbiology and Infectious Disease","Diagn. Microbiol. Infect. Dis."));
        result.add(new Abbreviation("Immunity","Immunity"));
        result.add(new Abbreviation("Public Relations Journal","Public Relat. J."));
        result.add(new Abbreviation("European Journal of Surgical Oncology","Eur. J. Surg. Oncol."));
        result.add(new Abbreviation("Revue d'Elevage et de Medecine Veterinaire des Pays Tropicaux","Rev. Elev. Med. Vet. Pays Trop."));
        result.add(new Abbreviation("Journal of Rheumatology","J. Rheumatol."));
        result.add(new Abbreviation("Information Management","Inf. Manage."));
        result.add(new Abbreviation("Journal of Photochemistry and Photobiology C: Photochemistry Reviews","J. Photochem. Photobiol., C"));
        result.add(new Abbreviation("Advances in Tuberculosis Research","Adv. Tuberc. Res."));
        result.add(new Abbreviation("Yao Xue Xue Bao (Acta Pharmaceutica Sinica)","Yao Xue Xue Bao"));
        result.add(new Abbreviation("Protein Reviews on the Web","Protein Rev. Web"));
        result.add(new Abbreviation("Journal of Plant Interactions","J. Plant Interact."));
        result.add(new Abbreviation("Journal of Solar Energy Engineering","J. Sol. Energy Eng."));
        result.add(new Abbreviation("American Journal of Clinical Dermatology","Am. J. Clin. Dermatol."));
        result.add(new Abbreviation("Annales de l Institut Pasteur. Microbiologie","Ann. Inst. Pasteur. Microbiol."));
        result.add(new Abbreviation("Population Reports. Series A, Oral Contraceptives","Popul. Rep. A"));
        result.add(new Abbreviation("Acta Endocrinologica","Acta Endocrinol. (Copenh.)"));
        result.add(new Abbreviation("Journal of the Irish Dental Association","J. Ir. Dent. Assoc."));
        result.add(new Abbreviation("Actualites Hepato-Gastro-Enterologiques","Actual. Hepatogastroenterol. (Paris)"));
        result.add(new Abbreviation("Journal of Mammalogy","J. Mammal."));
        result.add(new Abbreviation("Journal of Biomedical Materials Research. Part A","J. Biomed. Mater. Res. A"));
        result.add(new Abbreviation("Cardiovascular Engineering","Cardiovasc. Eng."));
        result.add(new Abbreviation("Journal of Craniomandibular Disorders","J. Craniomandib. Disord."));
        result.add(new Abbreviation("Cytometry. Part B, Clinical Cytometry","Cytometry B Clin. Cytom."));
        result.add(new Abbreviation("Disease Markers","Dis. Markers"));
        result.add(new Abbreviation("In Practice","In Pract."));
        result.add(new Abbreviation("Personnel Administrator","Pers. Adm."));
        result.add(new Abbreviation("Schweizerische Laboratoriums Zeitschrift","Schweiz. Lab. Z."));
        result.add(new Abbreviation("International Journal of Molecular Medicine","Int. J. Mol. Med."));
        result.add(new Abbreviation("Investigative Ophthalmology and Visual Science","Invest. Ophthalmol. Vis. Sci."));
        result.add(new Abbreviation("International Journal of Mining, Reclamation and Environment","Int. J. Min. Reclam. Environ."));
        result.add(new Abbreviation("World Meteorological Organization Bulletin","WMO Bull."));
        result.add(new Abbreviation("Annales Paediatrici (International Review of Pediatrics)","Ann. Paediatr. Int. Rev. Pediatr."));
        result.add(new Abbreviation("Experimental Medicine and Surgery","Exp. Med. Surg."));
        result.add(new Abbreviation("International Journal of Developmental Biology","Int. J. Dev. Biol."));
        result.add(new Abbreviation("Ecological Chemistry and Engineering A","Ecol. Chem. Eng. A"));
        result.add(new Abbreviation("Revista de Pediatrie, Obstetrica si Ginecologie. Obstetrica si Ginecologie","Rev. Pediatr. Obstet. Ginecol. Obstet. Ginecol."));
        result.add(new Abbreviation("Journal of Energy Resources Technology","J. Energy Res. Technol."));
        result.add(new Abbreviation("Executive Housekeeper","Exec. Housekeeper"));
        result.add(new Abbreviation("Acta Crystallographica Section F: Structural Biology and Crystallization Communications","Acta Crystallogr., Sect. F: Struct. Biol. Cryst. Commun."));
        result.add(new Abbreviation("Proceedings of the Institution of Civil Engineers: Construction Materials","Proc. Inst. Civ. Eng. Constr. Mater"));
        result.add(new Abbreviation("Biochimica et Biophysica Acta, Proteins and Proteomics","Biochim. Biophys. Acta, Proteins Proteomics"));
        result.add(new Abbreviation("Ecological Chemistry and Engineering S","Ecol. Chem. Eng. S"));
        result.add(new Abbreviation("Water Quality, Exposure and Health","Water Qual. Exposure Health"));
        result.add(new Abbreviation("Macromolecular Materials and Engineering","Macromol. Mater. Eng."));
        result.add(new Abbreviation("Springer Series in Materials Science","Springer Ser. Mater. Sci."));
        result.add(new Abbreviation("International Journal of Gastrointestinal Cancer","Int. J. Gastrointest. Cancer"));
        result.add(new Abbreviation("Treatments in Respiratory Medicine","Treat. Respir. Med."));
        result.add(new Abbreviation("Learning and Motivation","Learn. Motiv."));
        result.add(new Abbreviation("Atmospheric and Oceanic Optics","Atmos. Oceanic Opt."));
        result.add(new Abbreviation("American Medical News","Am. Med. News"));
        result.add(new Abbreviation("Nutrition","Nutrition"));
        result.add(new Abbreviation("British Corrosion Journal","Br. Corros. J."));
        result.add(new Abbreviation("Contributions to Primatology","Contrib. Primatol."));
        result.add(new Abbreviation("Diamond","Diamond"));
        result.add(new Abbreviation("Journal of the Indian Institute of Science","J. Indian Inst. Sci."));
        result.add(new Abbreviation("Research Report, Health Effects Institute","Res. Rep. Health Eff. Inst."));
        result.add(new Abbreviation("Management World","Manage. World"));
        result.add(new Abbreviation("Human Nutrition. Applied Nutrition","Hum. Nutr. Appl. Nutr."));
        result.add(new Abbreviation("Giornale di Malattie Infettive e Parassitarie","G. Mal. Infett. Parassit."));
        result.add(new Abbreviation("Journal of Patient Account Management","J. Patient Acc. Manage."));
        result.add(new Abbreviation("Journal of Public Health","J. Public Health"));
        result.add(new Abbreviation("Bone and Mineral","Bone Miner."));
        result.add(new Abbreviation("Revue des Sciences de l'Eau","Rev. Sci. Eau"));
        result.add(new Abbreviation("Biomedizinische Technik","Biomed. Tech."));
        result.add(new Abbreviation("Reproduction. Abstract Series","Reprod. Abstr. Ser."));
        result.add(new Abbreviation("American Christmas Tree Journal","Am. Christmas Tree J."));
        result.add(new Abbreviation("Journal of Molecular Medicine","J. Mol. Med."));
        result.add(new Abbreviation("Journal of Voice","J. Voice"));
        result.add(new Abbreviation("KY Reports","KY Rep."));
        result.add(new Abbreviation("TMJ Update","TMJ Update"));
        result.add(new Abbreviation("International Journal of Modern Physics C: Computational Physics and Physical Computation","Int. J. Mod. Phys. C"));
        result.add(new Abbreviation("Scanning Microscopy","Scanning Microsc."));
        result.add(new Abbreviation("Journal of the Aeronautical Sciences","J. Aeronaut. Sci."));
        result.add(new Abbreviation("Forschende Komplementarmedizin und Klassische Naturheilkunde","Forsch. Komplementarmed. Klass. Naturheilkd."));
        result.add(new Abbreviation("Journal of Travel Medicine","J. Travel Med."));
        result.add(new Abbreviation("Annals of Telecommunications","Ann. Telecommun."));
        result.add(new Abbreviation("2D Materials","2D Mater."));
        result.add(new Abbreviation("Surgery","Surgery"));
        result.add(new Abbreviation("Human and Experimental Toxicology","Hum. Exp. Toxicol."));
        result.add(new Abbreviation("Biological Journal of the Linnean Society","Biol. J. Linn. Soc."));
        result.add(new Abbreviation("Journal of Soils and Sediments","J. Soils Sediments"));
        result.add(new Abbreviation("Journal of Geophysical Research, Solid Earth","J. Geophys. Res. Solid Earth"));
        result.add(new Abbreviation("Journal of MMIJ","J. MMIJ"));
        result.add(new Abbreviation("Lutte Contre le Cancer","Lutte Cancer"));
        result.add(new Abbreviation("Neurotoxins","Neurotoxins"));
        result.add(new Abbreviation("Minerals Engineering","Miner. Eng."));
        result.add(new Abbreviation("Macromolecules","Macromolecules"));
        result.add(new Abbreviation("Schweizerische Mineralogische und Petrographische Mitteilungen","Schweiz. Mineral. Petrogr. Mitt."));
        result.add(new Abbreviation("R.I. Medical Journal","R. I. Med. J."));
        result.add(new Abbreviation("Report, U.S. Navy Experimental Diving Unit","Rep. US. Navy Exp. Diving Unit"));
        result.add(new Abbreviation("Nature Reviews Endrocrinology","Nat. Rev. Endocrinol."));
        result.add(new Abbreviation("SA Nursing Journal","SA Nurs. J."));
        result.add(new Abbreviation("Journal of Plant Physiology","J. Plant Physiol."));
        result.add(new Abbreviation("Healthcare Facilities Management Series","Healthc. Facil. Manag. Ser."));
        result.add(new Abbreviation("Preparative Biochemistry","Prep. Biochem."));
        result.add(new Abbreviation("Integrated Healthcare Report","Integr. Healthc. Rep."));
        result.add(new Abbreviation("Journal of Arthroplasty","J. Arthroplasty"));
        result.add(new Abbreviation("Journal of Rehabilitation Research and Development","J. Rehabil. Res. Dev."));
        result.add(new Abbreviation("Population Reports. Series M, Special Topics","Popul. Rep. M"));
        result.add(new Abbreviation("Urologiia i Nefrologiia","Urol. Nefrol. (Mosk.)"));
        result.add(new Abbreviation("Hippocampus","Hippocampus"));
        result.add(new Abbreviation("Omvardaren","Omvardaren"));
        result.add(new Abbreviation("Revista de la Facultad de Odontologia, Universidad de Antioquia","Rev. Fac. Odontol. Univ. Antioq."));
        result.add(new Abbreviation("Medicina del Lavoro","Med. Lav."));
        result.add(new Abbreviation("JSME International Journal Series A: Mechanics and Material Engineering","JSME Int J., Ser. A"));
        result.add(new Abbreviation("International Journal of Environmental Studies","Int. J. Environ. Stud."));
        result.add(new Abbreviation("Additives for Polymers","Addit. Polym."));
        result.add(new Abbreviation("Thrombosis et Diathesis Haemorrhagica. Supplementum","Thromb. Diath. Haemorrh. Suppl."));
        result.add(new Abbreviation("Best Practice & Research, Clinical Haematology","Best Pract. Res. Clin. Haematol."));
        result.add(new Abbreviation("Forschung im Ingenieurwesen","Forsch. Ingenieurwes."));
        result.add(new Abbreviation("Ultrasonics Sonochemistry","Ultrason. Sonochem."));
        result.add(new Abbreviation("Acta Rheumatologica Scandinavica","Acta Rheumatol. Scand."));
        result.add(new Abbreviation("Transactions of the SAEST","Trans. SAEST"));
        result.add(new Abbreviation("Zbornik Vojnomedicinske Akademije","Zb. Vojnomed. Akad."));
        result.add(new Abbreviation("Environmental Practice","Environ. Pract."));
        result.add(new Abbreviation("Enantiomer","Enantiomer"));
        result.add(new Abbreviation("Radiation Biology","Radiat. Biol."));
        result.add(new Abbreviation("Oncology Research","Oncol. Res."));
        result.add(new Abbreviation("Nippon Koku Geka Gakkai Zasshi","Nippon Koku Geka Gakkai Zasshi"));
        result.add(new Abbreviation("British Journal of Obstetrics and Gynaecology","Br. J. Obstet. Gynaecol."));
        result.add(new Abbreviation("Minerva Urologica e Nefrologica","Minerva Urol. Nefrol."));
        result.add(new Abbreviation("Rozprawy Wydzialu Nauk Medycznych","Rozpr. Wydz. Nauk Med."));
        result.add(new Abbreviation("Biomedical and Environmental Mass Spectrometry","Biomed. Environ. Mass Spectrom."));
        result.add(new Abbreviation("Journal of Compliance in Health Care","J. Compliance Health Care"));
        result.add(new Abbreviation("Global Change Biology","Global Change Biol."));
        result.add(new Abbreviation("Journals of Gerontology. Series B, Psychological Sciences and Social Sciences","J. Gerontol. B. Psychol. Sci. Soc. Sci."));
        result.add(new Abbreviation("Current Separations and Drug Development","Curr. Sep Drug Dev."));
        result.add(new Abbreviation("Journal of Nursing Management","J. Nurs. Manag."));
        result.add(new Abbreviation("Opticheskii Zhurnal","Opt. Zh."));
        result.add(new Abbreviation("Archives of Interamerican Rheumatology","Arch. Interam. Rheumatol."));
        result.add(new Abbreviation("Chemisches Zentralblatt","Chem. Zentralbl."));
        result.add(new Abbreviation("Building Operating Management","Build. Oper. Manage."));
        result.add(new Abbreviation("Frontiers of Materials Science in China","Front. Mater. Sci. China"));
        result.add(new Abbreviation("BMC Medical Research Methodology","BMC Med. Res. Methodol."));
        result.add(new Abbreviation("Reactive Polymers","React. Polym."));
        result.add(new Abbreviation("Journal of Cellular and Molecular Medicine","J. Cell. Mol. Med."));
        result.add(new Abbreviation("Journal of Food and Drug Analysis","J. Food Drug Anal."));
        result.add(new Abbreviation("American Journal of Hospice and Palliative Care","Am. J. Hosp. Palliat. Care"));
        result.add(new Abbreviation("Statistical Methods in Medical Research","Stat. Methods Med. Res."));
        result.add(new Abbreviation("Acta Hydrochimica et Hydrobiologica","Acta Hydrochim. Hydrobiol."));
        result.add(new Abbreviation("Advanced Powder Technology","Adv. Powder Technol."));
        result.add(new Abbreviation("Cell","Cell"));
        result.add(new Abbreviation("Israel Journal of Chemistry","Isr. J. Chem."));
        result.add(new Abbreviation("Occupational Health","Occup. Health (Lond.)"));
        result.add(new Abbreviation("Journal of Materials Science: Materials in Medicine","J. Mater. Sci.: Mater. Med."));
        result.add(new Abbreviation("Structure (Cambridge, MA, United States)","Structure (Cambridge, MA, U. S.)"));
        result.add(new Abbreviation("Science in China, Series D: Earth Sciences","Sci. China, Ser. D Earth Sci."));
        result.add(new Abbreviation("Surgeon","Surgeon"));
        result.add(new Abbreviation("IT Professional","IT Prof."));
        result.add(new Abbreviation("Magnesium and Trace Elements","Magnes. Trace Elem."));
        result.add(new Abbreviation("Oil and Chemical Pollution","Oil Chem. Pollut."));
        result.add(new Abbreviation("Plankton and Benthos Research","Plankton Benthos Res."));
        result.add(new Abbreviation("Clinical Colorectal Cancer","Clin. Colorectal Cancer"));
        result.add(new Abbreviation("Waves in Random and Complex Media","Waves Random Complex Medium"));
        result.add(new Abbreviation("Quimica no Brasil","Quim. Bras."));
        result.add(new Abbreviation("Tijdschrift voor Diergeneeskunde","Tijdschr. Diergeneeskd."));
        result.add(new Abbreviation("Pharmacogenomics Journal","Pharmacogenomics J."));
        result.add(new Abbreviation("Journal of Automated Methods & Management in Chemistry","J. Autom. Methods Manage. Chem."));
        result.add(new Abbreviation("Journal of the American Statistical Association","J. Am. Stat. Assoc."));
        result.add(new Abbreviation("Phonetica","Phonetica"));
        result.add(new Abbreviation("Revue Internationale du Trachome et de Pathologie Oculaire Tropicale et Subtropicale","Rev. Int. Trach. Pathol. Ocul. Trop. Subtrop."));
        result.add(new Abbreviation("SIAM Journal on Discrete Mathematics","SIAM J. Discrete Math."));
        result.add(new Abbreviation("Spectroscopic Properties of Inorganic and Organometallic Compounds","Spectrosc. Prop. Inorg. Organomet. Compd."));
        result.add(new Abbreviation("German Medicine","Ger. Med."));
        result.add(new Abbreviation("Nursing Times","Nurs. Times"));
        result.add(new Abbreviation("American Heart Hospital Journal","Am. Heart Hosp. J."));
        result.add(new Abbreviation("American Imago","Am. Imago"));
        result.add(new Abbreviation("European Journal of Nutrition","Eur. J. Nutr."));
        result.add(new Abbreviation("International Journal of Mobile Network Design and Innovation","Int. J. Mobile Network Des. Innov."));
        result.add(new Abbreviation("Surface Topography: Metrology and Properties","Surf. Topogr. Metrol. Prop."));
        result.add(new Abbreviation("Trends in Ecology & Evolution","Trends Ecol. Evol."));
        result.add(new Abbreviation("Doklady Biochemistry and Biophysics","Dokl. Biochem. Biophys."));
        result.add(new Abbreviation("Zahnarztliche Welt, Zahnarztliche Rundschau, ZWR, Vereinigt mit Zahnarztliche Reform","Zahnarztl. Welt. Zahnarztl. Rundsch. ZWR. Zahnarztl. Reform"));
        result.add(new Abbreviation("Mainlines","Mainlines"));
        result.add(new Abbreviation("Management and Compliance Series","Manag. Compliance Ser."));
        result.add(new Abbreviation("Hospital Infection Control","Hosp. Infect. Control"));
        result.add(new Abbreviation("Family Medicine","Fam. Med."));
        result.add(new Abbreviation("Gerodontology","Gerodontology"));
        result.add(new Abbreviation("Comparative Medicine","Comp. Med."));
        result.add(new Abbreviation("Pituitary","Pituitary"));
        result.add(new Abbreviation("Hellenis Adelphe","Hell. Adelphe"));
        result.add(new Abbreviation("Proceedings of the Cambridge Philosophical Society","Proc. Cambridge Philos. Soc."));
        result.add(new Abbreviation("Lotta Contro la Tubercolosi","Lotta Contro Tuberc."));
        result.add(new Abbreviation("Molecular and Cellular Biology","Mol. Cell. Biol."));
        result.add(new Abbreviation("Journal of the American College of Dentists","J. Am. Coll. Dent."));
        result.add(new Abbreviation("Scandinavian Journal of Plastic and Reconstructive Surgery and Hand Surgery. Supplementum","Scand. J. Plast. Reconstr. Surg. Hand Surg. Suppl."));
        result.add(new Abbreviation("Journal of Quality Assurance","J. Qual. Assur."));
        result.add(new Abbreviation("Molecular and Cellular Therapies","Mol. Cell. Ther."));
        result.add(new Abbreviation("Fresenius Environment bulletin","Fresenius Environ. Bull."));
        result.add(new Abbreviation("Enfermedades Infecciosas y Microbiologia Clinica","Enferm. Infecc. Microbiol. Clin."));
        result.add(new Abbreviation("Energy Economics","Energy Econ."));
        result.add(new Abbreviation("Multibody System Dynamics","Multibody Sys.Dyn."));
        result.add(new Abbreviation("Capitation Rates and Data","Capitation Rates Data"));
        result.add(new Abbreviation("CBE Life Sciences Education","CBE Life Sci. Educ."));
        result.add(new Abbreviation("U.S. Geological Survey Professional Paper","U.S. Geol. Surv. Prof. Pap."));
        result.add(new Abbreviation("Pharmacology and Therapeutics. Part B, General and Systematic Pharmacology","Pharmacol. Ther. [B]"));
        result.add(new Abbreviation("Digitale Bilddiagnostik","Digitale Bilddiagn."));
        result.add(new Abbreviation("International Journal of Polymer Analysis and Characterization","Int. J. Polym. Anal. Charact."));
        result.add(new Abbreviation("Biotechnology Letters","Biotechnol. Lett."));
        result.add(new Abbreviation("Applications in Plant Sciences","Appl. Plant Sci."));
        result.add(new Abbreviation("Dental Student","Dent. Stud."));
        result.add(new Abbreviation("Journal of Bone and Joint Surgery. American Volume","J. Bone Joint Surg. Am."));
        result.add(new Abbreviation("MRS Internet Journal of Nitride Semiconductor Research","MRS Internet J. Nitride Semicond. Res."));
        result.add(new Abbreviation("Community Health Studies","Community Health Stud."));
        result.add(new Abbreviation("Okajimas Folia Anatomica Japonica","Okajimas Folia Anat. Jpn."));
        result.add(new Abbreviation("Journal, Canadian Dental Association","J. Can. Dent. Assoc."));
        result.add(new Abbreviation("Beitrage zur Infusionstherapie","Beitr. Infusionsther."));
        result.add(new Abbreviation("Biochemistry and Molecular Biology International","Biochem. Mol. Biol. Int."));
        result.add(new Abbreviation("Developmental Immunology","Dev. Immunol."));
        result.add(new Abbreviation("Archiv fur Lebensmittelhygiene","Arch. Lebensmittelhyg."));
        result.add(new Abbreviation("Journal of Parenteral Science and Technology","J. Parenter. Sci. Technol."));
        result.add(new Abbreviation("Osterreichische Hebammenzeitung","Osterr. Hebammenztg."));
        result.add(new Abbreviation("Josanpu Zasshi (Japanese Journal for Midwives)","Josanpu Zasshi"));
        result.add(new Abbreviation("Advances in Chronic Kidney Disease","Adv. Chronic Kidney Dis."));
        result.add(new Abbreviation("Journal of Hematotherapy and Stem Cell Research","J. Hematother. Stem Cell Res."));
        result.add(new Abbreviation("Promotion et Education","Promot. Educ."));
        result.add(new Abbreviation("Chemico-Biological Interactions","Chem. Biol. Interact."));
        result.add(new Abbreviation("California Medicine","Calif. Med."));
        result.add(new Abbreviation("Gynecologie Pratique","Gynecol. Prat."));
        result.add(new Abbreviation("Family and Community Health","Fam. Community Health"));
        result.add(new Abbreviation("Journal of the Oslo City Hospitals","J. Oslo City Hosp."));
        result.add(new Abbreviation("High Temperature Material Processes","High Temp. Mater. Processes (New York)"));
        result.add(new Abbreviation("Journal of Experimental Social Psychology","J. Exp. Soc. Psychol."));
        result.add(new Abbreviation("Photo-Dermatology","Photodermatol."));
        result.add(new Abbreviation("Journal of Clinical Pathology","J. Clin. Pathol."));
        result.add(new Abbreviation("Protein Journal","Protein J."));
        result.add(new Abbreviation("Folia Morphologica (Poland)","Folia Morphol. (Warsz.)"));
        result.add(new Abbreviation("Soft Matter","Soft Matter"));
        result.add(new Abbreviation("Journal of Computing Science and Engineering","J. Comput. Sci. Eng."));
        result.add(new Abbreviation("Journal of Sound and Vibration","J. Sound Vib."));
        result.add(new Abbreviation("Japanese Journal of Dermatology: Series B","Jpn. J. Dermatol. B"));
        result.add(new Abbreviation("Ergebnisse der Physiologie, Biologischen Chemie und Experimentellen Pharmakologie","Ergeb. Physiol."));
        result.add(new Abbreviation("Military Medicine","Mil. Med."));
        result.add(new Abbreviation("Ciba Foundation Symposium","Ciba Found. Symp."));
        result.add(new Abbreviation("International Journal of Language and Communication Disorders","Int. J. Lang. Commun. Disord."));
        result.add(new Abbreviation("Wiley Interdisciplinary Reviews: Nanomedicine and Nanobiotechnology","Wiley Interdiscip. Rev. Nanomed. Nanobiotechnol."));
        result.add(new Abbreviation("International Journal of Psycho-Analysis","Int. J. Psychoanal."));
        result.add(new Abbreviation("National Institutes of Health Consensus Development Conference Consensus Statement","Natl. Inst. Health Consens. Dev. Conf. Consens. Statement"));
        result.add(new Abbreviation("Disability and Rehabilitation","Disabil. Rehabil."));
        result.add(new Abbreviation("Dentisuto (Dentist)","Dentisuto."));
        result.add(new Abbreviation("Geochemical Transactions","Geochem. Trans."));
        result.add(new Abbreviation("Review of Czechoslovak Medicine","Rev. Czech. Med."));
        result.add(new Abbreviation("Los Alamos National Laboratory, Preprint Archive, General Relativity and Quantum Cosmology","Los Alamos Nat. Lab. Prepr. Arch. Gen. Relativ. Quantum Cosmol."));
        result.add(new Abbreviation("Journal of Sedimentary Research","J. Sediment. Res."));
        result.add(new Abbreviation("Journal of Heart and Lung Transplantation","J. Heart Lung Transplant."));
        result.add(new Abbreviation("Osterreichische Zeitschrift fur Stomatologie","Osterr. Z. Stomatol."));
        result.add(new Abbreviation("Endodontic Report","Endod. Rep."));
        result.add(new Abbreviation("Journal of Biochemical Toxicology","J. Biochem. Toxicol."));
        result.add(new Abbreviation("Hellenic Journal of Cardiology","Hellenic J. Cardiol."));
        result.add(new Abbreviation("Progress in Biomaterials","Prog. Biomater."));
        result.add(new Abbreviation("Drying Technology","Drying Technol."));
        result.add(new Abbreviation("British Journal of Addiction to Alcohol and Other Drugs","Br. J. Addict. Alcohol Other Drugs"));
        result.add(new Abbreviation("Zeitschrift für Meteorologie","Z. Meteor."));
        result.add(new Abbreviation("Depression and Anxiety","Depress. Anxiety"));
        result.add(new Abbreviation("CRC Critical Reviews in Microbiology","CRC Crit. Rev. Microbiol."));
        result.add(new Abbreviation("Applied Soil Ecology","Appl. Soil Ecol."));
        result.add(new Abbreviation("Environmental Pollution (Amsterdam, Netherlands)","Environ. Pollut. (Amsterdam, Neth.)"));
        result.add(new Abbreviation("Turk Tip Dernegi Dergisi","Turk Tip Dernegi Derg."));
        result.add(new Abbreviation("Healthcare Information Management","Healthc. Inf. Manage."));
        result.add(new Abbreviation("Best Practice and Research. Clinical Anaesthesiology","Best Pract. Res. Clin. Anaesthesiol."));
        result.add(new Abbreviation("Molecular Neurobiology","Mol. Neurobiol."));
        result.add(new Abbreviation("Shiyo (Journal of the Tokyo Dental Association)","Shiyo"));
        result.add(new Abbreviation("Quarterly Journal of the Geological Society of London","Q. J. Geol. Soc. London"));
        result.add(new Abbreviation("Journal of Ultrasound in Medicine","J. Ultrasound Med."));
        result.add(new Abbreviation("Ukrains'kii Fizichnii Zhurnal","Ukr. Fiz. Zh."));
        result.add(new Abbreviation("Neues Jahrbuch fur Mineralogie, Geologie und Palaeontologie, Abhandlungen Abteiling B: Geologie, Palaeontologie","Neues Jahrb. Mineral. Geol. Palaeontol. Abh. Abt. B"));
        result.add(new Abbreviation("Plugger; Iowa Dental Assistants Journal","Plugger."));
        result.add(new Abbreviation("MLO; Medical Laboratory Observer","MLO. Med. Lab. Obs."));
        result.add(new Abbreviation("West African Journal of Pharmacology and Drug Research","West Afr. J. Pharmacol. Drug Res."));
        result.add(new Abbreviation("Giornale Italiano di Cardiologia","G. Ital. Cardiol."));
        result.add(new Abbreviation("Acta Orthopaedica Scandinavica. Supplementum","Acta Orthop. Scand. Suppl."));
        result.add(new Abbreviation("Water International","Water Int."));
        result.add(new Abbreviation("Hospital Technology Series","Hosp. Technol. Ser."));
        result.add(new Abbreviation("Heart Rhythm","Heart Rhythm"));
        result.add(new Abbreviation("Plant Signaling & Behavior","Plant Signaling Behav."));
        result.add(new Abbreviation("Journal American Water Works Association","J. Am. Water Works Assn."));
        result.add(new Abbreviation("Brain and Cognition","Brain Cogn."));
        result.add(new Abbreviation("Journal of Sustainable Forestry","J. Sustainable For."));
        result.add(new Abbreviation("Parasite","Parasite"));
        result.add(new Abbreviation("International Journal of Molecular Medicine and Advance Sciences","Int. J. Mol. Med. Adv. Sci."));
        result.add(new Abbreviation("International Journal of Bifurcation and Chaos in Applied Sciences and Engineering","Int. J. Bifurcation Chaos Appl. Sci. Eng."));
        result.add(new Abbreviation("Therapiewoche","Therapiewoche"));
        result.add(new Abbreviation("Advances in Biology of Skin","Adv. Biol. Skin"));
        result.add(new Abbreviation("Chief Information Officer Journal","Chief Inf. Off. J."));
        result.add(new Abbreviation("Online Journal of Current Clinical Trials","Online J. Curr. Clin. Trials"));
        result.add(new Abbreviation("Histochemistry","Histochemistry"));
        result.add(new Abbreviation("Biological Rhythm Research","Biol. Rhythm Res."));
        result.add(new Abbreviation("Malaysian Journal of Pathology","Malays. J. Pathol."));
        result.add(new Abbreviation("Acta Belgica. Medica Physica","Acta Belg. Med. Phys."));
        result.add(new Abbreviation("Archives Belges de Medecine Sociale, Hygiene, Medecine du Travail et Medecine Legale","Arch. Belg. Med. Soc."));
        result.add(new Abbreviation("Journal of Immunological Methods","J. Immunol. Methods"));
        result.add(new Abbreviation("Nurse Anesthesia","Nurse Anesth."));
        result.add(new Abbreviation("Oil, Gas (Hamburg, Germany)","Oil, Gas (Hamburg, Ger.)"));
        result.add(new Abbreviation("Journal of General Microbiology","J. Gen. Microbiol."));
        result.add(new Abbreviation("Advances in Polymer Technology","Adv. Polym. Technol."));
        result.add(new Abbreviation("Bulletin de la Societe de Pathologie Exotique","Bull. Soc. Pathol. Exot."));
        result.add(new Abbreviation("Public Health Papers","Public Health Pap."));
        result.add(new Abbreviation("Comments on Astrophysics","Comments Astrophys."));
        result.add(new Abbreviation("Gigiena i Sanitariia","Gig. Sanit."));
        result.add(new Abbreviation("Research in Health Economics","Res. Health Econ."));
        result.add(new Abbreviation("Public Administration Review","Public Adm. Rev."));
        result.add(new Abbreviation("EMBO Reports","EMBO Rep."));
        result.add(new Abbreviation("Endeavour","Endeavour"));
        result.add(new Abbreviation("ACS Macro Letters","ACS Macro Lett."));
        result.add(new Abbreviation("Critical Reviews in Eukaryotic Gene Expression","Crit. Rev. Eukaryot. Gene Expr."));
        result.add(new Abbreviation("Journal of Drugs in Dermatology","J. Drugs Dermatol."));
        result.add(new Abbreviation("Hospital Capital Finance","Hosp. Cap. Finance"));
        result.add(new Abbreviation("Critical Reviews in Clinical Laboratory Sciences","Crit. Rev. Clin. Lab. Sci."));
        result.add(new Abbreviation("Journal of Industrial Ecology","J. Ind. Ecol."));
        result.add(new Abbreviation("Aquatic Conservation: Marine and Freshwater Ecosystems","Aquat. Conserv. Mar. Freshwater Ecosyst."));
        result.add(new Abbreviation("Asepsis","Asepsis"));
        result.add(new Abbreviation("Canadian Journal of Pharmaceutical Sciences","Can. J. Pharm. Sci."));
        result.add(new Abbreviation("International Journal of Oral and Maxillofacial Surgery","Int. J. Oral Maxillofac. Surg."));
        result.add(new Abbreviation("Developmental Biology","Dev. Biol."));
        result.add(new Abbreviation("Oncogene Research","Oncogene Res."));
        result.add(new Abbreviation("Hansenologia Internationalis","Hansenol. Int."));
        result.add(new Abbreviation("Odontologia","Odontologia"));
        result.add(new Abbreviation("Acta Zoologica et Pathologica Antverpiensia","Acta Zool. Pathol. Antverp."));
        result.add(new Abbreviation("Seminars in Adolescent Medicine","Semin. Adolesc. Med."));
        result.add(new Abbreviation("Journal of Pharmacological Sciences","J. Pharmacol. Sci."));
        result.add(new Abbreviation("Electroencephalography and Clinical Neurophysiology. Supplement","Electroencephalogr. Clin. Neurophysiol. Suppl."));
        result.add(new Abbreviation("Journal of Laryngology and Otology. Supplement","J. Laryngol. Otol. Suppl."));
        result.add(new Abbreviation("Kathmandu University Medical Journal","Kathmandu Univ. Med. J."));
        result.add(new Abbreviation("Nihon Rinsho Shishubyo Danwakai Kaishi (Journal of the Japanese Society of Periodontists)","Nihon Rinsho Shishubyo Danwakai Kaishi"));
        result.add(new Abbreviation("Journal of Comparative Effectiveness Research","J. Comp. Eff. Res."));
        result.add(new Abbreviation("Journal of Nursing Quality Assurance","J. Nurs. Qual. Assur."));
        result.add(new Abbreviation("Spectrum","Spectrum"));
        result.add(new Abbreviation("Inorganic Reaction Mechanisms (Philadelphia, PA, United States)","Inorg. React. Mech. (Philadelphia, PA, U. S.)"));
        result.add(new Abbreviation("Clinical Preventive Dentistry","Clin. Prev. Dent."));
        result.add(new Abbreviation("American Journal of Neuroprotection and Neuroregeneration","Am. J. Neuroprot. Neuroregener."));
        result.add(new Abbreviation("Christian Nurse","Christ. Nurse (Mysore)"));
        result.add(new Abbreviation("Sairaanhoitaja","Sairaanhoitaja"));
        result.add(new Abbreviation("Journal of Urban Health","J. Urban Health"));
        result.add(new Abbreviation("Journal of the Medical Association of the State of Alabama","J. Med. Assoc. State Ala."));
        result.add(new Abbreviation("Applied Surface Science","Appl. Surf. Sci."));
        result.add(new Abbreviation("Bulletin of the Chemical Society of Japan","Bull. Chem. Soc. Jpn."));
        result.add(new Abbreviation("Nanomedicine","Nanomedicine"));
        result.add(new Abbreviation("Journal of Hydrology","J. Hydrol."));
        result.add(new Abbreviation("International Journal of Clinical and Laboratory Research","Int. J. Clin. Lab. Res."));
        result.add(new Abbreviation("Noseleutike","Noseleutike"));
        result.add(new Abbreviation("Pro Re Nata","Pro Re Nata"));
        result.add(new Abbreviation("Astrobiology","Astrobiology"));
        result.add(new Abbreviation("International Journal of Hyperthermia","Int. J. Hyperthermia"));
        result.add(new Abbreviation("Disease-a-Month","Dis. Mon."));
        result.add(new Abbreviation("Medicinal Chemistry Research","Med. Chem. Res."));
        result.add(new Abbreviation("Microbiologica","Microbiologica"));
        result.add(new Abbreviation("Concrete Engineering International","Concr. Eng. Int."));
        result.add(new Abbreviation("Deutsche Schwesternzeitung","Dtsch. Schwesternztg."));
        result.add(new Abbreviation("Journal of Traditional Chinese Medicine","J. Tradit. Chin. Med."));
        result.add(new Abbreviation("Molecular Ecology Resources","Mol. Ecol. Resour."));
        result.add(new Abbreviation("Policlinico. Sezione Pratica","Policlinico. [Prat.]"));
        result.add(new Abbreviation("Romanian Journal of Chemistry","Rom. J. Chem."));
        result.add(new Abbreviation("Minerva Oftalmologica","Minerva Oftalmol."));
        result.add(new Abbreviation("Aquatic Geochemistry","Aquat. Geochem."));
        result.add(new Abbreviation("Acta Farmaceutica Bonaerense","Acta Farm. Bonaerense"));
        result.add(new Abbreviation("Physik Journal","Phys. J."));
        result.add(new Abbreviation("Animal Reproduction Science","Anim. Reprod. Sci."));
        result.add(new Abbreviation("Climate Risk Management","Clim. Risk Manage."));
        result.add(new Abbreviation("Powder Metallurgy and Metal Ceramics","Powder Metall. Met. Ceram."));
        result.add(new Abbreviation("Journal of the National Association of Seventh-Day Adventist Dentists","J. Natl. Assoc. Seventh. Day Advent. Dent."));
        result.add(new Abbreviation("UNA Nursing Journal","UNA Nurs. J."));
        result.add(new Abbreviation("Journal of Tropical Ecology","J. Trop. Ecology"));
        result.add(new Abbreviation("International Journal of Modern Physics E: Nuclear Physics","Int. J. Mod. Phys. E"));
        result.add(new Abbreviation("Nutrition in Clinical Care","Nutr. Clin. Care"));
        result.add(new Abbreviation("Schweizerische Rundschau fur Medizin Praxis","Schweiz. Rundsch. Med. Prax."));
        result.add(new Abbreviation("Journal of the American Society of Nephrology","J. Am. Soc. Nephrol."));
        result.add(new Abbreviation("New England Journal of Medicine","N. Engl. J. Med."));
        result.add(new Abbreviation("BMC Chemical Biology","BMC Chem. Biol"));
        result.add(new Abbreviation("Genes and Function","Genes Funct."));
        result.add(new Abbreviation("Journal of the American Water Resources Association","J. Am. Water Resour. Assoc."));
        result.add(new Abbreviation("Toxicological Sciences","Toxicol. Sci."));
        result.add(new Abbreviation("Brain Topography","Brain Topogr."));
        result.add(new Abbreviation("Canadian Pharmaceutical Journal","Can. Pharm. J."));
        result.add(new Abbreviation("International Journal of Pancreatology","Int. J. Pancreatol."));
        result.add(new Abbreviation("American Journal of Transplantation","Am. J. Transplant."));
        result.add(new Abbreviation("Asian Pacific Journal of Cancer Prevention","Asian Pac. J. Cancer Prev."));
        result.add(new Abbreviation("Quarterly Journal of the Chemical Society","Q. J. Chem. Soc."));
        result.add(new Abbreviation("Pharmaceutisch Weekblad. Scientific Edition","Pharm. Weekbl. Sci."));
        result.add(new Abbreviation("Computational Geometry: Theory and Applications","Comput. Geom. Theory Appl."));
        result.add(new Abbreviation("American Biotechnology Laboratory","Am. Biotechnol. Lab."));
        result.add(new Abbreviation("Methods","Methods"));
        result.add(new Abbreviation("Nuclear and Chemical Waste Management","Nucl. Chem. Waste Manage."));
        result.add(new Abbreviation("Resources, Conservation and Recycling","Resour. Conserv. Recycl."));
        result.add(new Abbreviation("Revue de Paleobiologie","Rev. Paleobiol."));
        result.add(new Abbreviation("National Institute of Animal Health Quarterly","Natl. Inst. Anim. Health Q. (Tokyo)"));
        result.add(new Abbreviation("Giornale Italiano della Tubercolosi e delle Malattie del Torace","G. Ital. Tuberc. Mal. Torace"));
        result.add(new Abbreviation("Cahiers du Nursing","Cah. Nurs."));
        result.add(new Abbreviation("Zeitschrift fur Erkrankungen der Atmungsorgane","Z. Erkr. Atmungsorgane"));
        result.add(new Abbreviation("Revista de Neurologia","Rev. Neurol."));
        result.add(new Abbreviation("Advanced Cement Based Materials","Adv. Cem. Based Mater."));
        result.add(new Abbreviation("Protein & Peptide Letters","Protein Pept. Lett."));
        result.add(new Abbreviation("International Journal of Technology and Human Interaction","Int. J. Technol. Hum. Interact."));
        result.add(new Abbreviation("Lecture Notes in Physics Monographs","Lect. Notes Phys. Monogr."));
        result.add(new Abbreviation("European Journal of Pharmacology: Molecular Pharmacology","Eur. J. Pharmacol. Mol. Pharmacol."));
        result.add(new Abbreviation("International Journal of Medical Robotics and Computer Assisted Surgery","Int. J. Med. Rob. Comput. Assisted Surg."));
        result.add(new Abbreviation("Journal of Statistical Physics","J. Stat. Phys."));
        result.add(new Abbreviation("Acta Crystallographica. Section D, Biological Crystallography","Acta Crystallogr. D Biol. Crystallogr."));
        result.add(new Abbreviation("International Journal of Radiation Applications and Instrumentation. Part E. Nuclear Geophysics","Int. J. Radiat. Appl. Instrum. Part E"));
        result.add(new Abbreviation("Mitteilungen der Deutschen Pharmazeutischen Gesellschaft und der Pharmazeutischen Gesellschaft der DDR","Mitt. Dtsch. Pharm. Ges. Pharm. Ges. DDR"));
        result.add(new Abbreviation("Documenta Ophthalmologica","Doc. Ophthalmol."));
        result.add(new Abbreviation("IARC Monographs on the Evaluation of the Carcinogenic Risk of Chemicals to Humans. Supplement","IARC Monogr. Eval. Carcinog. Risk Chem. Hum. Suppl."));
        result.add(new Abbreviation("Social Biology","Soc. Biol."));
        result.add(new Abbreviation("Indian Journal of Pure and Applied Physics","Indian J. Pure Appl. Phys."));
        result.add(new Abbreviation("Publications of the Astronomical Society of Japan","Publ. Astron. Soc. Jpn."));
        result.add(new Abbreviation("Solar System Research","Sol. Syst. Res."));
        result.add(new Abbreviation("FEMS Yeast Research","FEMS Yeast Res."));
        result.add(new Abbreviation("Monographs of the American Association on Mental Deficiency","Monogr. Am. Assoc. Ment. Defic."));
        result.add(new Abbreviation("Nippon Kyobu Geka Gakkai Zasshi (Journal of the Japanese Association for Thoracic Surgery)","Nippon Kyobu Geka Gakkai Zasshi"));
        result.add(new Abbreviation("Progress in Biophysics and Molecular biology","Prog. Biophys. Mol. Biol."));

        return result;
    }
}
