package org.jabref.logic.journals;

import java.util.ArrayList;
import java.util.List;

public class IeeeAbbreviationLists {

    public static List<Abbreviation> getOfficialAbbreviations() {
        List<Abbreviation> result = new ArrayList<>(263);

        result.add(new Abbreviation("IEEE Communications Surveys and Tutorials","#IEEE_O_CSTO#"));
        result.add(new Abbreviation("IEEE Computing in Science and Engineering","#IEEE_M_CSE#"));
        result.add(new Abbreviation("IEEE Transactions on Parts, Materials and Packaging","#IEEE_J_PMP#"));
        result.add(new Abbreviation("IEEE Journal of Optical Communications and Networking","#IEEE_J_OCN#"));
        result.add(new Abbreviation("IEEE Expert","#IEEE_M_EXP#"));
        result.add(new Abbreviation("IEEE Transactions on Engineering Writing and Speech","#IEEE_J_EWS#"));
        result.add(new Abbreviation("IEEE Transactions on Human Factors in Electronics","#IEEE_J_HFE#"));
        result.add(new Abbreviation("IEEE Transactions on Applied Superconductivity","#IEEE_J_ASC#"));
        result.add(new Abbreviation("IEEE Translation Journal on Magnetics in Japan","#IEEE_J_TJMJ#"));
        result.add(new Abbreviation("IEEE Security and Privacy","#IEEE_M_SAP#"));
        result.add(new Abbreviation("IEEE Sensors Journal","#IEEE_J_SENSOR#"));
        result.add(new Abbreviation("IEEE Transactions on Terahertz Science and Technology","#IEEE_J_TTHZ#"));
        result.add(new Abbreviation("IEEE Pulse","#IEEE_M_PULSE#"));
        result.add(new Abbreviation("IEEE Circuits and Devices Magazine","#IEEE_M_CD#"));
        result.add(new Abbreviation("IEEE Transactions on Power Electronics","#IEEE_J_PWRE#"));
        result.add(new Abbreviation("IEEE Transactions on Systems Science and Cybernetics","#IEEE_J_SSC#"));
        result.add(new Abbreviation("IEEE Solid-State Circuits Magazine","#IEEE_M_SSC#"));
        result.add(new Abbreviation("IEEE Transactions on Computational Intelligence and AI in Games","#IEEE_J_CIAIG#"));
        result.add(new Abbreviation("IEEE Transactions on Dielectrics and Electrical Insulation","#IEEE_J_DEI#"));
        result.add(new Abbreviation("IEEE Concurrency","#IEEE_M_CONC#"));
        result.add(new Abbreviation("IEEE Network","#IEEE_M_NET#"));
        result.add(new Abbreviation("IEEE Wireless Communications Letters","#IEEE_J_WCOML#"));
        result.add(new Abbreviation("IEEE Computer Graphics and Applications","#IEEE_M_CGA#"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Express Briefs","#IEEE_J_CASII_EB#"));
        result.add(new Abbreviation("Computer","#IEEE_M_C#"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications","#IEEE_J_CASI#"));
        result.add(new Abbreviation("IEEE Transactions on Applications and Industry","#IEEE_J_APPIND#"));
        result.add(new Abbreviation("IEEE Transactions on Bio-Medical Engineering","#IEEE_J_B-ME#"));
        result.add(new Abbreviation("IEEE Robotics and Automation Magazine","#IEEE_M_RA#"));
        result.add(new Abbreviation("IEEE Vehicular Technology Magazine","#IEEE_M_VT#"));
        result.add(new Abbreviation("IEEE Transactions on Professional Communication","#IEEE_J_PC#"));
        result.add(new Abbreviation("IEEE Transactions on Biomedical Engineering","#IEEE_J_BME#"));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology","#IEEE_J_CPMT#"));
        result.add(new Abbreviation("IEEE Design & Test","#IEEE_M_DT#"));
        result.add(new Abbreviation("IEEE Transactions on Pattern Analysis and Machine Intelligence","#IEEE_J_PAMI#"));
        result.add(new Abbreviation("IEEE Control Systems Magazine","#IEEE_M_CS#"));
        result.add(new Abbreviation("IEEE Intelligent Transportation Systems Magazine","#IEEE_M_ITS#"));
        result.add(new Abbreviation("IEEE Transactions on Industrial Electronics","#IEEE_J_IE#"));
        result.add(new Abbreviation("IEEE Transactions on NanoBioscience","#IEEE_J_NB#"));
        result.add(new Abbreviation("IEEE Transactions on Engineering Management","#IEEE_J_EM#"));
        result.add(new Abbreviation("IEEE ASSP Magazine","#IEEE_M_ASSP#"));
        result.add(new Abbreviation("IEEE Journal on Multiscale and Multiphysics Computational Techniques","#IEEE_J_MMCT#"));
        result.add(new Abbreviation("IEEE Microwave Magazine","#IEEE_M_MW#"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics C: Applications and Reviews","#IEEE_J_SMCC#"));
        result.add(new Abbreviation("IEEE Internet of Things Journal","#IEEE_J_IOT#"));
        result.add(new Abbreviation("IEEE Transactions on Industry Applications","#IEEE_J_IA#"));
        result.add(new Abbreviation("IEEE Transactions on Magnetics","#IEEE_J_MAG#"));
        result.add(new Abbreviation("IEEE Revista Iberoamericana de Technolog'ias del Aprendizaje","#IEEE_J_RITA#"));
        result.add(new Abbreviation("IEEE Power and Energy Technology Systems Journal","#IEEE_J_PETS#"));
        result.add(new Abbreviation("IEEE Transactions on Aerospace","#IEEE_J_AS#"));
        result.add(new Abbreviation("IEEE/ACM Transactions on Networking","#IEEE_J_NET#"));
        result.add(new Abbreviation("IEEE Life Sciences Letters","#IEEE_J_LS#"));
        result.add(new Abbreviation("IEEE Transactions on Industrial Informatics","#IEEE_J_IINF#"));
        result.add(new Abbreviation("IEEE IT Professional","#IEEE_M_ITP#"));
        result.add(new Abbreviation("IEEE Transactions on Robotics","#IEEE_J_RO#"));
        result.add(new Abbreviation("IEEE Transactions on Aeronautical and Navigational Electronics","#IEEE_J_ANNE#"));
        result.add(new Abbreviation("IEEE Transactions on Audio and Electroacoustics","#IEEE_J_AUEA#"));
        result.add(new Abbreviation("IEEE Spectrum","#IEEE_M_SPECT#"));
        result.add(new Abbreviation("IEEE Wireless Communications","#IEEE_M_WC#"));
        result.add(new Abbreviation("IEEE/OSA Journal of Display Technology","#IEEE_J_JDT#"));
        result.add(new Abbreviation("IEEE Power and Energy Magazine","#IEEE_M_PE#"));
        result.add(new Abbreviation("IEEE Reviews in Biomedical Engineering","#IEEE_J_RBME#"));
        result.add(new Abbreviation("IEEE Embedded Systems Letters","#IEEE_J_ES#"));
        result.add(new Abbreviation("IEEE Transactions on Automatic Control","#IEEE_J_AC#"));
        result.add(new Abbreviation("Proceedings of the IEEE","#IEEE_J_PROC#"));
        result.add(new Abbreviation("IEEE Transactions on Education","#IEEE_J_EDU#"));
        result.add(new Abbreviation("IEEE Transactions on Information Forensics and Security","#IEEE_J_IFS#"));
        result.add(new Abbreviation("IEEE Transactions on Software Engineering","#IEEE_J_SE#"));
        result.add(new Abbreviation("IEEE Journal of Electron Devices Society","#IEEE_J_EDS#"));
        result.add(new Abbreviation("IEEE Transactions on Autonomous Mental Development","#IEEE_J_AMD#"));
        result.add(new Abbreviation("IEEE Power Electronics Letters","#IEEE_J_PEL#"));
        result.add(new Abbreviation("IEEE Transactions on Multi-Scale Computing Systems","#IEEE_J_MSCS#"));
        result.add(new Abbreviation("IEEE Transactions on Knowledge and Data Engineering","#IEEE_J_KDE#"));
        result.add(new Abbreviation("IEEE Transactions on Bio-Medical Electronics","#IEEE_J_BMELC#"));
        result.add(new Abbreviation("IEEE Transactions on Energy Conversion","#IEEE_J_EC#"));
        result.add(new Abbreviation("IEEE Journal of Quantum Electronics","#IEEE_J_JQE#"));
        result.add(new Abbreviation("IEEE Transactions on Antennas and Propagation","#IEEE_J_AP#"));
        result.add(new Abbreviation("IEEE Transactions on Components and Packaging Technology","#IEEE_J_CAPT#"));
        result.add(new Abbreviation("IEEE Transactions on Intelligent Transportation Systems","#IEEE_J_ITS#"));
        result.add(new Abbreviation("IEEE Transactions on Smart Grid","#IEEE_J_SG#"));
        result.add(new Abbreviation("IEEE Transactions on Military Electronics","#IEEE_J_MIL#"));
        result.add(new Abbreviation("IEEE Industry Applications Magazine","#IEEE_M_IA#"));
        result.add(new Abbreviation("Today's Engineer","#IEEE_M_TODAY#"));
        result.add(new Abbreviation("IEEE Transactions on Semiconductor Manufacturing","#IEEE_J_SM#"));
        result.add(new Abbreviation("IEEE/ECS Electrochemical and Solid-State Letters","#IEEE_J_ESSL#"));
        result.add(new Abbreviation("IEEE Photonics Journal","#IEEE_J_PJ#"));
        result.add(new Abbreviation("IEEE Journal of Robotics and Automation","#IEEE_J_JRA#"));
        result.add(new Abbreviation("IEEE Transactions on Acoustics, Speech, and Signal Processing","#IEEE_J_ASSP#"));
        result.add(new Abbreviation("IEEE Communications Society Magazine","#IEEE_M_COMSOC#"));
        result.add(new Abbreviation("IEEE Transactions on Nuclear Science","#IEEE_J_NS#"));
        result.add(new Abbreviation("IEEE Microwave and Wireless Components Letters","#IEEE_J_MWCL#"));
        result.add(new Abbreviation("IEEE Transactions on Rehabilitation Engineering","#IEEE_J_RE#"));
        result.add(new Abbreviation("IEEE Transactions on Network and Service Management","#IEEE_J_NSM#"));
        result.add(new Abbreviation("IEEE Transactions on Intelligent Vehicles","#IEEE_J_IV#"));
        result.add(new Abbreviation("IEEE Transactions on Parallel and Distributed Systems","#IEEE_J_PDS#"));
        result.add(new Abbreviation("IEEE Transactions on Control of Network Systems","#IEEE_J_CNS#"));
        result.add(new Abbreviation("IEEE Microwave and Guided Wave Letters","#IEEE_J_MGWL#"));
        result.add(new Abbreviation("IEEE Transactions on Plasma Science","#IEEE_J_PS#"));
        result.add(new Abbreviation("IEEE Transactions on Microwave Theory and Techniques","#IEEE_J_MTT#"));
        result.add(new Abbreviation("IEEE Transactions on Electronics Packaging Manufacturing","#IEEE_J_EPM#"));
        result.add(new Abbreviation("IEEE Transactions on Man-Machine Systems","#IEEE_J_MMS#"));
        result.add(new Abbreviation("IEEE/ACM Transactions on Computational Biology and Bioinformatics","#IEEE_J_CBB#"));
        result.add(new Abbreviation("IEEE Journal of Translational Engineering in Health and Medicine","#IEEE_J_TEHM#"));
        result.add(new Abbreviation("IEEE Transactions on Nanotechnology","#IEEE_J_NANO#"));
        result.add(new Abbreviation("IEEE Transactions on Power Apparatus and Systems","#IEEE_J_PWRAS#"));
        result.add(new Abbreviation("IEEE Transactions on Services Computing","#IEEE_J_SC#"));
        result.add(new Abbreviation("IEEE Computer Applications in Power","#IEEE_M_CAP#"));
        result.add(new Abbreviation("IEEE Transactions on Electromagnetic Compatibility","#IEEE_J_EMC#"));
        result.add(new Abbreviation("IEEE Transactions on Consumer Electronics","#IEEE_J_CE#"));
        result.add(new Abbreviation("IEEE Electron Device Letters","#IEEE_J_EDL#"));
        result.add(new Abbreviation("IEEE Transactions on Cognitive and Developmental Systems","#IEEE_J_CDS#"));
        result.add(new Abbreviation("IEEE Transactions on Transportation Electrification","#IEEE_J_TTE#"));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology C: Manufacturing","#IEEE_J_CPMTC#"));
        result.add(new Abbreviation("IEEE Design and Test of Computers","#IEEE_M_DTC#"));
        result.add(new Abbreviation("IEEE Nanotechnology Express","#IEEE_J_ENANO#"));
        result.add(new Abbreviation("IEEE Journal of Selected Topics in Quantum Electronics","#IEEE_J_JSTQE#"));
        result.add(new Abbreviation("IEEE/CAA Journal of Automatica Sinica","#IEEE_J_JAS#"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems","#IEEE_J_CAS#"));
        result.add(new Abbreviation("IEEE Transactions on Mobile Computing","#IEEE_J_MC#"));
        result.add(new Abbreviation("IEEE Transactions on Vehicular Communications","#IEEE_J_VC#"));
        result.add(new Abbreviation("IEEE Journal of Microelectromechanical Systems","#IEEE_J_MEMSI#"));
        result.add(new Abbreviation("IEEE Transactions on Electron Devices","#IEEE_J_ED#"));
        result.add(new Abbreviation("IEEE Robotics and Automation Letters","#IEEE_J_RAL#"));
        result.add(new Abbreviation("IEEE Transactions on Communications","#IEEE_J_COM#"));
        result.add(new Abbreviation("IEEE Signal Processing Letters","#IEEE_J_SPL#"));
        result.add(new Abbreviation("IEEE Transactions on Neural Networks","#IEEE_J_NN#"));
        result.add(new Abbreviation("IEEE Journal of Selected Topics in Signal Processing","#IEEE_J_STSP#"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems for Video Technology","#IEEE_J_CASVT#"));
        result.add(new Abbreviation("IEEE Journal on Technology in Computer Aided Design","#IEEE_J_TCAD#"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics: Systems","#IEEE_J_SMCS#"));
        result.add(new Abbreviation("IEEE Transactions on Haptics","#IEEE_J_H#"));
        result.add(new Abbreviation("IEEE Transactions on Biomedical Circuits and Systems","#IEEE_J_BCAS#"));
        result.add(new Abbreviation("IEEE Transactions on Electrical Insulation","#IEEE_J_EI#"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Regular Papers","#IEEE_J_CASI_RP#"));
        result.add(new Abbreviation("IEEE Transactions on Very Large Scale Integration (VLSI) Systems","#IEEE_J_VLSI#"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Analog and Digital Signal Processing","#IEEE_J_CASII#"));
        result.add(new Abbreviation("IEEE/TMS Journal of Electronic Materials","#IEEE_J_JEM#"));
        result.add(new Abbreviation("IEEE Power Engineering Review","#IEEE_M_PER#"));
        result.add(new Abbreviation("IEEE Transactions on Ultrasonics, Ferroelectrics, and Frequency Control","#IEEE_J_UFFC#"));
        result.add(new Abbreviation("IEEE Transactions on Industry and General Applications","#IEEE_J_IGA#"));
        result.add(new Abbreviation("IEEE Aerospace and Electronics Systems Magazine","#IEEE_M_AES#"));
        result.add(new Abbreviation("IEEE Transactions on Wireless Communications","#IEEE_J_WCOM#"));
        result.add(new Abbreviation("IEEE Transactions on Emerging Topics in Computing","#IEEE_J_ETC#"));
        result.add(new Abbreviation("IEEE Transactions on Robotics and Automation","#IEEE_J_RA#"));
        result.add(new Abbreviation("IEEE Transactions on Electronic Computers","#IEEE_J_ECOMP#"));
        result.add(new Abbreviation("IEEE Transactions on Manufacturing Technology","#IEEE_J_MFT#"));
        result.add(new Abbreviation("IEEE Personal Communications Magazine","#IEEE_M_PCOM#"));
        result.add(new Abbreviation("IEEE Antennas and Propagation Magazine","#IEEE_M_AP#"));
        result.add(new Abbreviation("IEEE Transactions on Medical Imaging","#IEEE_J_MI#"));
        result.add(new Abbreviation("IEEE Geoscience and Remote Sensing Letters","#IEEE_J_GRSL#"));
        result.add(new Abbreviation("IEEE Transactions on Multimedia","#IEEE_J_MM#"));
        result.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Power Electronics","#IEEE_J_ESTPE#"));
        result.add(new Abbreviation("IEEE ElectroTechnology Review","#IEEE_M_ETR#"));
        result.add(new Abbreviation("IEEE Journal on Exploratory Solid-State Computational Devices and Circuits","#IEEE_J_XCDC#"));
        result.add(new Abbreviation("IEEE Transactions on Sustainable Energy","#IEEE_J_STE#"));
        result.add(new Abbreviation("IEEE Software","#IEEE_M_S#"));
        result.add(new Abbreviation("IEEE Electrical Insulation Magazine","#IEEE_M_EI#"));
        result.add(new Abbreviation("IEEE Journal of Biomedical and Health Informatics","#IEEE_J_BHI#"));
        result.add(new Abbreviation("IEEE Transactions on Dependable and Secure Computing","#IEEE_J_DSC#"));
        result.add(new Abbreviation("IEEE Engineering Management Review","#IEEE_M_EMR#"));
        result.add(new Abbreviation("IEEE Transactions on Geoscience and Remote Sensing","#IEEE_J_GRS#"));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology A","#IEEE_J_CPMTA#"));
        result.add(new Abbreviation("IEEE Transactions on Visualization and Computer Graphics","#IEEE_J_VCG#"));
        result.add(new Abbreviation("IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems","#IEEE_J_CAD#"));
        result.add(new Abbreviation("IEEE Systems, Man, and Cybernetics Magazine","#IEEE_M_SMC#"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics A: Systems and Humans","#IEEE_J_SMCA#"));
        result.add(new Abbreviation("IEEE Technology and Society Magazine","#IEEE_M_TS#"));
        result.add(new Abbreviation("IEEE Nanotechnology Magazine","#IEEE_M_NANO#"));
        result.add(new Abbreviation("IEEE Transactions on Automation Science and Engineering","#IEEE_J_ASE#"));
        result.add(new Abbreviation("IEEE Transactions on Neural Networks and Learning Systems","#IEEE_J_NNLS#"));
        result.add(new Abbreviation("IEEE Instrumentation and Measurement Magazine","#IEEE_M_IM#"));
        result.add(new Abbreviation("IEEE Transactions on Signal and Information Processing over Networks","#IEEE_J_SIPN#"));
        result.add(new Abbreviation("IEEE Geoscience and Remote Sensing Magazine","#IEEE_M_GRS#"));
        result.add(new Abbreviation("IEEE Transactions on Computers","#IEEE_J_C#"));
        result.add(new Abbreviation("IEEE Pervasive Computing","#IEEE_M_PVC#"));
        result.add(new Abbreviation("IEEE Transactions on Affective Computing","#IEEE_J_AFFC#"));
        result.add(new Abbreviation("IEEE Transactions on Aerospace and Navigational Electronics","#IEEE_J_ANE#"));
        result.add(new Abbreviation("IEEE Computer Architecture Letters","#IEEE_J_CAL#"));
        result.add(new Abbreviation("IEEE Access","#IEEE_O_ACC#"));
        result.add(new Abbreviation("IEEE Transactions on Reliability","#IEEE_J_R#"));
        result.add(new Abbreviation("IEEE Transactions on Neural Systems and Rehabilitation Engineering","#IEEE_J_NSRE#"));
        result.add(new Abbreviation("IEEE RFIC Journal","#IEEE_J_RFIC#"));
        result.add(new Abbreviation("IEEE/ASME Journal of Microelectromechanical Systems","#IEEE_J_MEMS#"));
        result.add(new Abbreviation("IEEE Transactions on Advanced Packaging","#IEEE_J_ADVP#"));
        result.add(new Abbreviation("IEEE Power Electronics Magazine","#IEEE_M_PEL#"));
        result.add(new Abbreviation("China Communications Magazine","#IEEE_M_CHINAC#"));
        result.add(new Abbreviation("IEEE Transactions on Airborne Electronics","#IEEE_J_AIRE#"));
        result.add(new Abbreviation("IEEE RFID Journal","#IEEE_J_RFID#"));
        result.add(new Abbreviation("IEEE Computational Intelligence Magazine","#IEEE_M_CIM#"));
        result.add(new Abbreviation("IEEE Transactions on Industrial Electronics and Control Instrumentation","#IEEE_J_IECI#"));
        result.add(new Abbreviation("IEEE Transactions on Network Science and Engineering","#IEEE_J_NSE#"));
        result.add(new Abbreviation("IEEE Transactions on Cognitive Communications and Networking","#IEEE_J_CCN#"));
        result.add(new Abbreviation("IEEE Communications Letters","#IEEE_J_COML#"));
        result.add(new Abbreviation("IEEE Transactions on Control Systems Technology","#IEEE_J_CST#"));
        result.add(new Abbreviation("IEEE Transactions on Medical Electronics","#IEEE_J_ME#"));
        result.add(new Abbreviation("IEEE Communications Magazine","#IEEE_M_COM#"));
        result.add(new Abbreviation("IEEE Multimedia","#IEEE_M_MM#"));
        result.add(new Abbreviation("IEEE Journal of Product Safety Engineering","#IEEE_J_PSE#"));
        result.add(new Abbreviation("IEEE Transactions on Aerospace and Electronic Systems","#IEEE_J_AES#"));
        result.add(new Abbreviation("IEEE Computational Science and Engineering Magazine","#IEEE_M_CSEM#"));
        result.add(new Abbreviation("IEEE Transactions on Cybernetics","#IEEE_J_CYB#"));
        result.add(new Abbreviation("IEEE Transactions on Parts, Hybrids and Packaging","#IEEE_J_PHP#"));
        result.add(new Abbreviation("IEEE Transactions on Big Data","#IEEE_J_BD#"));
        result.add(new Abbreviation("IEEE Transactions on Molecular, Biological and Multi-Scale Communications","#IEEE_J_MBSC#"));
        result.add(new Abbreviation("IEEE Internet Computing","#IEEE_M_IC#"));
        result.add(new Abbreviation("IEEE Sustainable Computing","#IEEE_J_SUSC#"));
        result.add(new Abbreviation("IEEE Systems Journal","#IEEE_J_SYST#"));
        result.add(new Abbreviation("IEEE/ACM Transactions on Audio, Speech, and Language Processing","#IEEE_J_ASLP#"));
        result.add(new Abbreviation("IEEE Journal of Solid-State Circuits","#IEEE_J_JSSC#"));
        result.add(new Abbreviation("IEEE/OSA Journal of Lightwave Technology","#IEEE_J_JLT#"));
        result.add(new Abbreviation("IEEE Journal on Selected Areas in Communications","#IEEE_J_JSAC#"));
        result.add(new Abbreviation("IEEE Annals of the History of Computing","#IEEE_M_HIST#"));
        result.add(new Abbreviation("IEEE Electromagnetic Compatibility Magazine","#IEEE_M_EMC#"));
        result.add(new Abbreviation("IEEE Transactions on Cloud Computing","#IEEE_J_CC#"));
        result.add(new Abbreviation("IEEE Journal of Photovoltaics","#IEEE_J_PHOT#"));
        result.add(new Abbreviation("IEEE Transactions on Ultrasonics Engineering","#IEEE_J_UE#"));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology B: Advanced Packaging","#IEEE_J_CPMTB#"));
        result.add(new Abbreviation("Canadian Journal of Electrical and Computer Engineering","#IEEE_J_CJECE#"));
        result.add(new Abbreviation("IEEE Industrial Electronics Magazine","#IEEE_M_IE#"));
        result.add(new Abbreviation("IEEE/ASME Transactions on Mechatronics","#IEEE_J_MECH#"));
        result.add(new Abbreviation("IEEE Transactions on Power Systems","#IEEE_J_PWRS#"));
        result.add(new Abbreviation("IEEE Magnetics Letters","#IEEE_J_MAGL#"));
        result.add(new Abbreviation("IEEE Distributed Systems Online","#IEEE_O_DSO#"));
        result.add(new Abbreviation("IEEE Transactions on Broadcasting","#IEEE_J_BC#"));
        result.add(new Abbreviation("IEEE Transactions on Audio, Speech, and Language Processing","#IEEE_J_ASL#"));
        result.add(new Abbreviation("IEEE Transactions on Communication Technology","#IEEE_J_COMT#"));
        result.add(new Abbreviation("IEEE Transactions on Power Delivery","#IEEE_J_PWRD#"));
        result.add(new Abbreviation("IEEE Electrification Magazine","#IEEE_M_ETF#"));
        result.add(new Abbreviation("IEEE Transactions on Vehicular Technology","#IEEE_J_VT#"));
        result.add(new Abbreviation("IEEE Circuits and Systems Magazine","#IEEE_M_CAS#"));
        result.add(new Abbreviation("IEEE Micro","#IEEE_M_MICRO#"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics","#IEEE_J_SMC#"));
        result.add(new Abbreviation("IEEE Transactions on Circuit Theory","#IEEE_J_CT#"));
        result.add(new Abbreviation("IEEE Transactions on Broadcast and Television Receivers","#IEEE_J_BCTV#"));
        result.add(new Abbreviation("IEEE Transactions on Components, Hybrids and Manufacturing Technology","#IEEE_J_CHMT#"));
        result.add(new Abbreviation("IEEE Signal Processing Magazine","#IEEE_M_SP#"));
        result.add(new Abbreviation("IEEE Potentials","#IEEE_M_POT#"));
        result.add(new Abbreviation("IEEE Transactions on Speech and Audio Processing","#IEEE_J_SAP#"));
        result.add(new Abbreviation("IEEE Photonics Technology Letters","#IEEE_J_PTL#"));
        result.add(new Abbreviation("IEEE Transactions on Audio","#IEEE_J_AU#"));
        result.add(new Abbreviation("IEEE Transactions on Human-Machine Systems","#IEEE_J_HMS#"));
        result.add(new Abbreviation("IEEE Transactions on Device and Materials Reliability","#IEEE_J_DMR#"));
        result.add(new Abbreviation("IEEE Intelligent Systems","#IEEE_M_IS#"));
        result.add(new Abbreviation("IEEE Transactions on Information Theory","#IEEE_J_IT#"));
        result.add(new Abbreviation("IEEE Transactions on Information Technology in Biomedicine","#IEEE_J_ITBM#"));
        result.add(new Abbreviation("IEEE Transactions on Sonics and Ultrasonics","#IEEE_J_SU#"));
        result.add(new Abbreviation("IEEE Transactions on Components and Packaging Technologies","#IEEE_J_CAPTS#"));
        result.add(new Abbreviation("IEEE Transactions on Evolutionary Computation","#IEEE_J_EVC#"));
        result.add(new Abbreviation("IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing","#IEEE_J_STARS#"));
        result.add(new Abbreviation("IEEE Transactions on Instrumentation and Measurement","#IEEE_J_IM#"));
        result.add(new Abbreviation("IEEE Engineering in Medicine and Biology Magazine","#IEEE_M_EMB#"));
        result.add(new Abbreviation("IEEE Transactions on Component Parts","#IEEE_J_CPART#"));
        result.add(new Abbreviation("IEEE Transactions on Computational Social Systems","#IEEE_J_CSS#"));
        result.add(new Abbreviation("IEEE Transactions on Radio Frequency Interference","#IEEE_J_RFI#"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics B: Cybernetics","#IEEE_J_SMCB#"));
        result.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Circuits and Systems","#IEEE_J_ETCAS#"));
        result.add(new Abbreviation("IEEE Antennas and Wireless Propagation Letters","#IEEE_J_AWPL#"));
        result.add(new Abbreviation("IEEE Transactions on Fuzzy Systems","#IEEE_J_FUZZ#"));
        result.add(new Abbreviation("IEEE Transactions on Image Processing","#IEEE_J_IP#"));
        result.add(new Abbreviation("IEEE Journal of Oceanic Engineering","#IEEE_J_OE#"));
        result.add(new Abbreviation("IEEE Transactions on Geoscience Electronics","#IEEE_J_GE#"));
        result.add(new Abbreviation("IEEE Transactions on Signal Processing","#IEEE_J_SP#"));
        result.add(new Abbreviation("IEEE Transactions on Learning Technologies","#IEEE_J_LT#"));

        return result;
    }

    public static List<Abbreviation> getStandardAbbreviations() {
        List<Abbreviation> result = new ArrayList<>(263);

        result.add(new Abbreviation("IEEE Communications Surveys and Tutorials","IEEE Commun. Surveys Tuts."));
        result.add(new Abbreviation("IEEE Computing in Science and Engineering","IEEE Comput. Sci. Eng."));
        result.add(new Abbreviation("IEEE Transactions on Parts, Materials and Packaging","IEEE Trans. Parts, Mater., Packag."));
        result.add(new Abbreviation("IEEE Journal of Optical Communications and Networking","IEEE J. Opt. Commun. Netw."));
        result.add(new Abbreviation("IEEE Expert","IEEE Expert"));
        result.add(new Abbreviation("IEEE Transactions on Engineering Writing and Speech","IEEE Trans. Eng. Writing Speech"));
        result.add(new Abbreviation("IEEE Transactions on Human Factors in Electronics","IEEE Trans. Hum. Factors Electron."));
        result.add(new Abbreviation("IEEE Transactions on Applied Superconductivity","IEEE Trans. Appl. Supercond."));
        result.add(new Abbreviation("IEEE Translation Journal on Magnetics in Japan","IEEE Transl. J. Magn. Jpn."));
        result.add(new Abbreviation("IEEE Security and Privacy","IEEE Security Privacy"));
        result.add(new Abbreviation("IEEE Sensors Journal","IEEE Sensors J."));
        result.add(new Abbreviation("IEEE Transactions on Terahertz Science and Technology","IEEE Trans. THz Sci. Technol."));
        result.add(new Abbreviation("IEEE Pulse","IEEE Pulse"));
        result.add(new Abbreviation("IEEE Circuits and Devices Magazine","IEEE Circuits Devices Mag."));
        result.add(new Abbreviation("IEEE Transactions on Power Electronics","IEEE Trans. Power Electron."));
        result.add(new Abbreviation("IEEE Transactions on Systems Science and Cybernetics","IEEE Trans. Syst. Sci. Cybern."));
        result.add(new Abbreviation("IEEE Solid-State Circuits Magazine","IEEE Solid-State Circuits Mag."));
        result.add(new Abbreviation("IEEE Transactions on Computational Intelligence and AI in Games","IEEE Trans. Comput. Intell. AI in Games"));
        result.add(new Abbreviation("IEEE Transactions on Dielectrics and Electrical Insulation","IEEE Trans. Dielectr. Electr. Insul."));
        result.add(new Abbreviation("IEEE Concurrency","IEEE Concurrency"));
        result.add(new Abbreviation("IEEE Network","IEEE Netw."));
        result.add(new Abbreviation("IEEE Wireless Communications Letters","IEEE Wireless Commun. Lett."));
        result.add(new Abbreviation("IEEE Computer Graphics and Applications","IEEE Comput. Graph. Appl."));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Express Briefs","IEEE Trans. Circuits Syst. II"));
        result.add(new Abbreviation("Computer","Computer"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications","IEEE Trans. Circuits Syst. I"));
        result.add(new Abbreviation("IEEE Transactions on Applications and Industry","IEEE Trans. Appl. Ind."));
        result.add(new Abbreviation("IEEE Transactions on Bio-Medical Engineering","IEEE Trans. Bio-Med. Eng."));
        result.add(new Abbreviation("IEEE Robotics and Automation Magazine","IEEE Robot. Autom. Mag."));
        result.add(new Abbreviation("IEEE Vehicular Technology Magazine","IEEE Veh. Technol. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Professional Communication","IEEE Trans. Prof. Commun."));
        result.add(new Abbreviation("IEEE Transactions on Biomedical Engineering","IEEE Trans. Biomed. Eng."));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology","IEEE Trans. Compon. Packag. Manuf. Technol."));
        result.add(new Abbreviation("IEEE Design & Test","IEEE Des. Test"));
        result.add(new Abbreviation("IEEE Transactions on Pattern Analysis and Machine Intelligence","IEEE Trans. Pattern Anal. Mach. Intell."));
        result.add(new Abbreviation("IEEE Control Systems Magazine","IEEE Control Syst. Mag."));
        result.add(new Abbreviation("IEEE Intelligent Transportation Systems Magazine","IEEE Intell. Transp. Syst. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Industrial Electronics","IEEE Trans. Ind. Electron."));
        result.add(new Abbreviation("IEEE Transactions on NanoBioscience","IEEE Trans. Nanobiosci."));
        result.add(new Abbreviation("IEEE Transactions on Engineering Management","IEEE Trans. Eng. Manag."));
        result.add(new Abbreviation("IEEE ASSP Magazine","IEEE ASSP Mag."));
        result.add(new Abbreviation("IEEE Journal on Multiscale and Multiphysics Computational Techniques","IEEE J. Multiscale and Multiphys. Comput. Techn."));
        result.add(new Abbreviation("IEEE Microwave Magazine","IEEE Microw. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics C: Applications and Reviews","IEEE Trans. Syst., Man, Cybern. C"));
        result.add(new Abbreviation("IEEE Internet of Things Journal","IEEE Internet Things J."));
        result.add(new Abbreviation("IEEE Transactions on Industry Applications","IEEE Trans. Ind. Appl."));
        result.add(new Abbreviation("IEEE Transactions on Magnetics","IEEE Trans. Magn."));
        result.add(new Abbreviation("IEEE Revista Iberoamericana de Technolog'ias del Aprendizaje","IEEE Revista Iberoamericana de Technolog'ias del Aprendizaje"));
        result.add(new Abbreviation("IEEE Power and Energy Technology Systems Journal","IEEE Power Energy Technol. Syst. J."));
        result.add(new Abbreviation("IEEE Transactions on Aerospace","IEEE Trans. Aerosp."));
        result.add(new Abbreviation("IEEE/ACM Transactions on Networking","IEEE/ACM Trans. Netw."));
        result.add(new Abbreviation("IEEE Life Sciences Letters","IEEE Life Sci. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Industrial Informatics","IEEE Trans. Ind. Informat."));
        result.add(new Abbreviation("IEEE IT Professional","IEEE IT Prof."));
        result.add(new Abbreviation("IEEE Transactions on Robotics","IEEE Trans. Robot."));
        result.add(new Abbreviation("IEEE Transactions on Aeronautical and Navigational Electronics","IEEE Trans. Aeronaut. Navig. Electron."));
        result.add(new Abbreviation("IEEE Transactions on Audio and Electroacoustics","IEEE Trans. Audio Electroacoust."));
        result.add(new Abbreviation("IEEE Spectrum","IEEE Spectr."));
        result.add(new Abbreviation("IEEE Wireless Communications","IEEE Wireless Commun."));
        result.add(new Abbreviation("IEEE/OSA Journal of Display Technology","IEEE/OSA J. Display Technol."));
        result.add(new Abbreviation("IEEE Power and Energy Magazine","IEEE Power Energy Mag."));
        result.add(new Abbreviation("IEEE Reviews in Biomedical Engineering","IEEE Rev. Biomed. Eng."));
        result.add(new Abbreviation("IEEE Embedded Systems Letters","IEEE Embedded Syst. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Automatic Control","IEEE Trans. Autom. Control"));
        result.add(new Abbreviation("Proceedings of the IEEE","Proc. IEEE"));
        result.add(new Abbreviation("IEEE Transactions on Education","IEEE Trans. Educ."));
        result.add(new Abbreviation("IEEE Transactions on Information Forensics and Security","IEEE Trans. Inf. Forensics Security"));
        result.add(new Abbreviation("IEEE Transactions on Software Engineering","IEEE Trans. Softw. Eng."));
        result.add(new Abbreviation("IEEE Journal of Electron Devices Society","IEEE J. Electron Devices Soc."));
        result.add(new Abbreviation("IEEE Transactions on Autonomous Mental Development","IEEE Trans. Auton. Mental Develop."));
        result.add(new Abbreviation("IEEE Power Electronics Letters","IEEE Power Electron. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Multi-Scale Computing Systems","IEEE Trans. Multi-Scale Comput. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Knowledge and Data Engineering","IEEE Trans. Knowl. Data Eng."));
        result.add(new Abbreviation("IEEE Transactions on Bio-Medical Electronics","IEEE Trans. Bio-Med. Electron."));
        result.add(new Abbreviation("IEEE Transactions on Energy Conversion","IEEE Trans. Energy Convers."));
        result.add(new Abbreviation("IEEE Journal of Quantum Electronics","IEEE J. Quantum Electron."));
        result.add(new Abbreviation("IEEE Transactions on Antennas and Propagation","IEEE Trans. Antennas Propag."));
        result.add(new Abbreviation("IEEE Transactions on Components and Packaging Technology","IEEE Trans. Compon. Packag. Technol."));
        result.add(new Abbreviation("IEEE Transactions on Intelligent Transportation Systems","IEEE Trans. Intell. Transp. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Smart Grid","IEEE Trans. Smart Grid"));
        result.add(new Abbreviation("IEEE Transactions on Military Electronics","IEEE Trans. Mil. Electron."));
        result.add(new Abbreviation("IEEE Industry Applications Magazine","IEEE Ind. Appl. Mag."));
        result.add(new Abbreviation("Today's Engineer","Today's Engineer"));
        result.add(new Abbreviation("IEEE Transactions on Semiconductor Manufacturing","IEEE Trans. Semicond. Manuf."));
        result.add(new Abbreviation("IEEE/ECS Electrochemical and Solid-State Letters","IEEE/ECS Electrochem. Solid-State Lett."));
        result.add(new Abbreviation("IEEE Photonics Journal","IEEE Photon. J."));
        result.add(new Abbreviation("IEEE Journal of Robotics and Automation","IEEE J. Robot. Autom."));
        result.add(new Abbreviation("IEEE Transactions on Acoustics, Speech, and Signal Processing","IEEE Trans. Acoust., Speech, Signal Process."));
        result.add(new Abbreviation("IEEE Communications Society Magazine","IEEE Commun. Soc. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Nuclear Science","IEEE Trans. Nucl. Sci."));
        result.add(new Abbreviation("IEEE Microwave and Wireless Components Letters","IEEE Microw. Wireless Compon. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Rehabilitation Engineering","IEEE Trans. Rehabil. Eng."));
        result.add(new Abbreviation("IEEE Transactions on Network and Service Management","IEEE Trans. Netw. Service Manag."));
        result.add(new Abbreviation("IEEE Transactions on Intelligent Vehicles","IEEE Trans. Intell. Veh."));
        result.add(new Abbreviation("IEEE Transactions on Parallel and Distributed Systems","IEEE Trans. Parallel Distrib. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Control of Network Systems","IEEE Trans. Control Netw. Syst."));
        result.add(new Abbreviation("IEEE Microwave and Guided Wave Letters","IEEE Microw. Guided Wave Lett."));
        result.add(new Abbreviation("IEEE Transactions on Plasma Science","IEEE Trans. Plasma Sci."));
        result.add(new Abbreviation("IEEE Transactions on Microwave Theory and Techniques","IEEE Trans. Microw. Theory Techn."));
        result.add(new Abbreviation("IEEE Transactions on Electronics Packaging Manufacturing","IEEE Trans. Electron. Packag. Manuf."));
        result.add(new Abbreviation("IEEE Transactions on Man-Machine Systems","IEEE Trans. Man-Mach. Syst."));
        result.add(new Abbreviation("IEEE/ACM Transactions on Computational Biology and Bioinformatics","IEEE/ACM Trans. Comput. Biol. Bioinformatics"));
        result.add(new Abbreviation("IEEE Journal of Translational Engineering in Health and Medicine","IEEE J. Transl. Eng. Health Med."));
        result.add(new Abbreviation("IEEE Transactions on Nanotechnology","IEEE Trans. Nanotechnol."));
        result.add(new Abbreviation("IEEE Transactions on Power Apparatus and Systems","IEEE Trans. Power App. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Services Computing","IEEE Trans. Serv. Comput."));
        result.add(new Abbreviation("IEEE Computer Applications in Power","IEEE Comput. Appl. Power"));
        result.add(new Abbreviation("IEEE Transactions on Electromagnetic Compatibility","IEEE Trans. Electromagn. Compat."));
        result.add(new Abbreviation("IEEE Transactions on Consumer Electronics","IEEE Trans. Consum. Electron."));
        result.add(new Abbreviation("IEEE Electron Device Letters","IEEE Electron Device Lett."));
        result.add(new Abbreviation("IEEE Transactions on Cognitive and Developmental Systems","IEEE Trans. Cogn. Develop. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Transportation Electrification","IEEE Trans. Transport. Electrific."));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology C: Manufacturing","IEEE Trans. Compon., Packag., Manuf. Technol. C"));
        result.add(new Abbreviation("IEEE Design and Test of Computers","IEEE Des. Test. Comput."));
        result.add(new Abbreviation("IEEE Nanotechnology Express","IEEE Nanotechnol. Express"));
        result.add(new Abbreviation("IEEE Journal of Selected Topics in Quantum Electronics","IEEE J. Sel. Topics Quantum Electron."));
        result.add(new Abbreviation("IEEE/CAA Journal of Automatica Sinica","IEEE/CAA J. Autom. Sinica"));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems","IEEE Trans. Circuits Syst."));
        result.add(new Abbreviation("IEEE Transactions on Mobile Computing","IEEE Trans. Mobile Comput."));
        result.add(new Abbreviation("IEEE Transactions on Vehicular Communications","IEEE Trans. Veh. Commun."));
        result.add(new Abbreviation("IEEE Journal of Microelectromechanical Systems","J. Microelectromech. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Electron Devices","IEEE Trans. Electron Devices"));
        result.add(new Abbreviation("IEEE Robotics and Automation Letters","IEEE Robot. Autom. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Communications","IEEE Trans. Commun."));
        result.add(new Abbreviation("IEEE Signal Processing Letters","IEEE Signal Process. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Neural Networks","IEEE Trans. Neural Netw."));
        result.add(new Abbreviation("IEEE Journal of Selected Topics in Signal Processing","IEEE J. Sel. Topics Signal Process."));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems for Video Technology","IEEE Trans. Circuits Syst. Video Technol."));
        result.add(new Abbreviation("IEEE Journal on Technology in Computer Aided Design","IEEE J. Technol. Comput. Aided Design"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics: Systems","IEEE Trans. Syst., Man, Cybern., Syst."));
        result.add(new Abbreviation("IEEE Transactions on Haptics","IEEE Trans. Haptics"));
        result.add(new Abbreviation("IEEE Transactions on Biomedical Circuits and Systems","IEEE Trans. Biomed. Circuits Syst."));
        result.add(new Abbreviation("IEEE Transactions on Electrical Insulation","IEEE Trans. Electr. Insul."));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Regular Papers","IEEE Trans. Circuits Syst. I"));
        result.add(new Abbreviation("IEEE Transactions on Very Large Scale Integration (VLSI) Systems","IEEE Trans. VLSI Syst."));
        result.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Analog and Digital Signal Processing","IEEE Trans. Circuits Syst. II"));
        result.add(new Abbreviation("IEEE/TMS Journal of Electronic Materials","IEEE/TMS J. Electron. Mater."));
        result.add(new Abbreviation("IEEE Power Engineering Review","IEEE Power Eng. Rev."));
        result.add(new Abbreviation("China Communications","China Commun."));
        result.add(new Abbreviation("IEEE Transactions on Ultrasonics, Ferroelectrics, and Frequency Control","IEEE Trans. Ultrason., Ferroelectr., Freq. Control"));
        result.add(new Abbreviation("IEEE Transactions on Industry and General Applications","IEEE Trans. Ind. Gen. Appl."));
        result.add(new Abbreviation("IEEE Aerospace and Electronics Systems Magazine","IEEE Aerosp. Electron. Syst. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Wireless Communications","IEEE Trans. Wireless Commun."));
        result.add(new Abbreviation("IEEE Transactions on Emerging Topics in Computing","IEEE Trans. Emerg. Topics Comput."));
        result.add(new Abbreviation("IEEE Transactions on Robotics and Automation","IEEE Trans. Robot. Autom."));
        result.add(new Abbreviation("IEEE Transactions on Electronic Computers","IEEE Trans. Electron. Comput."));
        result.add(new Abbreviation("IEEE Transactions on Manufacturing Technology","IEEE Trans. Manuf. Technol."));
        result.add(new Abbreviation("IEEE Personal Communications Magazine","IEEE Personal Commun. Mag."));
        result.add(new Abbreviation("IEEE Antennas and Propagation Magazine","IEEE Antennas Propag. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Medical Imaging","IEEE Trans. Med. Imag."));
        result.add(new Abbreviation("IEEE Geoscience and Remote Sensing Letters","IEEE Geosci. Remote Sens. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Multimedia","IEEE Trans. Multimedia"));
        result.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Power Electronics","IEEE Trans. Emerg. Sel. Topics Power Electron."));
        result.add(new Abbreviation("IEEE ElectroTechnology Review","IEEE ElectroTechnol. Rev."));
        result.add(new Abbreviation("IEEE Journal on Exploratory Solid-State Computational Devices and Circuits","IEEE J. Explor. Solid-State Computat. Devices Circuits"));
        result.add(new Abbreviation("IEEE Transactions on Sustainable Energy","IEEE Trans. Sustain. Energy"));
        result.add(new Abbreviation("IEEE Software","IEEE Softw."));
        result.add(new Abbreviation("IEEE Electrical Insulation Magazine","IEEE Electr. Insul. Mag."));
        result.add(new Abbreviation("IEEE Journal of Biomedical and Health Informatics","IEEE J. Biomed. Health Inform."));
        result.add(new Abbreviation("IEEE Transactions on Dependable and Secure Computing","IEEE Trans. Depend. Sec. Comput."));
        result.add(new Abbreviation("IEEE Engineering Management Review","IEEE Eng. Manag. Rev."));
        result.add(new Abbreviation("IEEE Transactions on Geoscience and Remote Sensing","IEEE Trans. Geosci. Remote Sens."));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology A","IEEE Trans. Compon., Packag., Manuf. Technol. A"));
        result.add(new Abbreviation("IEEE Transactions on Visualization and Computer Graphics","IEEE Trans. Vis. Comput. Graphics"));
        result.add(new Abbreviation("IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems","IEEE Trans. Comput.-Aided Design Integr. Circuits Syst."));
        result.add(new Abbreviation("IEEE Systems, Man, and Cybernetics Magazine","IEEE Syst., Man, Cybern. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics A: Systems and Humans","IEEE Trans. Syst., Man, Cybern. A"));
        result.add(new Abbreviation("IEEE Technology and Society Magazine","IEEE Technol. Soc. Mag."));
        result.add(new Abbreviation("IEEE Nanotechnology Magazine","IEEE Nanotechnol. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Automation Science and Engineering","IEEE Trans. Autom. Sci. Eng."));
        result.add(new Abbreviation("IEEE Transactions on Neural Networks and Learning Systems","IEEE Trans. Neural Netw. Learn. Syst."));
        result.add(new Abbreviation("IEEE Instrumentation and Measurement Magazine","IEEE Instrum. Meas. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Signal and Information Processing over Networks","IEEE Trans. Signal Inf. Process. Netw."));
        result.add(new Abbreviation("IEEE Geoscience and Remote Sensing Magazine","IEEE Geosci. Remote Sens. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Computers","IEEE Trans. Comput."));
        result.add(new Abbreviation("IEEE Pervasive Computing","IEEE Pervasive Comput."));
        result.add(new Abbreviation("IEEE Transactions on Affective Computing","IEEE Trans. Affect. Comput."));
        result.add(new Abbreviation("IEEE Transactions on Aerospace and Navigational Electronics","IEEE Trans. Aerosp. Navig. Electron."));
        result.add(new Abbreviation("IEEE Computer Architecture Letters","IEEE Comput. Archit. Lett."));
        result.add(new Abbreviation("IEEE Access","IEEE Access"));
        result.add(new Abbreviation("IEEE Transactions on Reliability","IEEE Trans. Rel."));
        result.add(new Abbreviation("IEEE Transactions on Neural Systems and Rehabilitation Engineering","IEEE Trans. Neural Syst. Rehabil. Eng."));
        result.add(new Abbreviation("IEEE RFIC Journal","IEEE RFIC J."));
        result.add(new Abbreviation("IEEE/ASME Journal of Microelectromechanical Systems","J. Microelectromech. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Advanced Packaging","IEEE Trans. Adv. Packag."));
        result.add(new Abbreviation("IEEE Power Electronics Magazine","IEEE Power Electron. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Airborne Electronics","IEEE Trans. Airborne Electron."));
        result.add(new Abbreviation("IEEE RFID Journal","IEEE RFID J."));
        result.add(new Abbreviation("IEEE Computational Intelligence Magazine","IEEE Comput. Intell. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Industrial Electronics and Control Instrumentation","IEEE Trans. Ind. Electron. Contr. Instrum."));
        result.add(new Abbreviation("IEEE Transactions on Network Science and Engineering","IEEE Trans. Netw. Sci. Eng."));
        result.add(new Abbreviation("IEEE Transactions on Cognitive Communications and Networking","IEEE Trans. on Cogn. Commun. Netw."));
        result.add(new Abbreviation("IEEE Communications Letters","IEEE Commun. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Control Systems Technology","IEEE Trans. Control Syst. Technol."));
        result.add(new Abbreviation("IEEE Transactions on Medical Electronics","IEEE Trans. Med. Electron."));
        result.add(new Abbreviation("IEEE Communications Magazine","IEEE Commun. Mag."));
        result.add(new Abbreviation("IEEE Multimedia","IEEE Multimedia"));
        result.add(new Abbreviation("IEEE Journal of Product Safety Engineering","IEEE J. Product Safety Eng."));
        result.add(new Abbreviation("IEEE Transactions on Aerospace and Electronic Systems","IEEE Trans. Aerosp. Electron. Syst."));
        result.add(new Abbreviation("IEEE Computational Science and Engineering Magazine","IEEE Comput. Sci. Eng. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Cybernetics","IEEE Trans. Cybern."));
        result.add(new Abbreviation("IEEE Transactions on Parts, Hybrids and Packaging","IEEE Trans. Parts, Hybrids, Packag."));
        result.add(new Abbreviation("IEEE Transactions on Big Data","IEEE Trans. Big Data"));
        result.add(new Abbreviation("IEEE Transactions on Molecular, Biological and Multi-Scale Communications","IEEE Trans. Mol. Biol. Multi-Scale Commun."));
        result.add(new Abbreviation("IEEE Internet Computing","IEEE Internet Comput."));
        result.add(new Abbreviation("IEEE Sustainable Computing","IEEE Sustain. Comput."));
        result.add(new Abbreviation("IEEE Systems Journal","IEEE Syst. J."));
        result.add(new Abbreviation("IEEE/ACM Transactions on Audio, Speech, and Language Processing","IEEE/ACM Trans. Audio, Speech, Language Process."));
        result.add(new Abbreviation("IEEE Journal of Solid-State Circuits","IEEE J. Solid-State Circuits"));
        result.add(new Abbreviation("IEEE/OSA Journal of Lightwave Technology","J. Lightw. Technol."));
        result.add(new Abbreviation("IEEE Journal on Selected Areas in Communications","IEEE J. Sel. Areas Commun."));
        result.add(new Abbreviation("IEEE Annals of the History of Computing","IEEE Ann. Hist. Comput."));
        result.add(new Abbreviation("IEEE Electromagnetic Compatibility Magazine","IEEE Electromagn. Compat."));
        result.add(new Abbreviation("IEEE Transactions on Cloud Computing","IEEE Trans. on Cloud Comput."));
        result.add(new Abbreviation("IEEE Journal of Photovoltaics","IEEE J. Photovolt."));
        result.add(new Abbreviation("IEEE Transactions on Ultrasonics Engineering","IEEE Trans. Ultrason. Eng."));
        result.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology B: Advanced Packaging","IEEE Trans. Compon., Packag., Manuf. Technol. B"));
        result.add(new Abbreviation("Canadian Journal of Electrical and Computer Engineering","Canadian J. Elect. Comput. Eng."));
        result.add(new Abbreviation("IEEE Industrial Electronics Magazine","IEEE Ind. Electron. Mag."));
        result.add(new Abbreviation("IEEE/ASME Transactions on Mechatronics","IEEE/ASME Trans. Mechatronics"));
        result.add(new Abbreviation("IEEE Transactions on Power Systems","IEEE Trans. Power Syst."));
        result.add(new Abbreviation("IEEE Magnetics Letters","IEEE Magn. Lett."));
        result.add(new Abbreviation("IEEE Distributed Systems Online","IEEE Distrib. Syst. Online"));
        result.add(new Abbreviation("IEEE Transactions on Broadcasting","IEEE Trans. Broadcast."));
        result.add(new Abbreviation("IEEE Transactions on Audio, Speech, and Language Processing","IEEE Audio, Speech, Language Process."));
        result.add(new Abbreviation("IEEE Transactions on Communication Technology","IEEE Trans. Commun. Technol."));
        result.add(new Abbreviation("IEEE Transactions on Power Delivery","IEEE Trans. Power Del."));
        result.add(new Abbreviation("IEEE Electrification Magazine","IEEE Electrific. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Vehicular Technology","IEEE Trans. Veh. Technol."));
        result.add(new Abbreviation("IEEE Circuits and Systems Magazine","IEEE Circuits Syst. Mag."));
        result.add(new Abbreviation("IEEE Micro","IEEE Micro"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics","IEEE Trans. Syst., Man, Cybern."));
        result.add(new Abbreviation("IEEE Transactions on Circuit Theory","IEEE Trans. Circuit Theory"));
        result.add(new Abbreviation("IEEE Transactions on Broadcast and Television Receivers","IEEE Trans. Broadcast Television Receivers"));
        result.add(new Abbreviation("IEEE Transactions on Components, Hybrids and Manufacturing Technology","IEEE Trans. Compon., Hybrids, Manuf. Technol."));
        result.add(new Abbreviation("IEEE Signal Processing Magazine","IEEE Signal Process. Mag."));
        result.add(new Abbreviation("IEEE Potentials","IEEE Potentials"));
        result.add(new Abbreviation("IEEE Transactions on Speech and Audio Processing","IEEE Trans. Speech Audio Process."));
        result.add(new Abbreviation("IEEE Photonics Technology Letters","IEEE Photon. Technol. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Audio","IEEE Trans. Audio"));
        result.add(new Abbreviation("IEEE Transactions on Human-Machine Systems","IEEE Trans. Human-Mach. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Device and Materials Reliability","IEEE Trans. Device Mater. Rel."));
        result.add(new Abbreviation("IEEE Intelligent Systems","IEEE Intell. Syst."));
        result.add(new Abbreviation("IEEE Transactions on Information Theory","IEEE Trans. Inf. Theory"));
        result.add(new Abbreviation("IEEE Transactions on Information Technology in Biomedicine","IEEE Trans. Inf. Technol. Biomed."));
        result.add(new Abbreviation("IEEE Transactions on Sonics and Ultrasonics","IEEE Trans. Sonics Ultrason."));
        result.add(new Abbreviation("IEEE Transactions on Components and Packaging Technologies","IEEE Trans. Compon. Packag. Technol."));
        result.add(new Abbreviation("IEEE Transactions on Evolutionary Computation","IEEE Trans. Evol. Comput."));
        result.add(new Abbreviation("IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing","IEEE J. Sel. Topics Appl. Earth Observ. Remote Sens."));
        result.add(new Abbreviation("IEEE Transactions on Instrumentation and Measurement","IEEE Trans. Instrum. Meas."));
        result.add(new Abbreviation("IEEE Engineering in Medicine and Biology Magazine","IEEE Eng. Med. Biol. Mag."));
        result.add(new Abbreviation("IEEE Transactions on Component Parts","IEEE Trans. Compon. Parts"));
        result.add(new Abbreviation("IEEE Transactions on Computational Social Systems","IEEE Trans. Comput. Social Syst."));
        result.add(new Abbreviation("IEEE Transactions on Radio Frequency Interference","IEEE Trans. Radio Freq. Interference"));
        result.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics B: Cybernetics","IEEE Trans. Syst., Man, Cybern. B"));
        result.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Circuits and Systems","IEEE Trans. Emerg. Sel. Topics Circuits Syst."));
        result.add(new Abbreviation("IEEE Antennas and Wireless Propagation Letters","IEEE Antennas Wireless Propag. Lett."));
        result.add(new Abbreviation("IEEE Transactions on Fuzzy Systems","IEEE Trans. Fuzzy Syst."));
        result.add(new Abbreviation("IEEE Transactions on Image Processing","IEEE Trans. Image Process."));
        result.add(new Abbreviation("IEEE Journal of Oceanic Engineering","IEEE J. Ocean. Eng."));
        result.add(new Abbreviation("IEEE Transactions on Geoscience Electronics","IEEE Trans. Geosci. Electron."));
        result.add(new Abbreviation("IEEE Transactions on Signal Processing","IEEE Trans. Signal Process."));
        result.add(new Abbreviation("IEEE Transactions on Learning Technologies","IEEE Trans. Learn. Technol."));

        return result;
    }
}
