package org.jabref.logic.journals;

import java.util.ArrayList;
import java.util.List;

public class IeeeAbbreviationLists {

    private static final List<Abbreviation> officialIeeeList = new ArrayList<>(263);

    private static final List<Abbreviation> standardIeeeList = new ArrayList<>(263);

    static {
        officialIeeeList.add(new Abbreviation("IEEE Communications Surveys and Tutorials", "#IEEE_O_CSTO#"));
        officialIeeeList.add(new Abbreviation("IEEE Computing in Science and Engineering", "#IEEE_M_CSE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Parts, Materials and Packaging", "#IEEE_J_PMP#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Optical Communications and Networking", "#IEEE_J_OCN#"));
        officialIeeeList.add(new Abbreviation("IEEE Expert", "#IEEE_M_EXP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Engineering Writing and Speech", "#IEEE_J_EWS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Human Factors in Electronics", "#IEEE_J_HFE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Applied Superconductivity", "#IEEE_J_ASC#"));
        officialIeeeList.add(new Abbreviation("IEEE Translation Journal on Magnetics in Japan", "#IEEE_J_TJMJ#"));
        officialIeeeList.add(new Abbreviation("IEEE Security and Privacy", "#IEEE_M_SAP#"));
        officialIeeeList.add(new Abbreviation("IEEE Sensors Journal", "#IEEE_J_SENSOR#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Terahertz Science and Technology", "#IEEE_J_TTHZ#"));
        officialIeeeList.add(new Abbreviation("IEEE Pulse", "#IEEE_M_PULSE#"));
        officialIeeeList.add(new Abbreviation("IEEE Circuits and Devices Magazine", "#IEEE_M_CD#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Power Electronics", "#IEEE_J_PWRE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Systems Science and Cybernetics", "#IEEE_J_SSC#"));
        officialIeeeList.add(new Abbreviation("IEEE Solid-State Circuits Magazine", "#IEEE_M_SSC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Computational Intelligence and AI in Games", "#IEEE_J_CIAIG#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Dielectrics and Electrical Insulation", "#IEEE_J_DEI#"));
        officialIeeeList.add(new Abbreviation("IEEE Concurrency", "#IEEE_M_CONC#"));
        officialIeeeList.add(new Abbreviation("IEEE Network", "#IEEE_M_NET#"));
        officialIeeeList.add(new Abbreviation("IEEE Wireless Communications Letters", "#IEEE_J_WCOML#"));
        officialIeeeList.add(new Abbreviation("IEEE Computer Graphics and Applications", "#IEEE_M_CGA#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Express Briefs", "#IEEE_J_CASII_EB#"));
        officialIeeeList.add(new Abbreviation("Computer", "#IEEE_M_C#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications", "#IEEE_J_CASI#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Applications and Industry", "#IEEE_J_APPIND#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Bio-Medical Engineering", "#IEEE_J_B-ME#"));
        officialIeeeList.add(new Abbreviation("IEEE Robotics and Automation Magazine", "#IEEE_M_RA#"));
        officialIeeeList.add(new Abbreviation("IEEE Vehicular Technology Magazine", "#IEEE_M_VT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Professional Communication", "#IEEE_J_PC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Biomedical Engineering", "#IEEE_J_BME#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology", "#IEEE_J_CPMT#"));
        officialIeeeList.add(new Abbreviation("IEEE Design & Test", "#IEEE_M_DT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Pattern Analysis and Machine Intelligence", "#IEEE_J_PAMI#"));
        officialIeeeList.add(new Abbreviation("IEEE Control Systems Magazine", "#IEEE_M_CS#"));
        officialIeeeList.add(new Abbreviation("IEEE Intelligent Transportation Systems Magazine", "#IEEE_M_ITS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Industrial Electronics", "#IEEE_J_IE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on NanoBioscience", "#IEEE_J_NB#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Engineering Management", "#IEEE_J_EM#"));
        officialIeeeList.add(new Abbreviation("IEEE ASSP Magazine", "#IEEE_M_ASSP#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal on Multiscale and Multiphysics Computational Techniques", "#IEEE_J_MMCT#"));
        officialIeeeList.add(new Abbreviation("IEEE Microwave Magazine", "#IEEE_M_MW#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics C: Applications and Reviews", "#IEEE_J_SMCC#"));
        officialIeeeList.add(new Abbreviation("IEEE Internet of Things Journal", "#IEEE_J_IOT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Industry Applications", "#IEEE_J_IA#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Magnetics", "#IEEE_J_MAG#"));
        officialIeeeList.add(new Abbreviation("IEEE Revista Iberoamericana de Technolog'ias del Aprendizaje", "#IEEE_J_RITA#"));
        officialIeeeList.add(new Abbreviation("IEEE Power and Energy Technology Systems Journal", "#IEEE_J_PETS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Aerospace", "#IEEE_J_AS#"));
        officialIeeeList.add(new Abbreviation("IEEE/ACM Transactions on Networking", "#IEEE_J_NET#"));
        officialIeeeList.add(new Abbreviation("IEEE Life Sciences Letters", "#IEEE_J_LS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Industrial Informatics", "#IEEE_J_IINF#"));
        officialIeeeList.add(new Abbreviation("IEEE IT Professional", "#IEEE_M_ITP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Robotics", "#IEEE_J_RO#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Aeronautical and Navigational Electronics", "#IEEE_J_ANNE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Audio and Electroacoustics", "#IEEE_J_AUEA#"));
        officialIeeeList.add(new Abbreviation("IEEE Spectrum", "#IEEE_M_SPECT#"));
        officialIeeeList.add(new Abbreviation("IEEE Wireless Communications", "#IEEE_M_WC#"));
        officialIeeeList.add(new Abbreviation("IEEE/OSA Journal of Display Technology", "#IEEE_J_JDT#"));
        officialIeeeList.add(new Abbreviation("IEEE Power and Energy Magazine", "#IEEE_M_PE#"));
        officialIeeeList.add(new Abbreviation("IEEE Reviews in Biomedical Engineering", "#IEEE_J_RBME#"));
        officialIeeeList.add(new Abbreviation("IEEE Embedded Systems Letters", "#IEEE_J_ES#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Automatic Control", "#IEEE_J_AC#"));
        officialIeeeList.add(new Abbreviation("Proceedings of the IEEE", "#IEEE_J_PROC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Education", "#IEEE_J_EDU#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Information Forensics and Security", "#IEEE_J_IFS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Software Engineering", "#IEEE_J_SE#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Electron Devices Society", "#IEEE_J_EDS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Autonomous Mental Development", "#IEEE_J_AMD#"));
        officialIeeeList.add(new Abbreviation("IEEE Power Electronics Letters", "#IEEE_J_PEL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Multi-Scale Computing Systems", "#IEEE_J_MSCS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Knowledge and Data Engineering", "#IEEE_J_KDE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Bio-Medical Electronics", "#IEEE_J_BMELC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Energy Conversion", "#IEEE_J_EC#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Quantum Electronics", "#IEEE_J_JQE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Antennas and Propagation", "#IEEE_J_AP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Components and Packaging Technology", "#IEEE_J_CAPT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Intelligent Transportation Systems", "#IEEE_J_ITS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Smart Grid", "#IEEE_J_SG#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Military Electronics", "#IEEE_J_MIL#"));
        officialIeeeList.add(new Abbreviation("IEEE Industry Applications Magazine", "#IEEE_M_IA#"));
        officialIeeeList.add(new Abbreviation("Today's Engineer", "#IEEE_M_TODAY#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Semiconductor Manufacturing", "#IEEE_J_SM#"));
        officialIeeeList.add(new Abbreviation("IEEE/ECS Electrochemical and Solid-State Letters", "#IEEE_J_ESSL#"));
        officialIeeeList.add(new Abbreviation("IEEE Photonics Journal", "#IEEE_J_PJ#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Robotics and Automation", "#IEEE_J_JRA#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Acoustics, Speech, and Signal Processing", "#IEEE_J_ASSP#"));
        officialIeeeList.add(new Abbreviation("IEEE Communications Society Magazine", "#IEEE_M_COMSOC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Nuclear Science", "#IEEE_J_NS#"));
        officialIeeeList.add(new Abbreviation("IEEE Microwave and Wireless Components Letters", "#IEEE_J_MWCL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Rehabilitation Engineering", "#IEEE_J_RE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Network and Service Management", "#IEEE_J_NSM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Intelligent Vehicles", "#IEEE_J_IV#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Parallel and Distributed Systems", "#IEEE_J_PDS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Control of Network Systems", "#IEEE_J_CNS#"));
        officialIeeeList.add(new Abbreviation("IEEE Microwave and Guided Wave Letters", "#IEEE_J_MGWL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Plasma Science", "#IEEE_J_PS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Microwave Theory and Techniques", "#IEEE_J_MTT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Electronics Packaging Manufacturing", "#IEEE_J_EPM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Man-Machine Systems", "#IEEE_J_MMS#"));
        officialIeeeList.add(new Abbreviation("IEEE/ACM Transactions on Computational Biology and Bioinformatics", "#IEEE_J_CBB#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Translational Engineering in Health and Medicine", "#IEEE_J_TEHM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Nanotechnology", "#IEEE_J_NANO#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Power Apparatus and Systems", "#IEEE_J_PWRAS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Services Computing", "#IEEE_J_SC#"));
        officialIeeeList.add(new Abbreviation("IEEE Computer Applications in Power", "#IEEE_M_CAP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Electromagnetic Compatibility", "#IEEE_J_EMC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Consumer Electronics", "#IEEE_J_CE#"));
        officialIeeeList.add(new Abbreviation("IEEE Electron Device Letters", "#IEEE_J_EDL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Cognitive and Developmental Systems", "#IEEE_J_CDS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Transportation Electrification", "#IEEE_J_TTE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology C: Manufacturing", "#IEEE_J_CPMTC#"));
        officialIeeeList.add(new Abbreviation("IEEE Design and Test of Computers", "#IEEE_M_DTC#"));
        officialIeeeList.add(new Abbreviation("IEEE Nanotechnology Express", "#IEEE_J_ENANO#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Selected Topics in Quantum Electronics", "#IEEE_J_JSTQE#"));
        officialIeeeList.add(new Abbreviation("IEEE/CAA Journal of Automatica Sinica", "#IEEE_J_JAS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems", "#IEEE_J_CAS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Mobile Computing", "#IEEE_J_MC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Vehicular Communications", "#IEEE_J_VC#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Microelectromechanical Systems", "#IEEE_J_MEMSI#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Electron Devices", "#IEEE_J_ED#"));
        officialIeeeList.add(new Abbreviation("IEEE Robotics and Automation Letters", "#IEEE_J_RAL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Communications", "#IEEE_J_COM#"));
        officialIeeeList.add(new Abbreviation("IEEE Signal Processing Letters", "#IEEE_J_SPL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Neural Networks", "#IEEE_J_NN#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Selected Topics in Signal Processing", "#IEEE_J_STSP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems for Video Technology", "#IEEE_J_CASVT#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal on Technology in Computer Aided Design", "#IEEE_J_TCAD#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics: Systems", "#IEEE_J_SMCS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Haptics", "#IEEE_J_H#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Biomedical Circuits and Systems", "#IEEE_J_BCAS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Electrical Insulation", "#IEEE_J_EI#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Regular Papers", "#IEEE_J_CASI_RP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Very Large Scale Integration (VLSI) Systems", "#IEEE_J_VLSI#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Analog and Digital Signal Processing", "#IEEE_J_CASII#"));
        officialIeeeList.add(new Abbreviation("IEEE/TMS Journal of Electronic Materials", "#IEEE_J_JEM#"));
        officialIeeeList.add(new Abbreviation("IEEE Power Engineering Review", "#IEEE_M_PER#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Ultrasonics, Ferroelectrics, and Frequency Control", "#IEEE_J_UFFC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Industry and General Applications", "#IEEE_J_IGA#"));
        officialIeeeList.add(new Abbreviation("IEEE Aerospace and Electronics Systems Magazine", "#IEEE_M_AES#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Wireless Communications", "#IEEE_J_WCOM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Emerging Topics in Computing", "#IEEE_J_ETC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Robotics and Automation", "#IEEE_J_RA#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Electronic Computers", "#IEEE_J_ECOMP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Manufacturing Technology", "#IEEE_J_MFT#"));
        officialIeeeList.add(new Abbreviation("IEEE Personal Communications Magazine", "#IEEE_M_PCOM#"));
        officialIeeeList.add(new Abbreviation("IEEE Antennas and Propagation Magazine", "#IEEE_M_AP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Medical Imaging", "#IEEE_J_MI#"));
        officialIeeeList.add(new Abbreviation("IEEE Geoscience and Remote Sensing Letters", "#IEEE_J_GRSL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Multimedia", "#IEEE_J_MM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Power Electronics", "#IEEE_J_ESTPE#"));
        officialIeeeList.add(new Abbreviation("IEEE ElectroTechnology Review", "#IEEE_M_ETR#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal on Exploratory Solid-State Computational Devices and Circuits", "#IEEE_J_XCDC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Sustainable Energy", "#IEEE_J_STE#"));
        officialIeeeList.add(new Abbreviation("IEEE Software", "#IEEE_M_S#"));
        officialIeeeList.add(new Abbreviation("IEEE Electrical Insulation Magazine", "#IEEE_M_EI#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Biomedical and Health Informatics", "#IEEE_J_BHI#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Dependable and Secure Computing", "#IEEE_J_DSC#"));
        officialIeeeList.add(new Abbreviation("IEEE Engineering Management Review", "#IEEE_M_EMR#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Geoscience and Remote Sensing", "#IEEE_J_GRS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology A", "#IEEE_J_CPMTA#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Visualization and Computer Graphics", "#IEEE_J_VCG#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems", "#IEEE_J_CAD#"));
        officialIeeeList.add(new Abbreviation("IEEE Systems, Man, and Cybernetics Magazine", "#IEEE_M_SMC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics A: Systems and Humans", "#IEEE_J_SMCA#"));
        officialIeeeList.add(new Abbreviation("IEEE Technology and Society Magazine", "#IEEE_M_TS#"));
        officialIeeeList.add(new Abbreviation("IEEE Nanotechnology Magazine", "#IEEE_M_NANO#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Automation Science and Engineering", "#IEEE_J_ASE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Neural Networks and Learning Systems", "#IEEE_J_NNLS#"));
        officialIeeeList.add(new Abbreviation("IEEE Instrumentation and Measurement Magazine", "#IEEE_M_IM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Signal and Information Processing over Networks", "#IEEE_J_SIPN#"));
        officialIeeeList.add(new Abbreviation("IEEE Geoscience and Remote Sensing Magazine", "#IEEE_M_GRS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Computers", "#IEEE_J_C#"));
        officialIeeeList.add(new Abbreviation("IEEE Pervasive Computing", "#IEEE_M_PVC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Affective Computing", "#IEEE_J_AFFC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Aerospace and Navigational Electronics", "#IEEE_J_ANE#"));
        officialIeeeList.add(new Abbreviation("IEEE Computer Architecture Letters", "#IEEE_J_CAL#"));
        officialIeeeList.add(new Abbreviation("IEEE Access", "#IEEE_O_ACC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Reliability", "#IEEE_J_R#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Neural Systems and Rehabilitation Engineering", "#IEEE_J_NSRE#"));
        officialIeeeList.add(new Abbreviation("IEEE RFIC Journal", "#IEEE_J_RFIC#"));
        officialIeeeList.add(new Abbreviation("IEEE/ASME Journal of Microelectromechanical Systems", "#IEEE_J_MEMS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Advanced Packaging", "#IEEE_J_ADVP#"));
        officialIeeeList.add(new Abbreviation("IEEE Power Electronics Magazine", "#IEEE_M_PEL#"));
        officialIeeeList.add(new Abbreviation("China Communications Magazine", "#IEEE_M_CHINAC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Airborne Electronics", "#IEEE_J_AIRE#"));
        officialIeeeList.add(new Abbreviation("IEEE RFID Journal", "#IEEE_J_RFID#"));
        officialIeeeList.add(new Abbreviation("IEEE Computational Intelligence Magazine", "#IEEE_M_CIM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Industrial Electronics and Control Instrumentation", "#IEEE_J_IECI#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Network Science and Engineering", "#IEEE_J_NSE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Cognitive Communications and Networking", "#IEEE_J_CCN#"));
        officialIeeeList.add(new Abbreviation("IEEE Communications Letters", "#IEEE_J_COML#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Control Systems Technology", "#IEEE_J_CST#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Medical Electronics", "#IEEE_J_ME#"));
        officialIeeeList.add(new Abbreviation("IEEE Communications Magazine", "#IEEE_M_COM#"));
        officialIeeeList.add(new Abbreviation("IEEE Multimedia", "#IEEE_M_MM#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Product Safety Engineering", "#IEEE_J_PSE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Aerospace and Electronic Systems", "#IEEE_J_AES#"));
        officialIeeeList.add(new Abbreviation("IEEE Computational Science and Engineering Magazine", "#IEEE_M_CSEM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Cybernetics", "#IEEE_J_CYB#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Parts, Hybrids and Packaging", "#IEEE_J_PHP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Big Data", "#IEEE_J_BD#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Molecular, Biological and Multi-Scale Communications", "#IEEE_J_MBSC#"));
        officialIeeeList.add(new Abbreviation("IEEE Internet Computing", "#IEEE_M_IC#"));
        officialIeeeList.add(new Abbreviation("IEEE Sustainable Computing", "#IEEE_J_SUSC#"));
        officialIeeeList.add(new Abbreviation("IEEE Systems Journal", "#IEEE_J_SYST#"));
        officialIeeeList.add(new Abbreviation("IEEE/ACM Transactions on Audio, Speech, and Language Processing", "#IEEE_J_ASLP#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Solid-State Circuits", "#IEEE_J_JSSC#"));
        officialIeeeList.add(new Abbreviation("IEEE/OSA Journal of Lightwave Technology", "#IEEE_J_JLT#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal on Selected Areas in Communications", "#IEEE_J_JSAC#"));
        officialIeeeList.add(new Abbreviation("IEEE Annals of the History of Computing", "#IEEE_M_HIST#"));
        officialIeeeList.add(new Abbreviation("IEEE Electromagnetic Compatibility Magazine", "#IEEE_M_EMC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Cloud Computing", "#IEEE_J_CC#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Photovoltaics", "#IEEE_J_PHOT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Ultrasonics Engineering", "#IEEE_J_UE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology B: Advanced Packaging", "#IEEE_J_CPMTB#"));
        officialIeeeList.add(new Abbreviation("Canadian Journal of Electrical and Computer Engineering", "#IEEE_J_CJECE#"));
        officialIeeeList.add(new Abbreviation("IEEE Industrial Electronics Magazine", "#IEEE_M_IE#"));
        officialIeeeList.add(new Abbreviation("IEEE/ASME Transactions on Mechatronics", "#IEEE_J_MECH#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Power Systems", "#IEEE_J_PWRS#"));
        officialIeeeList.add(new Abbreviation("IEEE Magnetics Letters", "#IEEE_J_MAGL#"));
        officialIeeeList.add(new Abbreviation("IEEE Distributed Systems Online", "#IEEE_O_DSO#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Broadcasting", "#IEEE_J_BC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Audio, Speech, and Language Processing", "#IEEE_J_ASL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Communication Technology", "#IEEE_J_COMT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Power Delivery", "#IEEE_J_PWRD#"));
        officialIeeeList.add(new Abbreviation("IEEE Electrification Magazine", "#IEEE_M_ETF#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Vehicular Technology", "#IEEE_J_VT#"));
        officialIeeeList.add(new Abbreviation("IEEE Circuits and Systems Magazine", "#IEEE_M_CAS#"));
        officialIeeeList.add(new Abbreviation("IEEE Micro", "#IEEE_M_MICRO#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics", "#IEEE_J_SMC#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Circuit Theory", "#IEEE_J_CT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Broadcast and Television Receivers", "#IEEE_J_BCTV#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Components, Hybrids and Manufacturing Technology", "#IEEE_J_CHMT#"));
        officialIeeeList.add(new Abbreviation("IEEE Signal Processing Magazine", "#IEEE_M_SP#"));
        officialIeeeList.add(new Abbreviation("IEEE Potentials", "#IEEE_M_POT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Speech and Audio Processing", "#IEEE_J_SAP#"));
        officialIeeeList.add(new Abbreviation("IEEE Photonics Technology Letters", "#IEEE_J_PTL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Audio", "#IEEE_J_AU#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Human-Machine Systems", "#IEEE_J_HMS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Device and Materials Reliability", "#IEEE_J_DMR#"));
        officialIeeeList.add(new Abbreviation("IEEE Intelligent Systems", "#IEEE_M_IS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Information Theory", "#IEEE_J_IT#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Information Technology in Biomedicine", "#IEEE_J_ITBM#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Sonics and Ultrasonics", "#IEEE_J_SU#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Components and Packaging Technologies", "#IEEE_J_CAPTS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Evolutionary Computation", "#IEEE_J_EVC#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing", "#IEEE_J_STARS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Instrumentation and Measurement", "#IEEE_J_IM#"));
        officialIeeeList.add(new Abbreviation("IEEE Engineering in Medicine and Biology Magazine", "#IEEE_M_EMB#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Component Parts", "#IEEE_J_CPART#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Computational Social Systems", "#IEEE_J_CSS#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Radio Frequency Interference", "#IEEE_J_RFI#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics B: Cybernetics", "#IEEE_J_SMCB#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Circuits and Systems", "#IEEE_J_ETCAS#"));
        officialIeeeList.add(new Abbreviation("IEEE Antennas and Wireless Propagation Letters", "#IEEE_J_AWPL#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Fuzzy Systems", "#IEEE_J_FUZZ#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Image Processing", "#IEEE_J_IP#"));
        officialIeeeList.add(new Abbreviation("IEEE Journal of Oceanic Engineering", "#IEEE_J_OE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Geoscience Electronics", "#IEEE_J_GE#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Signal Processing", "#IEEE_J_SP#"));
        officialIeeeList.add(new Abbreviation("IEEE Transactions on Learning Technologies", "#IEEE_J_LT#"));
        
        standardIeeeList.add(new Abbreviation("IEEE Communications Surveys and Tutorials", "IEEE Commun. Surveys Tuts."));
        standardIeeeList.add(new Abbreviation("IEEE Computing in Science and Engineering", "IEEE Comput. Sci. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Parts, Materials and Packaging", "IEEE Trans. Parts, Mater., Packag."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Optical Communications and Networking", "IEEE J. Opt. Commun. Netw."));
        standardIeeeList.add(new Abbreviation("IEEE Expert", "IEEE Expert"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Engineering Writing and Speech", "IEEE Trans. Eng. Writing Speech"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Human Factors in Electronics", "IEEE Trans. Hum. Factors Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Applied Superconductivity", "IEEE Trans. Appl. Supercond."));
        standardIeeeList.add(new Abbreviation("IEEE Translation Journal on Magnetics in Japan", "IEEE Transl. J. Magn. Jpn."));
        standardIeeeList.add(new Abbreviation("IEEE Security and Privacy", "IEEE Security Privacy"));
        standardIeeeList.add(new Abbreviation("IEEE Sensors Journal", "IEEE Sensors J."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Terahertz Science and Technology", "IEEE Trans. THz Sci. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Pulse", "IEEE Pulse"));
        standardIeeeList.add(new Abbreviation("IEEE Circuits and Devices Magazine", "IEEE Circuits Devices Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Power Electronics", "IEEE Trans. Power Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Systems Science and Cybernetics", "IEEE Trans. Syst. Sci. Cybern."));
        standardIeeeList.add(new Abbreviation("IEEE Solid-State Circuits Magazine", "IEEE Solid-State Circuits Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Computational Intelligence and AI in Games", "IEEE Trans. Comput. Intell. AI in Games"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Dielectrics and Electrical Insulation", "IEEE Trans. Dielectr. Electr. Insul."));
        standardIeeeList.add(new Abbreviation("IEEE Concurrency", "IEEE Concurrency"));
        standardIeeeList.add(new Abbreviation("IEEE Network", "IEEE Netw."));
        standardIeeeList.add(new Abbreviation("IEEE Wireless Communications Letters", "IEEE Wireless Commun. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Computer Graphics and Applications", "IEEE Comput. Graph. Appl."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Express Briefs", "IEEE Trans. Circuits Syst. II"));
        standardIeeeList.add(new Abbreviation("Computer", "Computer"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Fundamental Theory and Applications", "IEEE Trans. Circuits Syst. I"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Applications and Industry", "IEEE Trans. Appl. Ind."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Bio-Medical Engineering", "IEEE Trans. Bio-Med. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Robotics and Automation Magazine", "IEEE Robot. Autom. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Vehicular Technology Magazine", "IEEE Veh. Technol. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Professional Communication", "IEEE Trans. Prof. Commun."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Biomedical Engineering", "IEEE Trans. Biomed. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology", "IEEE Trans. Compon. Packag. Manuf. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Design & Test", "IEEE Des. Test"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Pattern Analysis and Machine Intelligence", "IEEE Trans. Pattern Anal. Mach. Intell."));
        standardIeeeList.add(new Abbreviation("IEEE Control Systems Magazine", "IEEE Control Syst. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Intelligent Transportation Systems Magazine", "IEEE Intell. Transp. Syst. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Industrial Electronics", "IEEE Trans. Ind. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on NanoBioscience", "IEEE Trans. Nanobiosci."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Engineering Management", "IEEE Trans. Eng. Manag."));
        standardIeeeList.add(new Abbreviation("IEEE ASSP Magazine", "IEEE ASSP Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Journal on Multiscale and Multiphysics Computational Techniques", "IEEE J. Multiscale and Multiphys. Comput. Techn."));
        standardIeeeList.add(new Abbreviation("IEEE Microwave Magazine", "IEEE Microw. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics C: Applications and Reviews", "IEEE Trans. Syst., Man, Cybern. C"));
        standardIeeeList.add(new Abbreviation("IEEE Internet of Things Journal", "IEEE Internet Things J."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Industry Applications", "IEEE Trans. Ind. Appl."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Magnetics", "IEEE Trans. Magn."));
        standardIeeeList.add(new Abbreviation("IEEE Revista Iberoamericana de Technolog'ias del Aprendizaje", "IEEE Revista Iberoamericana de Technolog'ias del Aprendizaje"));
        standardIeeeList.add(new Abbreviation("IEEE Power and Energy Technology Systems Journal", "IEEE Power Energy Technol. Syst. J."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Aerospace", "IEEE Trans. Aerosp."));
        standardIeeeList.add(new Abbreviation("IEEE/ACM Transactions on Networking", "IEEE/ACM Trans. Netw."));
        standardIeeeList.add(new Abbreviation("IEEE Life Sciences Letters", "IEEE Life Sci. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Industrial Informatics", "IEEE Trans. Ind. Informat."));
        standardIeeeList.add(new Abbreviation("IEEE IT Professional", "IEEE IT Prof."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Robotics", "IEEE Trans. Robot."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Aeronautical and Navigational Electronics", "IEEE Trans. Aeronaut. Navig. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Audio and Electroacoustics", "IEEE Trans. Audio Electroacoust."));
        standardIeeeList.add(new Abbreviation("IEEE Spectrum", "IEEE Spectr."));
        standardIeeeList.add(new Abbreviation("IEEE Wireless Communications", "IEEE Wireless Commun."));
        standardIeeeList.add(new Abbreviation("IEEE/OSA Journal of Display Technology", "IEEE/OSA J. Display Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Power and Energy Magazine", "IEEE Power Energy Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Reviews in Biomedical Engineering", "IEEE Rev. Biomed. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Embedded Systems Letters", "IEEE Embedded Syst. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Automatic Control", "IEEE Trans. Autom. Control"));
        standardIeeeList.add(new Abbreviation("Proceedings of the IEEE", "Proc. IEEE"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Education", "IEEE Trans. Educ."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Information Forensics and Security", "IEEE Trans. Inf. Forensics Security"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Software Engineering", "IEEE Trans. Softw. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Electron Devices Society", "IEEE J. Electron Devices Soc."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Autonomous Mental Development", "IEEE Trans. Auton. Mental Develop."));
        standardIeeeList.add(new Abbreviation("IEEE Power Electronics Letters", "IEEE Power Electron. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Multi-Scale Computing Systems", "IEEE Trans. Multi-Scale Comput. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Knowledge and Data Engineering", "IEEE Trans. Knowl. Data Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Bio-Medical Electronics", "IEEE Trans. Bio-Med. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Energy Conversion", "IEEE Trans. Energy Convers."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Quantum Electronics", "IEEE J. Quantum Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Antennas and Propagation", "IEEE Trans. Antennas Propag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Components and Packaging Technology", "IEEE Trans. Compon. Packag. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Intelligent Transportation Systems", "IEEE Trans. Intell. Transp. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Smart Grid", "IEEE Trans. Smart Grid"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Military Electronics", "IEEE Trans. Mil. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Industry Applications Magazine", "IEEE Ind. Appl. Mag."));
        standardIeeeList.add(new Abbreviation("Today's Engineer", "Today's Engineer"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Semiconductor Manufacturing", "IEEE Trans. Semicond. Manuf."));
        standardIeeeList.add(new Abbreviation("IEEE/ECS Electrochemical and Solid-State Letters", "IEEE/ECS Electrochem. Solid-State Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Photonics Journal", "IEEE Photon. J."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Robotics and Automation", "IEEE J. Robot. Autom."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Acoustics, Speech, and Signal Processing", "IEEE Trans. Acoust., Speech, Signal Process."));
        standardIeeeList.add(new Abbreviation("IEEE Communications Society Magazine", "IEEE Commun. Soc. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Nuclear Science", "IEEE Trans. Nucl. Sci."));
        standardIeeeList.add(new Abbreviation("IEEE Microwave and Wireless Components Letters", "IEEE Microw. Wireless Compon. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Rehabilitation Engineering", "IEEE Trans. Rehabil. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Network and Service Management", "IEEE Trans. Netw. Service Manag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Intelligent Vehicles", "IEEE Trans. Intell. Veh."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Parallel and Distributed Systems", "IEEE Trans. Parallel Distrib. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Control of Network Systems", "IEEE Trans. Control Netw. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Microwave and Guided Wave Letters", "IEEE Microw. Guided Wave Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Plasma Science", "IEEE Trans. Plasma Sci."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Microwave Theory and Techniques", "IEEE Trans. Microw. Theory Techn."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Electronics Packaging Manufacturing", "IEEE Trans. Electron. Packag. Manuf."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Man-Machine Systems", "IEEE Trans. Man-Mach. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE/ACM Transactions on Computational Biology and Bioinformatics", "IEEE/ACM Trans. Comput. Biol. Bioinformatics"));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Translational Engineering in Health and Medicine", "IEEE J. Transl. Eng. Health Med."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Nanotechnology", "IEEE Trans. Nanotechnol."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Power Apparatus and Systems", "IEEE Trans. Power App. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Services Computing", "IEEE Trans. Serv. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Computer Applications in Power", "IEEE Comput. Appl. Power"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Electromagnetic Compatibility", "IEEE Trans. Electromagn. Compat."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Consumer Electronics", "IEEE Trans. Consum. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Electron Device Letters", "IEEE Electron Device Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Cognitive and Developmental Systems", "IEEE Trans. Cogn. Develop. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Transportation Electrification", "IEEE Trans. Transport. Electrific."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology C: Manufacturing", "IEEE Trans. Compon., Packag., Manuf. Technol. C"));
        standardIeeeList.add(new Abbreviation("IEEE Design and Test of Computers", "IEEE Des. Test. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Nanotechnology Express", "IEEE Nanotechnol. Express"));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Selected Topics in Quantum Electronics", "IEEE J. Sel. Topics Quantum Electron."));
        standardIeeeList.add(new Abbreviation("IEEE/CAA Journal of Automatica Sinica", "IEEE/CAA J. Autom. Sinica"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems", "IEEE Trans. Circuits Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Mobile Computing", "IEEE Trans. Mobile Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Vehicular Communications", "IEEE Trans. Veh. Commun."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Microelectromechanical Systems", "J. Microelectromech. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Electron Devices", "IEEE Trans. Electron Devices"));
        standardIeeeList.add(new Abbreviation("IEEE Robotics and Automation Letters", "IEEE Robot. Autom. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Communications", "IEEE Trans. Commun."));
        standardIeeeList.add(new Abbreviation("IEEE Signal Processing Letters", "IEEE Signal Process. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Neural Networks", "IEEE Trans. Neural Netw."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Selected Topics in Signal Processing", "IEEE J. Sel. Topics Signal Process."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems for Video Technology", "IEEE Trans. Circuits Syst. Video Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Journal on Technology in Computer Aided Design", "IEEE J. Technol. Comput. Aided Design"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics: Systems", "IEEE Trans. Syst., Man, Cybern., Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Haptics", "IEEE Trans. Haptics"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Biomedical Circuits and Systems", "IEEE Trans. Biomed. Circuits Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Electrical Insulation", "IEEE Trans. Electr. Insul."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems I: Regular Papers", "IEEE Trans. Circuits Syst. I"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Very Large Scale Integration (VLSI) Systems", "IEEE Trans. VLSI Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Circuits and Systems II: Analog and Digital Signal Processing", "IEEE Trans. Circuits Syst. II"));
        standardIeeeList.add(new Abbreviation("IEEE/TMS Journal of Electronic Materials", "IEEE/TMS J. Electron. Mater."));
        standardIeeeList.add(new Abbreviation("IEEE Power Engineering Review", "IEEE Power Eng. Rev."));
        standardIeeeList.add(new Abbreviation("China Communications", "China Commun."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Ultrasonics, Ferroelectrics, and Frequency Control", "IEEE Trans. Ultrason., Ferroelectr., Freq. Control"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Industry and General Applications", "IEEE Trans. Ind. Gen. Appl."));
        standardIeeeList.add(new Abbreviation("IEEE Aerospace and Electronics Systems Magazine", "IEEE Aerosp. Electron. Syst. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Wireless Communications", "IEEE Trans. Wireless Commun."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Emerging Topics in Computing", "IEEE Trans. Emerg. Topics Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Robotics and Automation", "IEEE Trans. Robot. Autom."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Electronic Computers", "IEEE Trans. Electron. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Manufacturing Technology", "IEEE Trans. Manuf. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Personal Communications Magazine", "IEEE Personal Commun. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Antennas and Propagation Magazine", "IEEE Antennas Propag. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Medical Imaging", "IEEE Trans. Med. Imag."));
        standardIeeeList.add(new Abbreviation("IEEE Geoscience and Remote Sensing Letters", "IEEE Geosci. Remote Sens. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Multimedia", "IEEE Trans. Multimedia"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Power Electronics", "IEEE Trans. Emerg. Sel. Topics Power Electron."));
        standardIeeeList.add(new Abbreviation("IEEE ElectroTechnology Review", "IEEE ElectroTechnol. Rev."));
        standardIeeeList.add(new Abbreviation("IEEE Journal on Exploratory Solid-State Computational Devices and Circuits", "IEEE J. Explor. Solid-State Computat. Devices Circuits"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Sustainable Energy", "IEEE Trans. Sustain. Energy"));
        standardIeeeList.add(new Abbreviation("IEEE Software", "IEEE Softw."));
        standardIeeeList.add(new Abbreviation("IEEE Electrical Insulation Magazine", "IEEE Electr. Insul. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Biomedical and Health Informatics", "IEEE J. Biomed. Health Inform."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Dependable and Secure Computing", "IEEE Trans. Depend. Sec. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Engineering Management Review", "IEEE Eng. Manag. Rev."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Geoscience and Remote Sensing", "IEEE Trans. Geosci. Remote Sens."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology A", "IEEE Trans. Compon., Packag., Manuf. Technol. A"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Visualization and Computer Graphics", "IEEE Trans. Vis. Comput. Graphics"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems", "IEEE Trans. Comput.-Aided Design Integr. Circuits Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Systems, Man, and Cybernetics Magazine", "IEEE Syst., Man, Cybern. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics A: Systems and Humans", "IEEE Trans. Syst., Man, Cybern. A"));
        standardIeeeList.add(new Abbreviation("IEEE Technology and Society Magazine", "IEEE Technol. Soc. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Nanotechnology Magazine", "IEEE Nanotechnol. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Automation Science and Engineering", "IEEE Trans. Autom. Sci. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Neural Networks and Learning Systems", "IEEE Trans. Neural Netw. Learn. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Instrumentation and Measurement Magazine", "IEEE Instrum. Meas. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Signal and Information Processing over Networks", "IEEE Trans. Signal Inf. Process. Netw."));
        standardIeeeList.add(new Abbreviation("IEEE Geoscience and Remote Sensing Magazine", "IEEE Geosci. Remote Sens. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Computers", "IEEE Trans. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Pervasive Computing", "IEEE Pervasive Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Affective Computing", "IEEE Trans. Affect. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Aerospace and Navigational Electronics", "IEEE Trans. Aerosp. Navig. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Computer Architecture Letters", "IEEE Comput. Archit. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Access", "IEEE Access"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Reliability", "IEEE Trans. Rel."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Neural Systems and Rehabilitation Engineering", "IEEE Trans. Neural Syst. Rehabil. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE RFIC Journal", "IEEE RFIC J."));
        standardIeeeList.add(new Abbreviation("IEEE/ASME Journal of Microelectromechanical Systems", "J. Microelectromech. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Advanced Packaging", "IEEE Trans. Adv. Packag."));
        standardIeeeList.add(new Abbreviation("IEEE Power Electronics Magazine", "IEEE Power Electron. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Airborne Electronics", "IEEE Trans. Airborne Electron."));
        standardIeeeList.add(new Abbreviation("IEEE RFID Journal", "IEEE RFID J."));
        standardIeeeList.add(new Abbreviation("IEEE Computational Intelligence Magazine", "IEEE Comput. Intell. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Industrial Electronics and Control Instrumentation", "IEEE Trans. Ind. Electron. Contr. Instrum."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Network Science and Engineering", "IEEE Trans. Netw. Sci. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Cognitive Communications and Networking", "IEEE Trans. on Cogn. Commun. Netw."));
        standardIeeeList.add(new Abbreviation("IEEE Communications Letters", "IEEE Commun. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Control Systems Technology", "IEEE Trans. Control Syst. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Medical Electronics", "IEEE Trans. Med. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Communications Magazine", "IEEE Commun. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Multimedia", "IEEE Multimedia"));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Product Safety Engineering", "IEEE J. Product Safety Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Aerospace and Electronic Systems", "IEEE Trans. Aerosp. Electron. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Computational Science and Engineering Magazine", "IEEE Comput. Sci. Eng. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Cybernetics", "IEEE Trans. Cybern."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Parts, Hybrids and Packaging", "IEEE Trans. Parts, Hybrids, Packag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Big Data", "IEEE Trans. Big Data"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Molecular, Biological and Multi-Scale Communications", "IEEE Trans. Mol. Biol. Multi-Scale Commun."));
        standardIeeeList.add(new Abbreviation("IEEE Internet Computing", "IEEE Internet Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Sustainable Computing", "IEEE Sustain. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Systems Journal", "IEEE Syst. J."));
        standardIeeeList.add(new Abbreviation("IEEE/ACM Transactions on Audio, Speech, and Language Processing", "IEEE/ACM Trans. Audio, Speech, Language Process."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Solid-State Circuits", "IEEE J. Solid-State Circuits"));
        standardIeeeList.add(new Abbreviation("IEEE/OSA Journal of Lightwave Technology", "J. Lightw. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Journal on Selected Areas in Communications", "IEEE J. Sel. Areas Commun."));
        standardIeeeList.add(new Abbreviation("IEEE Annals of the History of Computing", "IEEE Ann. Hist. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Electromagnetic Compatibility Magazine", "IEEE Electromagn. Compat."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Cloud Computing", "IEEE Trans. on Cloud Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Photovoltaics", "IEEE J. Photovolt."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Ultrasonics Engineering", "IEEE Trans. Ultrason. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Components, Packaging and Manufacturing Technology B: Advanced Packaging", "IEEE Trans. Compon., Packag., Manuf. Technol. B"));
        standardIeeeList.add(new Abbreviation("Canadian Journal of Electrical and Computer Engineering", "Canadian J. Elect. Comput. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Industrial Electronics Magazine", "IEEE Ind. Electron. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE/ASME Transactions on Mechatronics", "IEEE/ASME Trans. Mechatronics"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Power Systems", "IEEE Trans. Power Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Magnetics Letters", "IEEE Magn. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Distributed Systems Online", "IEEE Distrib. Syst. Online"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Broadcasting", "IEEE Trans. Broadcast."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Audio, Speech, and Language Processing", "IEEE Audio, Speech, Language Process."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Communication Technology", "IEEE Trans. Commun. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Power Delivery", "IEEE Trans. Power Del."));
        standardIeeeList.add(new Abbreviation("IEEE Electrification Magazine", "IEEE Electrific. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Vehicular Technology", "IEEE Trans. Veh. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Circuits and Systems Magazine", "IEEE Circuits Syst. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Micro", "IEEE Micro"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics", "IEEE Trans. Syst., Man, Cybern."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Circuit Theory", "IEEE Trans. Circuit Theory"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Broadcast and Television Receivers", "IEEE Trans. Broadcast Television Receivers"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Components, Hybrids and Manufacturing Technology", "IEEE Trans. Compon., Hybrids, Manuf. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Signal Processing Magazine", "IEEE Signal Process. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Potentials", "IEEE Potentials"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Speech and Audio Processing", "IEEE Trans. Speech Audio Process."));
        standardIeeeList.add(new Abbreviation("IEEE Photonics Technology Letters", "IEEE Photon. Technol. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Audio", "IEEE Trans. Audio"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Human-Machine Systems", "IEEE Trans. Human-Mach. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Device and Materials Reliability", "IEEE Trans. Device Mater. Rel."));
        standardIeeeList.add(new Abbreviation("IEEE Intelligent Systems", "IEEE Intell. Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Information Theory", "IEEE Trans. Inf. Theory"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Information Technology in Biomedicine", "IEEE Trans. Inf. Technol. Biomed."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Sonics and Ultrasonics", "IEEE Trans. Sonics Ultrason."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Components and Packaging Technologies", "IEEE Trans. Compon. Packag. Technol."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Evolutionary Computation", "IEEE Trans. Evol. Comput."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing", "IEEE J. Sel. Topics Appl. Earth Observ. Remote Sens."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Instrumentation and Measurement", "IEEE Trans. Instrum. Meas."));
        standardIeeeList.add(new Abbreviation("IEEE Engineering in Medicine and Biology Magazine", "IEEE Eng. Med. Biol. Mag."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Component Parts", "IEEE Trans. Compon. Parts"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Computational Social Systems", "IEEE Trans. Comput. Social Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Radio Frequency Interference", "IEEE Trans. Radio Freq. Interference"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Systems, Man, and Cybernetics B: Cybernetics", "IEEE Trans. Syst., Man, Cybern. B"));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Emerging and Selected Topics in Circuits and Systems", "IEEE Trans. Emerg. Sel. Topics Circuits Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Antennas and Wireless Propagation Letters", "IEEE Antennas Wireless Propag. Lett."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Fuzzy Systems", "IEEE Trans. Fuzzy Syst."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Image Processing", "IEEE Trans. Image Process."));
        standardIeeeList.add(new Abbreviation("IEEE Journal of Oceanic Engineering", "IEEE J. Ocean. Eng."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Geoscience Electronics", "IEEE Trans. Geosci. Electron."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Signal Processing", "IEEE Trans. Signal Process."));
        standardIeeeList.add(new Abbreviation("IEEE Transactions on Learning Technologies", "IEEE Trans. Learn. Technol."));
    }

    public static List<Abbreviation> getOfficialAbbreviations() {
        return officialIeeeList;
    }

    public static List<Abbreviation> getStandardAbbreviations() {
        return standardIeeeList;
    }
}
