/*  Copyright (C) 2003-2011 JabRef contributors.
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

package net.sf.jabref.imports;

/**
 * Container class for lists with keywords where the case should be kept independent of bibstyle
 * 
 */
public class CaseKeeperList {
   
    // Common words in IEEE Xplore that should always be in the given case
   public String[] wordListIEEEXplore = new String[]{
        "1-D",
        "1D",
        "2-D",
        "2D",
        "3-D",
        "3D",
        "3G",
        "4G",
        "A/D",
	"ACM",
        "AC",
        "ADC",
        "ADI",
	"ADSL",
        "AES",
        "ALU",
        "AMPS",
        "AM",
        "ANOVA",
        "ANSI",
        "API",
        "ARQ",
        "ASIC",
	"ATM",
        "AVC",
        "AlGaAs",
        "Altera",
        "BCD",
        "BCH",
        "BER",
        "BIST",
        "BJT",
        "BPSK",
        "Bayes",
        "Bessel",
        "BiCMOS",
        "Bragg",
        "Butterworth",
        "CAD",
        "CATV",
        "CBR",
        "CDMA",
        "CIC",
        "CMOS",
        "CMRR",
	"CORDIC",
        "CPLD",
        "CPU",
        "CRC",
        "CSD",
        "CSIT",
        "CSI",
        "Carlo",
        "Cauer",
        "Chebyshev",
        "D/A",
        "DAB",
	"DAC",
	"DCT",
        "DC",
        "DDFS",
        "DDSM",
        "DDS",
        "DFE",
        "DFT",
	"DMT",
        "DNL",
        "DOCSIS",
        "DRM",
        "DSP",
	"DST",
        "DVB-C",
        "DVB-H",
        "DVB-S",
        "DVB-T",
        "DVB",
        "DVFS",
        "DVI",
        "DWT",
        "ECG",
        "ECL",
        "EDGE",
        "EEG",
        "EMC",
        "EMI",
        "ENOB",
        "EPROM",
        "FDTD",
        "FER",
        "FET",
        "FFT",
	"FIR",
	"FM",
        "FMCW",
        "FPGA",
	"Farrow",
        "Fourier",
        "GHz",
        "GNSS",
        "GPGPU",
        "GPRS",
        "GPS",
        "GPU",
        "GS",
        "GSM",
        "GaAs",
        "Galileo",
        "Gauss",
        "Gbps",
        "Gb/s",
        "H.264",
        "HARQ",
        "HBT",
        "HDMI",
        "HDTV",
        "HEMT",
        "HEVC",
        "Haar",
        "Hadamard",
        "Hamming",
        "Hilbert",
        "I/O",
        "I/Q",
        "IBM",
        "ICA",
        "IC",
        "IDCT",
        "IDFT",
        "IEEE",
        "IFFT",
        "IGBT",
        "IIR",
        "INL",
        "IO",
        "IPTV",
        "IP",
        "IQ",
        "ISDN",
        "ISI",
        "InP",
        "JPEG",
        "JTAG",
        "Kalman",
        "LAN",
        "LCD",
        "LDPC",
        "LED",
        "LNA",
        "LNS",
        "LSB",
        "LTE-A",
        "LTE",
        "LVDC",
        "LVDS",
        "Laplace",
        "MAC",
        "MAP",
        "MASH",
        "MCM",
        "MCU",
        "MEMS",
        "MHz",
        "MIMO",
        "MISO",
        "MMIC",
        "MMSE",
        "MOSFET",
        "MOS",
        "MPEG",
        "MRI",
        "MSB",
        "MSD",
        "MSPS",
        "MS",
        "MTCMOS",
        "Markov",
        "Maxwell",
        "Mbps",
        "Mb/s",
        "Miller",
        "Monte",
        "Msps",
        "NTSC",
        "Newton",
        "Nyquist",
        "OFDMA",
        "OFDM",
        "OSR",
        "OTA-C",
        "OTA",
        "P2P",
        "PAL",
        "PAM",
        "PAPR",
        "PCM",
        "PC",
        "PCI",
        "PID",
        "PLC",
        "PLL",
        "POTS",
        "PSRR",
        "PWM",
        "PowerPC",
        "QAM",
        "QPSK",
        "QRD",
        "QoS",
        "RAM",
        "RCS",
        "RF",
        "RFE",
        "RISC",
        "RLS",
        "RMS",
        "RNS",
        "ROM",
        "RSA",
        "Reed",
        "Remez",
        "SAR",
        "SAW",
        "SC",
        "SDR",
        "SFDR",
        "SIMO",
        "SINAD",
        "SINR",
        "SISO",
        "SNDR",
        "SNR",
        "SOI",
        "SQNR",
        "SVD",
        "SVM",
        "SerDes",
        "Shannon",
        "SiGe",
        "SoC",
        "Solomon",
        "TCP",
        "TDMA",
        "TFT",
        "THD",
        "TSPC",
        "TV",
        "UMTS",
        "UWB",
        "VBR",
        "VCO",
        "VDD",
        "VDSL",
        "VGA",
        "VHDL",
        "VLIW",
        "VLSI",
        "VOD",
        "VSB",
        "Vdd",
        "Verilog-AMS",
        "Verilog-A",
        "Verilog",
        "Viterbi",
        "VoD",
        "VoIP",
        "Volterra",
        "WCDMA",
        "WDF",
        "WLAN",
        "WWW",
        "WiMAX",
        "Winograd",
        "XML",
        "Xilinx",
        "dB",
        "kHz",
        "kS",
        "mW",
        "xDSL"
   };
    
   
   // List of all keyword lists
   private String[][] allLists = new String[][] {
       wordListIEEEXplore
   };
   
   public CaseKeeperList () {
   
   };
   /* Return all lists concatenated
    * Can be done faster once deciding on Java 6.0
    * see: http://stackoverflow.com/questions/80476/how-to-concatenate-two-arrays-in-java
    */
    public String[] getAll() {
        int lengh = 0;
        for (String[] array : allLists) {
            lengh += array.length;
        }
        String[] result = new String[lengh];
        int pos = 0;
        for (String[] array : allLists) {
            for (String element : array) {
                result[pos] = element;
                pos++;
            }
        }
        return result;
    }
}
