name: Full checkout and gradle setup
description: Full checkout and gradle setup
runs:
  using: composite
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: "5.x"
    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.2.1
    - uses: ./.github/actions/setup-gradle
