name: Format Java sources
description: Reformat Java sources using IntelliJ IDEA's code style

runs:
  using: composite
  steps:
    - uses: leventeBajczi/intellij-idea-format@db20da18da1ea0264171c370e2ea1922c7b3d18a # idea-2026.2.1
      with:
        file-mask: "*.java"
        settings-file: ".idea/codeStyles/Project.xml"
    - name: Undo JBang changes # IntelliJ issue: https://youtrack.jetbrains.com/issue/IDEA-https://youtrack.jetbrains.com/issue/IDEA-384956/Skip-formatting-of-shebang-headers/Skip-formatting-of-shebang-headers
      shell: bash
      run: git checkout HEAD -- jablib-examples/jbang/*.java
