plugins {
    id("java-platform")
}

javaPlatform {
    allowDependencies()
}

val javafx = "25"
val lucene = "10.3.0"
val pdfbox = "3.0.5"

dependencies {
    api(platform("ai.djl:bom:0.34.0"))
    api(platform("dev.langchain4j:langchain4j-bom:1.4.0"))
    api("dev.langchain4j:langchain4j")
    api("dev.langchain4j:langchain4j-google-ai-gemini")
    api("dev.langchain4j:langchain4j-hugging-face")
    api("dev.langchain4j:langchain4j-mistral-ai")
    api("dev.langchain4j:langchain4j-open-ai")
    api(enforcedPlatform("io.zonky.test.postgres:embedded-postgres-binaries-bom:17.6.0"))
}

dependencies.constraints {
    api("org.openjfx:javafx-base:$javafx")
    api("org.openjfx:javafx-controls:$javafx")
    api("org.openjfx:javafx-fxml:$javafx")
    api("org.openjfx:javafx-graphics:${javafx}")
    api("org.openjfx:javafx-swing:$javafx")
    api("org.openjfx:javafx-web:$javafx")

    api("com.ibm.icu:icu4j:72.0.1!!")

    api("com.dlsc.gemsfx:gemsfx:3.5.7")
    api("com.dlsc.pdfviewfx:pdfviewfx:3.1.1")
    api("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.20.0")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.20.0")
    api("com.fasterxml:aalto-xml:1.3.3")
    api("org.eclipse.lsp4j:org.eclipse.lsp4j:0.24.0")
    api("org.eclipse.lsp4j:org.eclipse.lsp4j.websocket:0.24.0")
    api("com.github.javakeyring:java-keyring:1.0.4")
    api("com.github.javaparser:javaparser-symbol-solver-core:3.27.1")
    api("com.github.jknack:handlebars-helpers:4.3.1") // Required by Wiremock - and our patching of Wiremock
    api("com.github.jknack:handlebars:4.3.1") // Required by Wiremock - and our patching of Wiremock
    api("com.github.koppor:wiremock-slf4j-shim:main-SNAPSHOT")
    api("com.github.koppor:wiremock-slf4j-spi-shim:main-SNAPSHOT")
    api("com.github.sialcasa.mvvmFX:mvvmfx-validation:f195849ca9") //jitpack
    api("com.github.tomtung:latex2unicode_2.13:0.3.2")
    api("com.github.vatbub:mslinks:1.0.6.2")
    api("com.google.guava:guava:33.4.8-jre")
    api("com.googlecode.plist:dd-plist:1.28")
    api("com.h2database:h2-mvstore:2.3.232")
    api("com.konghq:unirest-java-core:4.5.1")
    api("com.konghq:unirest-modules-gson:4.5.1")
    api("com.pixelduke:fxthemes:1.6.0")
    api("com.squareup.okhttp3:okhttp:5.1.0")
    api("com.squareup.okio:okio-jvm:3.16.0")
    api("com.squareup.retrofit2:retrofit:3.0.0")
    api("com.tngtech.archunit:archunit:1.4.1")
    api("com.tngtech.archunit:archunit-junit5-api:1.4.1")
    api("com.tngtech.archunit:archunit-junit5-engine:1.4.1")
    api("com.vladsch.flexmark:flexmark-html2md-converter:0.64.8")
    api("com.vladsch.flexmark:flexmark:0.64.8")
    api("commons-io:commons-io:2.20.0")
    api("commons-logging:commons-logging:1.3.5")
    api("de.rototor.snuggletex:snuggletex-jeuclid:1.3.0")
    api("de.saxsys:mvvmfx:1.8.0")
    api("de.undercouch:citeproc-java:3.3.0")
    api("info.debatty:java-string-similarity:2.0.0")
    api("info.picocli:picocli-codegen:4.7.7")
    api("info.picocli:picocli:4.7.7")
    api("io.github.adr:e-adr:2.0.0-SNAPSHOT")
    api("io.github.classgraph:classgraph:4.8.181")
    api("io.github.java-diff-utils:java-diff-utils:4.15")
    api("io.github.stefanbratanov:jvm-openai:0.11.0")
    api("io.github.thibaultmeyer:cuid:2.0.3")
    api("io.zonky.test.postgres:embedded-postgres-binaries-darwin-arm64v8")
    api("io.zonky.test.postgres:embedded-postgres-binaries-linux-arm64v8")
    api("io.zonky.test:embedded-postgres:2.1.1")
    api("jakarta.annotation:jakarta.annotation-api:3.0.0")
    api("jakarta.inject:jakarta.inject-api:2.0.1")
    api("jakarta.validation:jakarta.validation-api:3.1.1")
    api("jakarta.ws.rs:jakarta.ws.rs-api:4.0.0")
    api("net.bytebuddy:byte-buddy:1.17.6")
    api("net.harawata:appdirs:1.4.0")
    api("net.java.dev.jna:jna-jpms:5.18.0")
    api("net.java.dev.jna:jna-platform:5.18.0")
    api("org.antlr:antlr4-runtime:4.13.2")
    api("org.antlr:antlr4:4.13.2")
    api("org.apache.commons:commons-csv:1.14.0")
    api("org.apache.commons:commons-lang3:3.19.0")
    api("org.apache.commons:commons-text:1.14.0")
    api("org.apache.httpcomponents.client5:httpclient5:5.5")
    api("org.apache.logging.log4j:log4j-to-slf4j:2.25.2")
    api("org.apache.lucene:lucene-analysis-common:$lucene")
    api("org.apache.lucene:lucene-core:$lucene")
    api("org.apache.lucene:lucene-highlighter:$lucene")
    api("org.apache.lucene:lucene-queries:$lucene")
    api("org.apache.lucene:lucene-queryparser:$lucene")
    api("org.apache.pdfbox:fontbox:$pdfbox")
    api("org.apache.pdfbox:pdfbox:$pdfbox")
    api("org.apache.pdfbox:xmpbox:$pdfbox")
    api("org.apache.velocity:velocity-engine-core:2.4.1")
    api("org.bouncycastle:bcprov-jdk18on:1.82")
    api("org.controlsfx:controlsfx:11.2.2")
    api("org.eclipse.jgit:org.eclipse.jgit:7.3.0.202506031305-r")
    api("org.fxmisc.flowless:flowless:0.7.4")
    api("org.fxmisc.richtext:richtextfx:0.11.6")
    api("org.glassfish.grizzly:grizzly-framework:4.0.2")
    api("org.glassfish.grizzly:grizzly-http-server:4.0.2")
    api("org.glassfish.hk2:hk2-api:3.1.1")
    api("org.glassfish.hk2:hk2-locator:3.1.1")
    api("org.glassfish.hk2:hk2-utils:3.1.1")
    api("org.glassfish.jaxb:jaxb-runtime:4.0.6")
    api("org.glassfish.jersey.containers:jersey-container-grizzly2-http:3.1.10")
    api("org.glassfish.jersey.core:jersey-server:3.1.11")
    api("org.glassfish.jersey.inject:jersey-hk2:3.1.11")
    api("org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-grizzly2:3.1.10")
    api("org.hamcrest:hamcrest:3.0")
    api("org.hibernate.validator:hibernate-validator:9.0.1.Final")
    api("org.hisp.dhis:json-tree:1.8.1")
    api("org.jabref:afterburner.fx:2.0.0")
    api("org.jabref:easybind:2.3.0")
    api("org.jetbrains:annotations:26.0.2-1")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.0")
    api("org.jooq:jool:0.9.15")
    api("org.jsoup:jsoup:1.20.1")
    api("org.jspecify:jspecify:1.0.0")
    api("org.junit.jupiter:junit-jupiter-api:6.0.0")
    api("org.junit.jupiter:junit-jupiter-params:6.0.0")
    api("org.junit.jupiter:junit-jupiter:6.0.0")
    api("org.junit.platform:junit-platform-launcher:1.13.4")
    api("org.kordamp.ikonli:ikonli-javafx:12.4.0")
    api("org.kordamp.ikonli:ikonli-materialdesign2-pack:12.4.0")
    api("org.libreoffice:libreoffice:24.8.4")
    api("org.libreoffice:unoloader:24.8.4")
    api("org.mockito:mockito-core:5.20.0")
    api("org.ow2.asm:asm:9.8")
    api("org.postgresql:postgresql:42.7.7")
    api("org.slf4j:jul-to-slf4j:2.0.17")
    api("org.slf4j:slf4j-api:2.0.17")
    api("org.testfx:testfx-core:4.0.18")
    api("org.testfx:testfx-junit5:4.0.18")
    api("org.tinylog:slf4j-tinylog:2.7.0")
    api("org.tinylog:tinylog-api:2.7.0")
    api("org.tinylog:tinylog-impl:2.7.0")
    api("org.wiremock:wiremock:3.13.0")
    api("org.xmlunit:xmlunit-core:2.10.4")
    api("org.xmlunit:xmlunit-matchers:2.10.4")
    api("org.yaml:snakeyaml:2.5")
    api("tech.units:indriya:2.2.3")
}
