import org.gradle.nativeplatform.platform.internal.DefaultNativePlatform

plugins {
    id("java-platform")
}

javaPlatform {
    allowDependencies()
}

// Based on https://stackoverflow.com/questions/11235614/how-to-detect-the-current-os-from-gradle
val os = DefaultNativePlatform.getCurrentOperatingSystem()
val arch = DefaultNativePlatform.getCurrentArchitecture()
val javafx = if (os.isLinux && arch.name.equals("aarch64", ignoreCase = true)) "25" else "25.0.1"

val lucene = "10.3.2"
val pdfbox = "3.0.6"

dependencies {
    api(platform("ai.djl:bom:0.35.1"))
    api(platform("dev.langchain4j:langchain4j-bom:1.7.1"))
    api("dev.langchain4j:langchain4j")
    api("dev.langchain4j:langchain4j-google-ai-gemini")
    api("dev.langchain4j:langchain4j-hugging-face")
    api("dev.langchain4j:langchain4j-mistral-ai")
    api("dev.langchain4j:langchain4j-open-ai")
    api(enforcedPlatform("io.zonky.test.postgres:embedded-postgres-binaries-bom:18.1.0"))

    api(platform("org.junit:junit-bom:6.0.1"))
    api("org.junit.jupiter:junit-jupiter-api")
    api("org.junit.jupiter:junit-jupiter-params")
    api("org.junit.jupiter:junit-jupiter")
    api("org.junit.platform:junit-platform-launcher")

    api(platform("org.glassfish.grizzly:grizzly-bom:4.0.2"))
    api("org.glassfish.grizzly:grizzly-framework")
    api("org.glassfish.grizzly:grizzly-http-server")

    api(platform("org.glassfish.jersey:jersey-bom:4.0.0"))
    api("org.glassfish.jersey.containers:jersey-container-grizzly2-http")
    api("org.glassfish.jersey.core:jersey-server")
    api("org.glassfish.jersey.inject:jersey-hk2")
    api("org.glassfish.jersey.test-framework:jersey-test-framework-core")
    api("org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-grizzly2")

    api(platform("tools.jackson:jackson-bom:3.0.2"))
    api("tools.jackson.core:jackson-core")
    api("tools.jackson.core:jackson-databind")
    api("tools.jackson.dataformat:jackson-dataformat-yaml")
}

dependencies.constraints {
    api("org.openjfx:javafx-base:$javafx")
    api("org.openjfx:javafx-controls:$javafx")
    api("org.openjfx:javafx-fxml:$javafx")
    api("org.openjfx:javafx-graphics:${javafx}")
    api("org.openjfx:javafx-swing:$javafx")
    api("org.openjfx:javafx-web:$javafx")
    // from JavaFX25 onwards
    api("org.openjfx:jdk-jsobject:$javafx")

    api("cc.jilt:jilt:1.9")

    api("com.dlsc.gemsfx:gemsfx:3.6.2")
    api("com.dlsc.pdfviewfx:pdfviewfx:3.4.1")
    api("com.ibm.icu:icu4j:72.0.1!!")
    api("com.fasterxml:aalto-xml:1.3.4")
    api("org.eclipse.lsp4j:org.eclipse.lsp4j:0.24.0")
    api("org.eclipse.lsp4j:org.eclipse.lsp4j.websocket:0.24.0")
    api("com.github.ben-manes.caffeine:caffeine:3.2.3")
    api("com.github.javakeyring:java-keyring:1.0.4")
    api("com.github.javaparser:javaparser-symbol-solver-core:3.27.1")
    api("com.github.sialcasa.mvvmFX:mvvmfx-validation:f195849ca9") //jitpack
    api("com.github.tomtung:latex2unicode_2.13:0.3.2")
    api("com.github.vatbub:mslinks:1.0.6.2")
    api("com.google.errorprone:error_prone_core:2.44.0")
    api("com.google.guava:guava:33.5.0-jre")
    api("com.googlecode.plist:dd-plist:1.28")
    api("com.h2database:h2-mvstore:2.3.232")
    api("com.konghq:unirest-java-core:4.7.0")
    api("com.konghq:unirest-modules-gson:4.7.0")
    api("com.pixelduke:fxthemes:1.6.0")
    api("com.squareup.okhttp3:okhttp:5.1.0")
    api("com.squareup.okio:okio-jvm:3.16.4")
    api("com.squareup.retrofit2:retrofit:3.0.0")
    api("com.tngtech.archunit:archunit:1.4.1")
    api("com.tngtech.archunit:archunit-junit5-api:1.4.1")
    api("com.tngtech.archunit:archunit-junit5-engine:1.4.1")
    api("com.uber.nullaway:nullaway:0.12.10")
    api("com.vladsch.flexmark:flexmark-html2md-converter:0.64.8")
    api("com.vladsch.flexmark:flexmark:0.64.8")
    api("commons-io:commons-io:2.21.0")
    api("commons-logging:commons-logging:1.3.5")
    api("de.rototor.snuggletex:snuggletex-jeuclid:1.3.0")
    api("de.saxsys:mvvmfx:1.8.0")
    api("de.undercouch:citeproc-java:3.3.0")
    api("info.debatty:java-string-similarity:2.0.0")
    api("info.picocli:picocli-codegen:4.7.7")
    api("info.picocli:picocli:4.7.7")
    api("io.github.adr:e-adr:2.0.0")
    api("io.github.darvil82:terminal-text-formatter:2.3.0c")
    api("io.github.classgraph:classgraph:4.8.184")
    api("io.github.java-diff-utils:java-diff-utils:4.16")
    api("io.github.stefanbratanov:jvm-openai:0.11.0")
    api("io.github.thibaultmeyer:cuid:2.0.4")
    api("io.zonky.test.postgres:embedded-postgres-binaries-darwin-arm64v8")
    api("io.zonky.test.postgres:embedded-postgres-binaries-linux-arm64v8")
    api("io.zonky.test:embedded-postgres:2.1.1")
    api("jakarta.annotation:jakarta.annotation-api:3.0.0")
    api("jakarta.inject:jakarta.inject-api:2.0.1")
    api("jakarta.validation:jakarta.validation-api:3.1.1")
    api("jakarta.ws.rs:jakarta.ws.rs-api:4.0.0")
    api("net.bytebuddy:byte-buddy:1.18.2")
    api("net.harawata:appdirs:1.5.0")
    api("net.java.dev.jna:jna-jpms:5.18.1")
    api("net.java.dev.jna:jna-platform:5.18.1")
    api("net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:4.3.0")
    api("net.ltgt.nullaway:nullaway:2.3.0")
    api("org.antlr:antlr4-runtime:4.13.2")
    api("org.antlr:antlr4:4.13.2")
    api("org.apache.commons:commons-csv:1.14.0")
    api("org.apache.commons:commons-lang3:3.19.0")
    api("org.apache.commons:commons-text:1.14.0")
    api("org.apache.httpcomponents.client5:httpclient5:5.5")
    api("org.apache.logging.log4j:log4j-to-slf4j:2.25.2")
    api("org.apache.lucene:lucene-analysis-common:$lucene")
    api("org.apache.lucene:lucene-core:$lucene")
    api("org.apache.lucene:lucene-highlighter:$lucene")
    api("org.apache.lucene:lucene-queries:$lucene")
    api("org.apache.lucene:lucene-queryparser:$lucene")
    api("org.apache.pdfbox:fontbox:$pdfbox")
    api("org.apache.pdfbox:pdfbox:$pdfbox")
    api("org.apache.pdfbox:xmpbox:$pdfbox")
    api("org.apache.velocity:velocity-engine-core:2.4.1")
    api("org.bouncycastle:bcprov-jdk18on:1.82")
    api("org.controlsfx:controlsfx:11.2.2")
    api("org.eclipse.jgit:org.eclipse.jgit:7.5.0.202512021534-r")
    api("org.fxmisc.flowless:flowless:0.7.4")
    api("org.fxmisc.richtext:richtextfx:0.11.7")
    api("org.glassfish.hk2:hk2-api:3.1.1")
    api("org.glassfish.hk2:hk2-locator:3.1.1")
    api("org.glassfish.hk2:hk2-utils:3.1.1")
    api("org.glassfish.jaxb:jaxb-runtime:4.0.6")
    api("org.hamcrest:hamcrest:3.0")
    api("org.hibernate.validator:hibernate-validator:9.1.0.Final")
    api("org.hisp.dhis:json-tree:1.8.1")
    api("org.jabref:afterburner.fx:2.0.0")
    api("org.jabref:easybind:2.3.0")
    api("org.jetbrains:annotations:26.0.2-1")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.21")
    api("org.jooq:jool:0.9.15")
    api("org.jsoup:jsoup:1.21.2")
    api("org.jspecify:jspecify:1.0.0")
    api("org.kordamp.ikonli:ikonli-javafx:12.4.0")
    api("org.kordamp.ikonli:ikonli-materialdesign2-pack:12.4.0")
    api("org.libreoffice:libreoffice:24.8.4")
    api("org.libreoffice:unoloader:24.8.4")
    api("org.mockito:mockito-core:5.21.0")
    api("org.ow2.asm:asm:9.9")
    api("org.postgresql:postgresql:42.7.7")
    api("org.slf4j:jul-to-slf4j:2.0.17")
    api("org.slf4j:slf4j-api:2.0.17")
    api("org.testfx:testfx-core:4.0.18")
    api("org.testfx:testfx-junit5:4.0.18")
    api("org.tinylog:slf4j-tinylog:2.7.0")
    api("org.tinylog:tinylog-api:2.7.0")
    api("org.tinylog:tinylog-impl:2.7.0")
    api("org.xmlunit:xmlunit-core:2.10.4")
    api("org.xmlunit:xmlunit-matchers:2.10.4")
    api("org.yaml:snakeyaml:2.5")
    api("tech.units:indriya:2.2.3")
}
