name: Setup JDK and Gradle
description: Setup JDK and Gradle, optionally JBang

inputs:
  distribution:
    description: JDK distribution
    required: false
    default: corretto
  javaVersion:
    description: Java version
    required: false
    default: '25'
  setupJbang:
    description: Whether to set up JBang
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.javaVersion }}
        distribution: ${{ inputs.distribution }}
        check-latest: true
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        gradle-version: current
      env:
        GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: false
    - name: Generate JBang cache key
      id: cache-key
      if: inputs.setupJbang == 'true'
      shell: bash
      run: |
        echo "cache_key=jbang-$(date +%Y-%m)" >> $GITHUB_OUTPUT
    - name: Cache JBang
      if: inputs.setupJbang == 'true'
      uses: actions/cache@v6
      with:
        path: ~/.jbang
        key: ${{ steps.cache-key.outputs.cache_key }}
        restore-keys:
          jbang-
    - name: Setup JBang
      if: inputs.setupJbang == 'true'
      uses: jbangdev/setup-jbang@main
