name: Setup JDK, JBang, and gradle
description: Setup JDK, JBang and gradle

inputs:
  distribution:
    description: JDK distribution
    required: false
    default: corretto
  javaVersion:
    description: Java version
    required: false
    default: '25'

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.javaVersion }}
        distribution: ${{ inputs.distribution }}
        check-latest: true
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      env:
        GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
    - name: Generate JBang cache key
      id: cache-key
      shell: bash
      run: |
        echo "cache_key=jbang-$(date +%Y-%m)" >> $GITHUB_OUTPUT
    - name: Cache JBang
      uses: actions/cache@v5
      with:
        path: ~/.jbang
        key: ${{ steps.cache-key.outputs.cache_key }}
        restore-keys:
          jbang-
    - name: Setup JBang
      uses: jbangdev/setup-jbang@main
