name: Setup JDK, JBang, and gradle
description: Setup JDK, JBang and gradle
runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        java-version: '24'
        distribution: 'corretto'
        check-latest: true
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Cache LTWA
      uses: actions/cache@v5
      with:
        path: /tmp/ltwa_20210702.csv
        key: ltwa_20210702.csv
    - name: Generate JBang cache key
      id: cache-key
      shell: bash
      run: |
        echo "cache_key=jbang-$(date +%Y-%m)" >> $GITHUB_OUTPUT
    - name: Cache JBang
      uses: actions/cache@v5
      with:
        path: ~/.jbang
        key: ${{ steps.cache-key.outputs.cache_key }}
        restore-keys:
          jbang-
    - name: Setup JBang
      uses: jbangdev/setup-jbang@main
