name: Sparse checkout and gradle setup
description: Sparse checkout and gradle setup
runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'true'
        show-progress: 'false'
    - uses: ./.github/actions/gradle-setup
