name: "Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value:
        "Please use the GitHub issue tracker only for bug reports.
        Feature requests, questions and general feedback is now handled at http://discourse.jabref.org.
        Please make sure you looked into our [list of existing issues](https://github.com/jabref/JabRef/issues) before creating a new issue to avoid duplicates!"

  - type: dropdown
    attributes:
      label: JabRef version
      options:
        - "5.3 (latest release)"
        - "3.8.2"
        - Latest development branch build (please note build date below)
        - Other (please describe below)
      description: The version as shown in the about dialog.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating system
      multiple: false
      options:
        - Windows
        - GNU / Linux
        - macOS
        - Other (please describe below)
    validations:
      required: true

  - type: input
    attributes:
      label: Details on version and operating system
      description: OS Version, distribution, desktop environment, older JabRef version etc.
      placeholder: Ubuntu 21.04 with Plasma 5.22 / Windows 10 21H1 / macOS 10.14
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checked with the latest development build
      description: |
        Please always test if the bug is still reproducible in the latest development version. We are constantly improving JabRef and some bugs may already be fixed. If you already use a development version, ensure that you use the latest one.
        You can download the latest development build at: https://builds.jabref.org/main/ . **Please make a backup of your library before you try out this version.**
      options:
        - label: I made a backup of my libraries before testing the latest development version.
          required: true
        - label: I have tested the latest development version and the problem persists
          required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the behaviour
      description: A clear and concise description of what the bug is and how to make it occur.
      value: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Appendix
      description: "If applicable: An excerpt of the bibliography file, a screenshot, an excerpt of log (available in the error console) etc."
      value: |
        ...
        <details>

        <summary>Log File</summary>

        ```
        Paste an excerpt of your log file here
        ```

        </details>
    validations:
      required: false
