blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://discourse.jabref.org/
    about: Feature requests, questions and general feedback is handled at http://discourse.jabref.org
