package org.jabref.logic.util.io;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HexFormat;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import org.jabref.logic.util.BackupFileType;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BackupFileUtil {

    private static final Logger LOGGER = LoggerFactory.getLogger(BackupFileUtil.class);

    private BackupFileUtil() {
    }

    /// Determines the path of a new backup file (using the given extension)
    ///
    /// The file is named `<unique prefix>--<library file name>--<timestamp>.<extension>` and placed in the backup directory.
    ///
    /// _SIDE EFFECT_: Creates the directory.
    /// In case that fails, the backup is placed next to the library — still with the same name pattern,
    /// so it can never collide with (and overwrite) the library file itself.
    ///
    /// Note that this backup is different from the `.sav` file generated by
    /// [org.jabref.logic.exporter.AtomicFileOutputStream] while saving
    public static Path getPathForNewBackupFileAndCreateDirectory(Path targetFile, BackupFileType fileType, Path backupDir) {
        String extension = "." + fileType.getExtensions().getFirst();
        String timeSuffix = ZonedDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd--HH.mm.ss"));

        // We choose the data directory, because a backup file should survive cache cleanups
        Path directory = backupDir;
        try {
            Files.createDirectories(directory);
        } catch (IOException e) {
            directory = getDirectoryOfLibrary(targetFile);
            LOGGER.warn("Could not create backup directory {}, using {} instead", backupDir, directory, e);
        }
        String baseFileName = getUniqueFilePrefix(targetFile) + "--" + targetFile.getFileName() + "--" + timeSuffix;
        Path fileName = FileUtil.addExtension(Path.of(baseFileName), extension);
        return directory.resolve(fileName);
    }

    /// Lists the existing backups of the given library, oldest first.
    /// Name order is time order, because of the timestamp in the file name.
    ///
    /// In case there is no backup directory, the directory of the library is searched,
    /// because that is where [#getPathForNewBackupFileAndCreateDirectory] places backups then.
    public static List<Path> getExistingBackupFiles(Path targetFile, Path backupDir) {
        Path directory = Files.exists(backupDir) ? backupDir : getDirectoryOfLibrary(targetFile);
        String prefix = getUniqueFilePrefix(targetFile) + "--" + targetFile.getFileName();
        try (Stream<Path> files = Files.list(directory)) {
            return files.filter(path -> path.getFileName().toString().startsWith(prefix))
                        .sorted()
                        .toList();
        } catch (IOException e) {
            LOGGER.error("Could not list backup files in {}", directory, e);
            return List.of();
        }
    }

    /// Determines the most recent existing backup of the given library, see [#getExistingBackupFiles].
    public static Optional<Path> getPathOfLatestExistingBackupFile(Path targetFile, Path backupDir) {
        List<Path> backupFiles = getExistingBackupFiles(targetFile, backupDir);
        if (backupFiles.isEmpty()) {
            return Optional.empty();
        }
        return Optional.of(backupFiles.getLast());
    }

    private static Path getDirectoryOfLibrary(Path targetFile) {
        return targetFile.toAbsolutePath().getParent();
    }

    ///
    /// Determines a unique file prefix.
    ///
    ///
    /// When creating a backup file, the backup file should belong to the original file.
    /// Just adding a suffix to the filename, does not work in all cases:
    /// It may be possible that the user has opened "paper.bib" twice.
    /// Thus, we need to create a unique prefix to distinguish these files.
    ///
    public static String getUniqueFilePrefix(Path targetFile) {
        // Idea: use the hash code and convert it to hex
        // Thereby, use positive values only and use length 4
        int positiveCode = Math.abs(targetFile.hashCode());
        byte[] array = ByteBuffer.allocate(4).putInt(positiveCode).array();
        return HexFormat.of().formatHex(array);
    }
}
