package org.jabref.gui.copyfiles;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class CopyResultsDialogController {
	@FXML
	private TableView tvResult;
	@FXML
	private TableColumn colStatus;
	@FXML
	private TableColumn colMessage;
	@FXML
	private TableColumn colFile;

	// Event Listener on Button.onAction
	@FXML
	public void close(ActionEvent event) {
		// TODO Autogenerated
	}
}
