@startuml
|SuccessLane|
start
:Pass plain citation to GrobidCitationFetcher    ;
:Pass plain citation to external parser (GROBID)       ;
:Get the parsing results    ;
if (parsing successful       ) then (yes)
else (no)
    |FailLane|
    :Show Error Dialog  ;
    stop
endif
|SuccessLane|
:Parse TEI to BIB  ;
if (parsing successful?     ) then (yes)
else (no)
    |FailLane|
    :Show Error Dialog  ;
    stop
endif
|SuccessLane|
:Parse BIB to BibEntry   ;
if (parsing successful?     ) then (yes)
else (no)
    |FailLane|
    :Show Error Dialog  ;
    stop
endif
|SuccessLane|
:Show BibEntry to User    ;
stop
@enduml
