@startuml

[*] --> DialogWithParser : Pressed "New entry by plain text" or the parse Grobid button
DialogWithParser: TextArea: Enter a plain text
DialogWithParser --> EntryEditor : After successfully adding a entry
DialogWithParser --> FailedWindow : When some references could not be parsed
FailedWindow : Your failed to parse text
EntryEditor: Added BibEntry to new library or the current







@enduml
