@startuml

[*] --> DialogWithParser : Pressed "New entry by plain text" or the parse Grobid button
DialogWithParser: TextArea: Enter a plain text
DialogWithParser --> EntryEditor : After successfully adding a entry
EntryEditor: Added BibEntry to new library or the current







@enduml
