@startuml legend #White
legend right 
    |<#TECHNOLOGY>     | <#White> Existing class |
    |<#PeachPuff>      | <#White> New class |
    |<#SkyBlue>        | <#White> Modified class |
endlegend
@enduml