{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.adr",
    "module": "e-adr",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "e-adr-2.0.0-SNAPSHOT.jar",
          "url": "e-adr-2.0.0-SNAPSHOT.jar",
          "size": 9126,
          "sha512": "fb3b869899f88b39e7ff6d52be5ecd3f53ff5c94b06c043b91ede3891b5e6dc5b49580c6293770eeea50d8715379f142601ab4786344dd16caff5f49463f4004",
          "sha256": "386c9566218663b15de9142b52ab52776ab62836764701c25789c8e68dde4ce1",
          "sha1": "73e4f813ea70e55c61f5ea40e59a48a32c189946",
          "md5": "06871b5c1f81bddfce8029e61d8557b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "e-adr-2.0.0-SNAPSHOT.jar",
          "url": "e-adr-2.0.0-SNAPSHOT.jar",
          "size": 9126,
          "sha512": "fb3b869899f88b39e7ff6d52be5ecd3f53ff5c94b06c043b91ede3891b5e6dc5b49580c6293770eeea50d8715379f142601ab4786344dd16caff5f49463f4004",
          "sha256": "386c9566218663b15de9142b52ab52776ab62836764701c25789c8e68dde4ce1",
          "sha1": "73e4f813ea70e55c61f5ea40e59a48a32c189946",
          "md5": "06871b5c1f81bddfce8029e61d8557b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "e-adr-2.0.0-SNAPSHOT-sources.jar",
          "url": "e-adr-2.0.0-SNAPSHOT-sources.jar",
          "size": 6131,
          "sha512": "989a56949008dca82959b7e00d6f0e9734bb1e3da547ef4488e9547c5ed80c2c3dffe08d747f1bcb05ac4c7e3fc69e23935bc18e0854def897b36ae875218e29",
          "sha256": "6b16d64a19f783f988f45071f37e66a9bee1a09c58ef4fda8d0cf4c9ee751be4",
          "sha1": "58f983c9a0ed22eacc4c4c3bc834e8a2b4314a4b",
          "md5": "7dd38447818d0760553913ab8c4ac6a0"
        }
      ]
    }
  ]
}
