#!/bin/sh
# postinst script for my jabref
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [[ $EUID != 0 ]]; then
    # User-based install
    INSTALL_PATH="$HOME/.mozilla/native-messaging-hosts/"
else
    INSTALL_PATH="/usr/lib/mozilla/native-messaging-hosts/"
fi

\cp /opt/jabref/lib/org.jabref.jabref.json INSTALL_PATH

exit 0
