#!/bin/sh
# postrm script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)
set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Remove the native-messaging hosts script only if relative to the deb package
        for NATIVE_MESSAGING_JSON in "/usr/lib/mozilla/native-messaging-hosts/org.jabref.jabref.json"\
                                     "/etc/chromium/native-messaging-hosts/org.jabref.jabref.json"\
                                     "/etc/opt/chrome/native-messaging-hosts/org.jabref.jabref.json"\
                                     "/etc/opt/edge/native-messaging-hosts/org.jabref.jabref.json"; do
            if [ -e $NATIVE_MESSAGING_JSON ] && grep --quiet '"path": "/opt' $NATIVE_MESSAGING_JSON; then
                rm $NATIVE_MESSAGING_JSON
            fi
        done
        # Remove the auto-install triggers of the browser addon for chrom/chromium
        rm /opt/google/chrome/extensions/bifehkofibaamoeaopjglfkddgkijdlh.json
        rm /usr/share/google-chrome/extensions/bifehkofibaamoeaopjglfkddgkijdlh.json
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
