dist: focal
language: ruby
cache: bundler
rvm:
- 2.7.1
install:
- bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
- bundle update sheldon
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - secure: Ko9SzcdByE/HOMP7s9ddTpRdqahnO5LJ1MGJWX/cmymQc8fDRMgP9jgI6D/G5Ntgo6uGUO+xkcV5mBbOAoI5v8U2GQ5nICDXHdQrX8kJzve9JDiQJOy0c17TYi3d7bBeS1bOhy7E0TxHRax2wWWxDhqz80GwSo9JAhQbcusR/1U=
    - secure: Ov0xcwOVBSbc7uuCk0Qu+ILmh3HuFNa9PnfI363at9V3aG05oJHiTRseFXvfiHgK5663Wcytcl3DU+A2vYZSz7Y3ZGzcUzhlRBLMUfebncB2nAsX3NJsieJ6FoYlkRBZdzA2lzt3FVv99hebuZnU4OiANdnHFiLmFzeWRaPZfIQ=
  webhooks:
    urls:
    - https://shelbot.herokuapp.com/build
    - https://styles-update.zotero.org:8826/
    - https://styles-update.zotero.org:8827/
    on_success: always
    on_failure: always
    on_start: never
