package org.jabref.gui.actions;

/**
 * Global String constants for GUI actions
 */
@Deprecated
public enum Actions {
    ABBREVIATE_DEFAULT,
    ABBREVIATE_MEDLINE,
    ABBREVIATE_SHORTEST_UNIQUE,
    ADD_FILE_LINK,
    CLEANUP,
    DOWNLOAD_FULL_TEXT,
    EDIT,
    EDIT_PREAMBLE,
    EDIT_STRINGS,
    EXPORT_TO_CLIPBOARD,
    MAKE_KEY,
    MANAGE_SELECTORS,
    MERGE_DATABASE,
    PULL_CHANGES_FROM_SHARED_DATABASE,
    REPLACE_ALL,
    SAVE,
    SAVE_AS,
    SAVE_SELECTED_AS_PLAIN,
    SELECT_ALL,
    TOGGLE_GROUPS,
    UNABBREVIATE,
}
