name: Package JabRef Component
description: Package JabRef Component

inputs:
  component:
    required: true
  componentShort:
    required: true
  useEaJdk:
    required: true
  AssemblySemVer:
    required: true
  Major:
    required: true
  Minor:
    required: true
  InformationalVersion:
    required: true
  diskSpaceAvailable:
    required: true
  os:
    required: true
  displayName:
    required: true
  archivePortable:
    required: true
  should-jbundle:
    required: true
  upload-as-artifact:
    required: true
  archForDebianRepack:
    required: true
  suffix:
    required: true

runs:
  using: composite
  steps:
    - name: jpackage ${{ inputs.component }}
      shell: bash
      run: ./gradlew -i -PeaJdkBuild="${{ inputs.useEaJdk }}" -PprojVersion="${{ inputs.AssemblySemVer }}" -PprojVersionInfo="${{ inputs.InformationalVersion }}" :${{ inputs.component }}:jpackage
    - name: Smoke test ${{ inputs.component }}
      shell: bash
      run: |
        ./gradlew -PeaJdkBuild="${{ inputs.useEaJdk }}" -PprojVersion="${{ inputs.AssemblySemVer }}" -PprojVersionInfo="${{ inputs.InformationalVersion }}" :${{ inputs.component }}:run --args="--help"
    - name: Package ${{ inputs.component }} application image
      shell: bash
      if: ${{ inputs.archivePortable != 'NONE' }}
      run: |
        set -e
        ${{ inputs.archivePortable }}
    - name: Rename files
      shell: pwsh
      if: ${{ inputs.archivePortable != 'NONE' }}
      run: |
        get-childitem -Path '${{ inputs.component }}/build/packages/*/*' | rename-item -NewName {$_.name -replace "${{ inputs.AssemblySemVer }}","${{ inputs.Major }}.${{ inputs.Minor }}${{ inputs.suffix }}"}
    - name: Repack deb file for Debian
      if: ${{ (startsWith(inputs.os, 'ubuntu')) && (inputs.component == 'jabgui') }}
      shell: bash
      run: |
        cd ${{ inputs.component }}/build/packages/${{ inputs.os }}
        ls -l
        ar x jabref_${{ inputs.Major }}.${{ inputs.Minor }}${{ inputs.suffix }}${{ inputs.archForDebianRepack }}.deb
        rm jabref_${{ inputs.Major }}.${{ inputs.Minor }}${{ inputs.suffix }}${{ inputs.archForDebianRepack }}.deb
        zstd -d < control.tar.zst | xz > control.tar.xz
        zstd -d < data.tar.zst | xz > data.tar.xz
        ar -m -c -a sdsd jabref_${{ inputs.Major }}.${{ inputs.Minor }}${{ inputs.suffix }}${{ inputs.archForDebianRepack }}_repackaged.deb debian-binary control.tar.xz data.tar.xz
        rm debian-binary control.tar.* data.tar.*
        mv -f jabref_${{ inputs.Major }}.${{ inputs.Minor }}${{ inputs.suffix }}${{ inputs.archForDebianRepack }}_repackaged.deb jabref_${{ inputs.Major }}.${{ inputs.Minor }}${{ inputs.suffix }}.deb
    - name: Upload ${{ inputs.component }} packages to GitHub
      # background: true
      if: ${{ inputs.upload-as-artifact == 'true' && (inputs.archivePortable != 'NONE') }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.componentShort }} (${{ inputs.displayName }})
        path: |
          ${{ inputs.component }}/build/packages/${{ inputs.os }}/*.*
    - name: Upload ${{ inputs.component }} to builds.jabref.org (Linux, macOS)
      # background: true
      if: ${{ (inputs.diskSpaceAvailable == 'true') && (startsWith(inputs.os, 'macos') || startsWith(inputs.os, 'ubuntu')) && (inputs.archivePortable != 'NONE') }}
      shell: bash
      run: |
        rsync -rt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --itemize-changes --stats -e 'ssh -p 9922 -i sshkey -o StrictHostKeyChecking=no' ${{ inputs.component }}/build/packages/${{ inputs.os }}/ jrrsync@build-upload.jabref.org:/var/www/builds.jabref.org/www/${{ inputs.branchName }}/${{ inputs.displayName }}/
    - name: Upload ${{ inputs.component }} to builds.jabref.org (Windows)
      # background: true
      # jabsrv-cli doesn't have any installer and no archivePortable; thus we do not upload
      if: ${{ (inputs.diskSpaceAvailable == 'true') && (inputs.os == 'windows-latest') && (inputs.archivePortable != 'NONE') }}
      shell: cmd
      # for rsync installed by chocolatey, we need the ssh.exe delivered with that installation
      run: |
        rsync -rt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --itemize-changes --stats -e 'C:\ProgramData\chocolatey\lib\rsync\tools\bin\ssh.exe -p 9922 -i sshkey -o StrictHostKeyChecking=no' ${{ inputs.component }}/build/packages/${{ inputs.os }}/*.* jrrsync@build-upload.jabref.org:/var/www/builds.jabref.org/www/${{ inputs.branchName }}/${{ inputs.displayName }}/

    - name: ShadowJar ${{ inputs.component }}
      if: ${{ (inputs.os == 'ubuntu-22.04') }}
      shell: bash
      run: ./gradlew -PeaJdkBuild="${{ inputs.useEaJdk }}" -PprojVersion="${{ inputs.AssemblySemVer }}" -PprojVersionInfo="${{ inputs.InformationalVersion }}" :${{ inputs.component }}:shadowJar

    - name: jbundle ${{ inputs.component }}
      if: ${{ (inputs.os == 'ubuntu-22.04') && (inputs.should-jbundle == 'true') }}
      shell: bash
      run: |
        jbundle build --no-appcds --input . --gradle-project ${{ inputs.component }} --output ./build/jbundle/${{ inputs.componentShort }}-${{ inputs.displayName }}
    - name: jbundle JabGui filename fix (Windows)
      # if: ${{ inputs.os == 'windows-latest' }}
      if: false
      shell: bash
      run: |
        mv build/jbundle/${{ inputs.componentShort }}-${{ inputs.displayName }} build/jbundle/${{ inputs.componentShort }}-${{ inputs.displayName }}.exe
    - name: Test jbundle binary (smoke test)
      if: ${{ (inputs.os == 'ubuntu-22.04') && (inputs.should-jbundle == 'true') }}
      shell: bash
      run: |
        build/jbundle/${{ inputs.componentShort }}-${{ inputs.displayName }} --help
    - name: Upload jbundle artifact to GitHub
      # background: true
      if: ${{ (inputs.os == 'ubuntu-22.04') && (inputs.upload-as-artifact == 'true') && (inputs.should-jbundle == 'true') }}
      uses: actions/upload-artifact@v6
      with:
        name: jbundle-${{ inputs.displayName }}
        path: build/jbundle/${{ inputs.componentShort }}*
    - name: Upload jbundle artifact to builds.jabref.org
      # background: true
      if: ${{ (inputs.os == 'ubuntu-22.04') && (inputs.diskSpaceAvailable == 'true') && (inputs.should-jbundle == 'true') }}
      shell: bash
      run: |
        rsync -rt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --itemize-changes --stats \
          --rsync-path="mkdir -p /var/www/builds.jabref.org/www/${{ steps.gitversion.outputs.branchName }}/${{ matrix.displayName }}/jbundle && rsync" \
          -e 'ssh -p 9922 -i sshkey -o StrictHostKeyChecking=no' \
          build/jbundle/${{ inputs.componentShort }}-${{ inputs.displayName }}* \
          jrrsync@build-upload.jabref.org:/var/www/builds.jabref.org/www/${{ steps.gitversion.outputs.branchName }}/${{ matrix.displayName }}/jbundle/

    # After jbundle, because jbundle needs original filename
    - name: Rename ShadowJar
      if: ${{ (inputs.os == 'ubuntu-22.04') }}
      shell: pwsh
      run: |
        get-childitem -Path '${{ inputs.component }}/build/libs/*-all*.jar' | rename-item -NewName {$_.name -replace "${{ inputs.AssemblySemVer }}","${{ inputs.Major }}.${{ inputs.Minor }}${{ inputs.suffix }}"}
    - name: Upload ShadowJar to GitHub
      # background: true
      if: ${{ (inputs.upload-as-artifact == 'true') && (inputs.os == 'ubuntu-22.04') }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.componentShort }} (${{ inputs.displayName }})
        path: |
          ${{ inputs.component }}/build/libs/-*all.jar
    - name: Upload ${{ inputs.componentShort }} ShadowJar to builds.jabref.org (Linux)
      # background: true
      if: ${{ (inputs.diskSpaceAvailable == 'true') && (inputs.os == 'ubuntu-22.04') }}
      shell: bash
      run: |
        rsync -rt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --itemize-changes --stats -e 'ssh -p 9922 -i sshkey -o StrictHostKeyChecking=no' ${{ inputs.component }}/build/libs/*-all.jar jrrsync@build-upload.jabref.org:/var/www/builds.jabref.org/www/${{ inputs.branchName }}/${{ inputs.displayName }}/
