// This file is for IntelliJ's HTTP Client, available in the Ultimate Edition

GET https://localhost:6051

###

GET https://localhost:6051/libraries

###

GET https://localhost:6051/libraries/notfound

###

// if you have checkout the JabRef code at c:\git-repositories\jabref, then this
// will show the contents of your first opened library as BibTeX

GET https://localhost:6051/libraries/jabref-authors.bib-026bd7ec
Accept: application/x-bibtex

###

// if you have checkout the JabRef code at c:\git-repositories\jabref, then this
// will show the contents of your first opened library using CSL JSON

GET https://localhost:6051/libraries/jabref-authors.bib-026bd7ec
Accept: application/x-bibtex-library-csl+json

###

// if you have checkout the JabRef code at c:\git-repositories\jabref, then this
// will show the contents of your first opened library using json + embedded BibTeX

GET https://localhost:6051/libraries/jabref-authors.bib-026bd7ec
Accept: application/json
