name: jabref
adopt-info: jabref
icon: snap/gui/jabref.png
license: MIT
summary: Bibliography manager
description: |
  JabRef is an open source bibliography reference manager.
  Simplifies reference management and literature organization for academic researchers by leveraging BibTeX, native file format for LaTeX..
  To access files in external media (i.e., USB drives) you must run:
  `snap connect jabref:removable-media`
grade: stable
title: JabRef
donation: https://donations.jabref.org
issues: https://github.com/JabRef/jabref/issues
website: https://www.jabref.org/
source-code: https://github.com/JabRef/jabref
contact: web@jabref.org
confinement: strict
base: core24
compression: lzo
platforms:
  amd64:
    build-on: [ amd64 ]
    build-for: [ amd64 ]
  arm64:
    build-on: [ arm64 ]
    build-for: [ arm64 ]
plugs:
  home:
  unity7:
  opengl:
  network-bind:
  removable-media:

layout:
  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm

apps:
  jabref:
    command: bin/JabRef
    extensions: [ gnome ]

environment:
  _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
  GTK_USE_PORTAL: "1"

parts:
  mesa-fix:
    plugin: nil
    build-snaps:
      - mesa-2404/candidate  # Force it to look in candidate
  jabref:
    plugin: dump
    source:
      - on amd64 to amd64: https://builds.jabref.org/main/linux-amd64/JabRef-portable_linux.tar.gz
      - on arm64 to arm64: https://builds.jabref.org/main/linux-arm/JabRef-portable_linux_arm64.tar.gz
    stage-packages:
      - x11-utils
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(cat $SNAPCRAFT_PART_INSTALL/lib/app/.jpackage.xml | grep "app-version" | cut -d">" -f2 | cut -d"<" -f1)"
      rm $SNAPCRAFT_PART_INSTALL/bin/JabRef
  jabref-launcher:
    after:
      - jabref
    source: snap/local
    source-type: local
    plugin: dump
    organize:
      JabRef-launcher: bin/JabRef
  cleanup:
    after:
      - jabref
      - jabref-launcher
    plugin: nil
    build-snaps:
      - gnome-46-2404
      - mesa-2404/candidate
    override-prime: |
      set -eux
      for snap in "gnome-46-2404"; do  # List all content-snaps you're using here
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
      done
      for CRUFT in bug lintian man; do
          rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
