name: jabref
# adopt-info: jabref
version: 'master'
version-script: cat build.gradle | grep "^version =" | cut -d'"' -f2
icon: snap/gui/jabref.png
license: MIT
summary: Bibliography manager
description: JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.

grade: devel
confinement: strict
base: core18
license: MIT
architectures:
  - build-on: amd64

apps:
  jabref:
    command: bin/JabRef
    extensions: [gnome-3-28]
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - opengl
      - network-bind
      - removable-media

parts:
  jabref:
    plugin: dump
    source: build/distribution/JabRef-portable_linux.tar.gz
    # override-pull: |
    #   snapcraftctl pull
    #   snapcraftctl set-version "$(cat app/JabRef.cfg | grep "app.version=" | cut -d'=' -f2)"
    stage-packages:
      - x11-utils
