name: jabref
version: "git"
version-script: cat build.gradle | grep "^version =" | cut -d'"' -f2
#icon: snap/gui/jabref.png
summary: Bibliography manager
description: JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.

grade: devel
confinement: strict
base: core18
license: MIT
architectures:
  - build-on: amd64

apps:
  jabref:
    command: desktop-launch $SNAP/jabref/bin/JabRefMain
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - opengl
      - network-bind
      - removable-media
      - gnome-3-28-1804

plugs:
  gnome-3-28-1804:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804
    content: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes


parts:
  jabref:
    plugin: x_gradle
    source: .
    source-type: git
    stage-packages:
      - openjdk-11-jre
      - openjfx
      - x11-utils
    gradle-options: [jlink, -xtest]
    gradle-output-dir: 'build/image'
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
