name: jabref
version: "git"
version-script: cat build.gradle | grep "^version =" | cut -d'"' -f2
#icon: snap/gui/jabref.png
summary: Bibliography manager
description: JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.

grade: devel
confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  jabref:
    command: desktop-launch java -jar $SNAP/jar/JabRef-$SNAP_VERSION.jar
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - opengl
      - network-bind
      - removable-media

parts:
  jabref:
    plugin: gradle
    source: .
    source-type: git
    stage-packages:
      - openjdk-11-jre
      - openjfx
      - x11-utils
    gradle-options: [snapJar, -xtest]
    gradle-output-dir: 'build/releases'
    after: [desktop-gtk3]
