name: jabref
adopt-info: jabref
icon: snap/gui/jabref.png
license: MIT
summary: Bibliography manager
description: JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.

grade: devel
confinement: strict
base: core18
license: MIT
architectures:
  - build-on: amd64

apps:
  jabref:
    command: java/bin/JabRef
    extensions: [gnome-3-28]
    environment:
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - opengl
      - network-bind
      - removable-media

parts:
  jabref:
    plugin: x_gradle
    source: .
    source-type: git
    stage-packages:
      - x11-utils
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(cat build.gradle | grep "^version =" | cut -d'"' -f2)"
    gradle-options: [jlink, -xtest]
    gradle-output-dir: 'build/image'
    gradle-build-jar: false
  cleanup:
    after: [jabref]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
      set -eux
      cd /snap/gnome-3-28-1804/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;