name: jabref
adopt-info: jabref
icon: snap/gui/jabref.png
license: MIT
summary: Bibliography manager
description: JabRef is an open source bibliography reference manager. The native file format used by JabRef is BibTeX, the standard LaTeX bibliography format.

grade: devel
confinement: strict
base: core18
license: MIT
architectures:
  - build-on: amd64

apps:
  jabref:
    command: bin/JabRef
    extensions: [gnome-3-28]
  browser-proxy:
    command: lib/jabrefHost.py
    extensions: [gnome-3-28]

environment:
  _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA"
plugs:
  desktop:
  desktop-legacy:
  wayland:
  unity7:
  home:
  opengl:
  network-bind:
  removable-media:
  plugs:
    hostfs-mozilla-native-messaging-jabref:
      interface: system-files
      write:
      - /var/lib/snapd/hostfs/usr/lib/mozilla/native-messaging-hosts/org.jabref.jabref.json
    hostfs-chrome-native-messaging-jabref:
      interface: system-files
      write:
      - /var/lib/snapd/hostfs/etc/opt/chrome/native-messaging-hosts/org.jabref.jabref.json
    hostfs-chromium-native-messaging-jabref:
      interface: system-files
      write:
      - /var/lib/snapd/hostfs/etc/chromium/native-messaging-hosts/org.jabref.jabref.json
parts:
  jabref:
    plugin: dump
    source: build/distribution/JabRef-portable_linux.tar.gz
    # Use this source for debug purposes:
    # source: https://builds.jabref.org/master/JabRef-portable_linux.tar.gz
    stage-packages:
      - x11-utils
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(cat $SNAPCRAFT_PART_INSTALL/lib/app/JabRef.cfg | grep "app.version=" | cut -d'=' -f2)"
      sed -i 's|/opt/jabref/lib/jabrefHost.py|/snap/bin/jabref.browser-proxy|g' $SNAPCRAFT_PART_INSTALL/lib/native-messaging-host/*/org.jabref.jabref.json
