/*
 * Created on 09-Dec-2003
 */
package net.sf.jabref.labelPattern;


/*
 * Created on 09-Dec-2003
 */
 
/**
  * How this works:
  * The fields used to autogeneratr keys are stored in an ArrayList
  * with the first item of the list being a string representation of 
  * the key pattern and the second item the spacer character.
  * The order of the fields in the autogenerated key will match the
  * order of the fields in the ArrayList.
  *
  * Each entry type will have its own corrosponding ArrayList, to handle
  * this, we will have a Hashtable where an entry type > ArrayList.
  * There will be a default KP, which will parent a userdefined KP.
  * 
  * Upon generatring keys we will itentify the type of entry, fetch
  * the proper Array, store the spacer in a temp. String. By reading the
  * field in the Array, the proper value will be fetched and stored in a
  * StringBuffer, with the spacer between each field.
  * 
  * Btw. we wont allow for keys like [auth][year]_[pages], is this a 
  * problem?
  *
  * 
 * @author Ulrik Stervbo (ulriks AT ruc.dk)
 */
//public class DefaultLabelPatterns extends ListResourceBundle{
public class DefaultLabelPatterns extends LabelPattern{
	
    public DefaultLabelPatterns(){
	addLabelPattern("article", "[author]_[year]");
	addLabelPattern("book",	"[author]_[year]");
	addLabelPattern("booklet", "[author]_[year]");
	addLabelPattern("conference", "[author]_[year]");
	addLabelPattern("inbook", "[author]_[year]");
	addLabelPattern("incollection", "[author]_[year]");
	addLabelPattern("inproceedings", "[author]_[year]");
	addLabelPattern("manual", "[author]_[year]");
	addLabelPattern("mastersthesis", "[author]_[year]");
	addLabelPattern("misc",	"[author]_[year]");
	addLabelPattern("phdthesis", "[author]_[year]");
	addLabelPattern("proceedings","[author]_[year]");
	addLabelPattern("techreport", "[author]_[year]");
	addLabelPattern("unpublished", "[author]_[year]");
    }
}
