name: Add greeting to issues for first time contributors

on:
  issues:
     types:
       - labeled
  pull_request_target:
    types:
       - labeled

jobs:
  GreetingFirstTimeCodeContribution:
    if: ${{ github.event.label.name == 'FirstTimeCodeContribution' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: GreetingFirstTimeCodeContribution
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
        body: |
          Welcome to the vibrant world of open-source development with JabRef!

          Newcomers, we're excited to have you on board. Start by exploring our [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md) guidelines, and don't forget to check out our [workspace setup guidelines](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace) to get started smoothly.

          Having any questions or issues? Feel free to ask here on GitHub. Need help setting up your local workspace? Join the conversation on [JabRef's Gitter chat](https://gitter.im/JabRef/jabref). And don't hesitate to open a (draft) pull request early on to show the direction it is heading towards. This way, you will receive valuable feedback.

          Happy coding! 🚀
