name: Check dependencies

on:
  schedule:
    - cron:  '0 0 * * TUE' # Run every Tuesday (after dependabot, which runs Monday)

jobs:
  checkDependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'gradle'
      - name: Look for outdated dependencies
        run: ./gradlew -q checkOutdatedDependencies
      - name: Report issues
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/outdatedDependencies.md
