name: Check dependencies

on:
  schedule:
    - cron:  '0 0 * * TUE' # Run every Tuesday (after dependabot, which runs Monday)

jobs:
  checkDependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 15.0.1.j9-adpt
      - uses: actions/setup-java@v1
        id: setup-java
        with:
          java-version: 15.0.1
          jdkFile: ${{ steps.sdkman.outputs.file }}
      - name: Look for outdated dependencies
        run: ./gradlew -q checkOutdatedDependencies
      - name: Report issues
        if: failure()
        uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/outdatedDependencies.md
