on:
  schedule:
    - cron:  '0 0 * * SUN' # Run every Sunddy (before dependabot, which runs Monday)
  push:

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - run: |
          echo "$JAVA_HOME"
          echo "$JAVA_HOME_11_X64"
          ls -la /opt/hostedtoolcache/jdk/11.0.6
          which java
      - name: Update Gradle Wrapper
        uses: rahulsom/gradle-up@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
