name: Deployment

on: [push, pull_request]

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
         - os: ubuntu-latest
           displayName: linux
         - os: windows-latest
           displayName: windows
         - os: macOS-latest
           displayName: macOS
           
    runs-on: ${{ matrix.os }}
    name: Deploy on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Build with Gradle
      run: ./gradlew jlink
    - name: Save artifact
      uses: actions/upload-artifact@master
      with:
        name: JabRef-${{ displayName }}
        path: build/image
      
