name: Deployment

on: [push]

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
         - os: ubuntu-latest
           displayName: linux
         - os: windows-latest
           displayName: windows
         - os: macOS-latest
           displayName: macOS
           
    runs-on: ${{ matrix.os }}
    name: Deploy on ${{ matrix.displayName }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.4
    - name: Build with Gradle
      run: ./gradlew jlinkZip
    - name: Save artifact
      uses: actions/upload-artifact@master
      with:
        name: JabRef-${{ matrix.displayName }}
        path: build/image
    - name: Upload to build.jabref.org
      uses: garygrossgarten/github-action-scp@release
      with:
        local: build/image.zip
        remote: JabRef-${{ matrix.displayName }}.zip
        host: build-upload.jabref.org
        username: builds_jabref_org
        privateKey: ${{ secrets.buildJabRefPrivateKey }}
        port: 9922
}
      
