on:
  schedule:
    - cron:  '0 0 * * SUN' # Run every Sunddy (before dependabot, which runs Monday)
  push:

jobs:
  check_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Update Gradle Wrapper
        uses: rahulsom/gradle-up@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.5/x64/bin
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
