name: Adapt PR status labels

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-changes-required:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Adapt labels
        run: |
          gh issue --repo ${{ github.repository }} edit ${{ github.event.pull_request.number }} --remove-label "status: ready-for-review"
          gh issue --repo ${{ github.repository }} edit ${{ github.event.pull_request.number }} --remove-label "status: awaiting-second-review"
          gh issue --repo ${{ github.repository }} edit ${{ github.event.pull_request.number }} --add-label "status: changes-required"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
