name: On PR opened/updated

on:
  # _target is required
  pull_request_target:
  # default: opened, synchronize, reopened

jobs:
  conflicts_with_target:
    if: github.repository == 'JabRef/jabref'
    name: Conflicts with target branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: 'false'
      - name: Check PR mergeability
        id: check_mergeable
        run: |
          MERGEABLE=$(gh pr view --json mergeable ${{ github.event.pull_request.number }} --template '{{.mergeable}}')
          if [ "$MERGEABLE" == "CONFLICTING" ]; then
            echo "❌ Merge conflicts"
            exit 1
          fi
          echo "✅ No merge conflicts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload-pr-number:
    if: github.repository == 'JabRef/jabref'
    runs-on: ubuntu-latest
    steps:
      - name: Create pr_number.txt
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt
      - uses: actions/upload-artifact@v5
        with:
          name: pr_number
          path: pr_number.txt
