name: Adapt PR status labels (Check)

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  label-changes-required:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-slim
    permissions:
      contents: read
      actions: write
    steps:
      - name: Create pr_number.txt
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: pr_number
          path: pr_number.txt
