name: Run OpenRewrite

permissions:
  contents: write
  pull-requests: read

on:
  pull_request:
    paths:
      - '.github/workflows/run-openrewrite.yml'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to run OpenRewrite on'
        required: true
        type: string

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  rewrite:
    if: github.event_name == 'workflow_dispatch' || github.repository == 'JabRef/jabref'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'
          ref: ${{ inputs.branch || github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_TOKEN_JABREF_MACHINE_PR_APPROVE || github.token }}

      - uses: ./.github/actions/setup-gradle

      - name: Run rewrite
        run: gradle --no-configuration-cache :rewriteRun

      # Reformat code (because OpenRewrite does different indents)
      - uses: ./.github/actions/format-java

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Fix issues using OpenRewrite"
            git push
          fi
