name: Release binaries on GitHub

on:
  push:
    tags:
       - 'v*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    strategy:
      fail-fast: run
    name: Release binaries on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Get binaries from builds.jabref.org
        run:
          mkdir build
          cd build
          wget -m -r -nH --cut-dirs 2 --no-parent --accept=tar.gz,dmg,pkg,deb,rpm,zip,msi https://builds.jabref.org/tags/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: build/**
